### ISSUE TITLE
[Quest] The Apprentice's Request

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2691] opened 2018-11-15 09:07 UTC
**Description**: 
This quest cannot be turned in at Dama Wildmane (https://db.excalibur.ws/?npc=20494). The reason might be the quest is not complete upon taking the quest (It is a speak to someone type quest). Or it might be that Dama is a vendor and upon talking to her she will offer her wares right away having no dialog.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2304

**Comment by Evolvee** [comment] 2018-11-16 15:08
The quest has set few conditions, I guess you made it @Shanghi ?

**Comment by Shanghi** [comment] 2018-11-17 22:07
The conditions are global so that can't be it. The problem is:

```
A -> B
C -> no followup quest
D -> E
```

A/C/D are just breadcrumb quests sending you to the same town and should become unavailable if you take or do any others or their followup quests.
This quest is C. Currently you can take C, then take either B or E (because A and D are optional), then you won't be able to finish C. I'm not sure of the proper way to handle this kind of situation! I can't find any comments about it and it can't be tested on retail on because breadcrumb quests were changed.
1. don't allow B to be taken if you have C or D, which would be very confusing because they're unrelated quest lines
2. a core change that lets you complete the quest even though you wouldn't be able to accept it if you tried again

**Comment by Evolvee** [comment] 2018-11-18 09:45
The 2. can be done with conditions 19+20 I believe.

**Comment by Shanghi** [comment] 2018-11-18 23:15
This and a few others like it should be fixed in revision 2333.

**Closed by Shanghi** 2018-11-18 23:15 UTC
Labels: Misc, Quest
