### ISSUE TITLE
Stoneform Not Removing Bleed on Leo in SSC

### ISSUE THREAD

**Issue by Joeeak0324** [Atlantiss/NetherwingBugtracker#6255] opened 2019-09-01 02:50 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Leotheras the Blind's whirlwind bleed debuff is not dispellable by Stoneform. Last week it was, not sure if bug or not.

**Current behaviour**: Whirlwind dot applied, use Stoneform, bleed dot does not get removed and does full dmg, Stoneform goes on CD.

**Expected behaviour**:  Whirlwind dot applied, use Stoneform, bleed dot is removed and no damage is taken.

**Server Revision**:  220

**Comment by Easyfraggy** [comment] 2019-09-01 06:54
Need some proof that it should if possible - I'm pretty sure you are right that it should - would just be nice with some confirmation.

**Comment by The14me** [comment] 2020-07-08 18:07
If can remove bleed in AQ...its suppose to remove bleed in SSC too
https://classic.wowhead.com/spell=20594/stoneform#comments:id=4988

**Comment by Godmatik** [comment] 2024-07-19 04:19
![dfsfdsf](https://github.com/user-attachments/assets/f496f877-1999-42bb-9ee9-ee90a6830526)
![reretretret](https://github.com/user-attachments/assets/2d947fb9-2b32-4935-8e85-6499cc5e8797)
![zzzzzzzzz](https://github.com/user-attachments/assets/322c3ef2-e9f8-4477-9a73-e2cc5c581a87)

Nope - it very much appears that stoneform should not remove the Leotheras bleed.

So not a bug.

Closing.

**Closed by Godmatik** 2024-07-19 04:19 UTC
Labels: NPC
