### ISSUE TITLE
[Karazhan][Boss] Moroes vanish can be cancelled early

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3088] opened 2018-11-28 08:49 UTC
**Description**: 
On Monday we killed Moroes and his vanish phase broke after a few seconds, much earlier than intended.

**Current behaviour**:
His Vanish can be broken, either by dots or aoe spells.

**Expected behaviour**: 
Should not be able to break bis vanish early, it should last for it's full duration.

**Server Revision**:

**Comment by Easyfraggy** [comment] 2018-11-28 21:32
The cause for this is explained here https://github.com/Atlantiss/AtlantissTBCBT/issues/4368

**Comment by Drayo** [comment] 2018-12-02 01:14
It seems like spells that are in flight before he vanishes, but hit after he goes invisible break it. But I'm not exactly sure, it's hard to tell. 

This bug was very noticeable as a healer today because there are barely any breaks during the fight when it happens often. 
At the same time the fight becomes shorter and thus Garrote is not as dangerous as it should be.

**Comment by Wolffenstein** [comment] 2018-12-08 07:36
This should be fixed now.

**Closed by Wolffenstein** 2018-12-08 07:36 UTC
Labels: Raid, Spell
