### ISSUE TITLE
[Spell][Warrior] Spell Reflect damage

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7790] opened 2020-12-14 03:17 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
**Description**: Spell Reflect

**Current behaviour**: Spell Reflect takes spell damage, hit and penetration from Warrior and not caster of reflected spell

**Expected behaviour**: Reflected spell should take spell damage, spell hit and spell penetration from caster of the reflected spell.

**Server Revision**: 3563

**Comment by danbopes** [comment] 2020-12-14 03:21
Dupe of #7790

**Closed by danbopes** 2020-12-14 03:21 UTC
Labels: - Arena, Class: Warrior
