### ISSUE TITLE
Bugged mage quest (Investigate the blue recluse) 

### ISSUE THREAD

**Issue by Kraknes** [Atlantiss/NetherwingBugtracker#5508] opened 2019-03-29 17:58 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Bugged Quest for mage class: Investigate the Blue Recluse. 
**Current behaviour**:
Nothing happens when activating an item that should spawn enemies (Cantatoin of Manifestation". Have met others in the same area that had the same problems. Have happened for several days now.  
**Expected behaviour**: 
Should work and spawn enemies. 
**Server Revision**:

**Comment by ircfelix** [comment] 2019-03-30 05:36
For me it worked

**Comment by Kraknes** [comment] 2019-03-30 10:40
When did you do the quest? Have tried three times this whole week with no results.

**Comment by ircfelix** [comment] 2019-03-30 17:06
Sorry I mixed it up with the Horde counterpart of this quest, which worked fine for me during server launch.

**Comment by GEEMOU** [comment] 2019-03-31 09:26
Bamp, tried it today around 5AM EST, doesn't work.

**Comment by Kraknes** [comment] 2019-03-31 14:57
Did report it to GM who said they were informed about the issue and will resolve it quickly.

**Comment by danbopes** [comment] 2019-04-18 12:21
Dupe of #1071

**Comment by HolteUnderscore** [comment] 2019-04-26 14:02
Can confirm this is still bugged, tried numerous times today in various locations - The Cantation works but, no mobs spawn.

**Comment by Maggan68** [comment] 2019-05-05 06:15
Doesn´t work today either 2019-05-05

**Comment by Evolvee** [comment] 2019-05-28 23:52
rev 2971

**Comment by HolteUnderscore** [comment] 2019-05-30 10:50
This isn't fixed, I just tried it again and there is still nothing spawning when you click the scroll.

**Comment by Evolvee** [comment] 2019-05-30 13:01
because server isnt updated with the fix

**Comment by harley6665** [comment] 2020-04-05 22:20
I tried to complete the quest 3 times and unfortunately it can't be done.

**Comment by Evolvee** [comment] 2020-04-06 15:54
did you make a video of your tries? i would need to see how you did it, because when i try it it works for me

**Comment by harley6665** [comment] 2020-04-07 05:41
No i didn't

pon., 6 kwi 2020, 16:54 użytkownik Evolve <notifications@github.com>
napisał:

**Comment by Godmatik** [comment] 2024-07-13 14:51
Unable to reproduce

Tested it a few times - the elementals spawned and I was able to capture them each time. Also have not heard of this issue happening on Netherwing.

Closing.

**Closed by Godmatik** 2024-07-13 14:51 UTC
Labels: Class: Mage, Quest
