### ISSUE TITLE
Stuck in combat after duel

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#1843] opened 2018-10-23 23:12 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After a duel ends I got stuck in combat for no apparent reason. While it seems quite uncommon, it has happened on a few separate occasions. 

**Current behaviour**:
See above
**Expected behaviour**: 
After a duel ends, both players should drop combat, unless there is aggro from an external source.
**Server Revision**: 
2196

**Comment by zapsuu** [comment] 2018-10-24 18:53
I think that you fought with hunter or warlock. Any pet make combat bug. After recast pet by warlock the CB disappear after few seconds. Hunter have to dismiss pet to reset combat for enemy player.

The pet hasn't to attack you. It can just buff the warlock (stamina buff from Imp)/hunter (Spirit Bond) while he attack you, there should be any way to get combat with the pet and you will stack in combat bug.

I make a new subject for it.

**Comment by zapsuu** [comment] 2018-10-24 19:03
I think that you fought with warlock/hunter.

https://github.com/Atlantiss/NetherwingBugtracker/issues/1862

**Comment by Tenoutoften** [comment] 2018-12-11 16:36
Haven't managed to reproduce this, hard to figure it out the report is so incredibly vague... no mention of classes or what was done in the duel

**Comment by aresbrutus** [comment] 2018-12-11 16:41
Will close this, DM me on discord or comment here if you have additional proof or w/e.

**Comment by Waddy333** [comment] 2019-01-23 23:57
https://www.dropbox.com/s/k8by6ittbwpkzya/Desktop%202019.01.23%20-%2023.07.47.04.webm?dl=0

**Comment by aresbrutus** [comment] 2019-01-24 00:01
Seems to be visual.

**Comment by Drayo** [comment] 2020-07-11 09:19
I don't think this report will lead to anything. 

Way too little actual information and no way to reproduce this. It seems to have happened very rarely.

**Comment by Tereneckla** [comment] 2020-07-11 09:24
Also just visual. He is regenerating hp in the video

**Closed by Tereneckla** 2020-07-11 09:24 UTC
Labels: - Core Mechanic, PvP: Mechanics
