### ISSUE TITLE
"Ride the Lightning" quest

### ISSUE THREAD

**Issue by trovi123** [Atlantiss/NetherwingBugtracker#9026] opened 2024-04-05 09:40 UTC
[[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
](https://www.wowhead.com/tbc/quest=10657/ride-the-lightning#comments)[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: cant reuse quest item to get shild, if i right click buff from first use

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by trovi123** [comment] 2024-04-05 09:59
only restart of client helps

**Comment by Godmatik** [comment] 2024-07-01 19:38
Duplicate of #8393

**Closed as completed by Godmatik** 2024-07-01 19:38 UTC
