### ISSUE TITLE
[NPC] Booty Bay Bruisers not aggroing

### ISSUE THREAD

**Issue by Ahzdraheed** [Atlantiss/NetherwingBugtracker#7401] opened 2020-08-16 21:57 UTC
Hello, please excuse my ignorance regarding anything wrong with the format of the post, this is my absolute first time experience posting on GitHub.

**Description:** Booty Bay Bruisers (cannot say for other neutral goblin Bruisers) are not aggroing players, despite players performing certain actions that negatively impact the status of an opposing faction's player character. 

**Current behavior:** Neither paladin's Consecration AoE damage nor priest's Dispel Magic trigger have triggered an aggro response from Booty Bay Bruisers. 

**Expected behavior:** "Booty Bay Bruiser says: Get a rope!" :)

**Date of incident:** 16.08.2020 around 23:00 server time.

Thank you for your time, and let me once again apologize in advance for 
any and all potential imperfections of the form of my querry. 

Have a good day/evening/night!

**Comment by Tereneckla** [comment] 2021-03-04 21:35
Duplicate of #6854

**Closed by Tereneckla** 2021-03-04 21:35 UTC
Labels: PvP: Mechanics
