### ISSUE TITLE
Undercity Lift doors not opening

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#731] opened 2018-09-27 04:47 UTC
**Description**: bottom doors on the western lift dont open when it reaches the bottom. stayed in the lift a few minutes to check and they never opened when it reached the ground. tried the other two lifts and they work fine.

**Current behaviour**: lift doors do not open

**Expected behaviour**:  doors will open when you reach ground

**Server Revision**: 2072

https://streamable.com/cf3i4

**Comment by wtRCH** [comment] 2018-09-27 04:53
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/224

**Closed by wtRCH** 2018-09-27 04:53 UTC
