### ISSUE TITLE
[Durotar] Quilboar get stuck and unattackable on evade.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#7162] opened 2020-07-13 17:23 UTC
**Description**: 
![image](https://user-images.githubusercontent.com/36134067/87333844-07ef7800-c53e-11ea-929e-ca61ce9546a6.png)

**Current behaviour**:

Mobs get stuck when evading in this area a lot. Might cause issues on launch since they seem to never reset properly.
https://gfycat.com/meagerhappyasianlion
https://gfycat.com/deafeningplumpammonite
https://gfycat.com/offbeatscarylangur
https://gfycat.com/elementaryheartyblesbok

**Expected behaviour**: 
reset to position on evade.

**Server Revision**: 3482

**Comment by duzyizly** [comment] 2020-07-13 21:34
might be related https://github.com/Atlantiss/NetherwingBugtracker/issues/6849

**Comment by PaulStincuta** [comment] 2021-04-15 11:34
I also encountered i think exacly the same monster right now. Wanted to report but seeing that there is a post...any its really old..i guess its not worth reporting it since they wont fix it.

**Comment by Godmatik** [comment] 2024-07-31 13:34
Rev 4016 - no longer an issue, can not reproduce
Likely fixed with the pathing updates done last year.

**Closed by Godmatik** 2024-07-31 13:34 UTC
Labels: Movement, NPC, Status: Need Research
