### ISSUE TITLE
[NPC] Stormwind City Guard - wrong orientation (visual)

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#546] opened 2018-09-25 16:49 UTC
[NPC] Stormwind City Guard

**Current behaviour**:
Two guards leading to Old Town from Trade Disctrict face "the wall" rather than the road, which looks funny. I guess they have wrong orientation set.

![screenshot_3](https://user-images.githubusercontent.com/43505196/46029432-b0c3ad80-c0f3-11e8-8618-3d3014408b67.png)
![screenshot_4](https://user-images.githubusercontent.com/43505196/46029434-b1f4da80-c0f3-11e8-8cc6-0f9b9152907d.png)

**Expected behaviour**: 
Guards should face the road, not walls.

**Server Revision**: 
2050

**Comment by aresbrutus** [comment] 2018-09-25 19:27
Seems an issue on PTR so re-opening it.

**Comment by Firroth** [comment] 2018-09-26 16:58
Seems to be fixed now, so I can report can be closed.

**Comment by aresbrutus** [comment] 2018-09-26 17:01
Alright.

**Comment by Firroth** [comment] 2018-09-29 22:47
To not make different issue about it, I will just post in old one. Found another 2 guards facing wrong way. From Cathedral Square to Dwarven District.

![screenshot_3](https://user-images.githubusercontent.com/43505196/46251114-40e25980-c44a-11e8-96a5-0e65abec7d2b.png)

**Comment by aresbrutus** [comment] 2018-09-29 22:56
Re-opening since it seems to be a very weird issue which I don't know the cause of yet.

**Comment by aresbrutus** [comment] 2018-10-22 10:16
Seems to be working fine now? Closing it.

**Comment by aresbrutus** [comment] 2018-10-22 10:16
Seems to be working fine now? Closing it.

**Closed by aresbrutus** 2018-10-22 10:16 UTC
Labels: Movement, NPC

**Comment by aresbrutus** [comment] 2018-10-22 10:21
Seems to be working fine now?

**Comment by WhyAintThisFixedYet** [comment] 2018-12-07 15:50
![guard](https://user-images.githubusercontent.com/4724040/49657521-80f32900-fa05-11e8-8b3e-035e354a4382.jpg)
walking through SW to see this.

**Comment by aresbrutus** [comment] 2018-12-07 15:51
No npc info, no information what they were doing.

Can't help you there.

**Comment by eedijs** [comment] 2019-03-01 13:39
I'd like to revive this - several guards in Stormwind are out of position and inside of each other (Trade district, Mage quarters etc.).
