### ISSUE TITLE
[Talent][Paladin] One-handed weapon specialization

### ISSUE THREAD

**Issue by zodis6** [Atlantiss/NetherwingBugtracker#5242] opened 2019-02-27 10:24 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work )https://www.wowhead.com/forums&topic=13710
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Talent][Paladin] One-handed weapon specialization https://i.imgur.com/BiTLFh8.jpg
 

**Current behaviour**:Talent doesnt increase holy dmg from paladin spells

**Expected behaviour**: Should increace all dmg from paladin sorsuces https://www.wowhead.com/forums&topic=13710  keep in mind all spells on screenshots have flat dmg
Consecration w/o talent![wowscrnshot_022719_124102](https://user-images.githubusercontent.com/48017449/53482896-54452f80-3a91-11e9-8e68-272578159ee3.jpg)
Consecration with talent![wowscrnshot_022719_125809](https://user-images.githubusercontent.com/48017449/53482953-763eb200-3a91-11e9-96be-277ed8aad61f.jpg)
Holy shield w/o talent 
![wowscrnshot_022719_124048](https://user-images.githubusercontent.com/48017449/53483227-198fc700-3a92-11e9-9955-ab39277b40ef.jpg)

Holy shield with talent 
![wowscrnshot_022719_131430](https://user-images.githubusercontent.com/48017449/53483263-2f9d8780-3a92-11e9-9541-216220072569.jpg)

Blessing of Sanctury w/o talent 
![wowscrnshot_022719_124134](https://user-images.githubusercontent.com/48017449/53483322-4ba12900-3a92-11e9-9291-78125a6c3a93.jpg)
Blessing of Sanctury with talent
![wowscrnshot_022719_131527](https://user-images.githubusercontent.com/48017449/53483393-755a5000-3a92-11e9-8e89-ba2d60b875f6.jpg)
Ret aura w/o talent 
![wowscrnshot_022719_124308](https://user-images.githubusercontent.com/48017449/53483448-96bb3c00-3a92-11e9-9f13-f51b07c3434f.jpg)
Ret aura with talent 
![wowscrnshot_022719_131420](https://user-images.githubusercontent.com/48017449/53483481-a33f9480-3a92-11e9-951a-dbb90f134696.jpg)
SoR w/o talent
![wowscrnshot_022719_124226](https://user-images.githubusercontent.com/48017449/53483549-c10cf980-3a92-11e9-8fa5-d26ca5c96ebd.jpg)
SoR with talent 
![wowscrnshot_022719_131544](https://user-images.githubusercontent.com/48017449/53483580-d2ee9c80-3a92-11e9-93b0-06537f389de6.jpg)

**Server Revision**: 2851

**Comment by towneh** [comment] 2019-02-27 11:04
Interesting that this is no longer working, it was previously raised under https://github.com/Atlantiss/NetherwingBugtracker/issues/4910 and then withdrawn after being confirmed to work by both the author and @tenoutoften

**Comment by totalscrubking** [comment] 2019-02-28 22:23
honestly i never tested it again to confirm if it worked and i closed it because he said it was working

**Comment by zodis6** [comment] 2019-03-10 14:19
Is it realy hard to fix?

**Comment by Tenoutoften** [comment] 2019-03-19 17:51
This should be very easy to fix @zodis6

**Comment by Wolffenstein** [comment] 2019-04-06 21:42
Fixed in rev 2933.

**Closed by Wolffenstein** 2019-04-06 21:42 UTC
