### ISSUE TITLE
[Lootsystem] FFA when Masterloot set after killing the boss.

### ISSUE THREAD

**Issue by Suzaru** [Atlantiss/NetherwingBugtracker#6464] opened 2019-12-05 20:10 UTC
**Current behaviour**:
Loot is set to group loot while killing the boss. Everybody passes. Lootmaster is put in. Loot is FFA and not Lootmaster.

**Expected behaviour**: 
If everybody passed and you put in lootmaster, you should be able to assign it like it would be when you killed the boss with lootmaster in the first place.

**Server Revision**: 
3199

**Comment by Wolffenstein** [comment] 2019-12-05 20:44
Emm... any sources for that?

**Comment by Suzaru** [comment] 2019-12-05 20:54
Quite frankly, i don't. But it's kinda logic right? When i put in Lootmaster, you're not supposed to be able to just take all the stuff?

And since i've been raidleading TBC since retail TBC, i remember it that way. But I know its not evidence and memories deceive people.

**Comment by Wolffenstein** [comment] 2019-12-05 21:10
Well the loot method is set when the mob dies. If it was set to group loot and rolls happened, everything passed on simply becomes FFA, not sure why setting method to master loot afterwards is supposed to affect that.

**Comment by Suzaru** [comment] 2019-12-05 21:16
Because in Hyjal for example you play with grouploot all the time and it happens, that you forget to put in masterlooter - what makes ninjalooting possible.
I do not get what the downside of that would be?

**Comment by Easyfraggy** [comment] 2019-12-05 21:39
You just have to not forget to change the loot setting or simply set Masterlooter the whole time with Epic threshold. That way the greens and blues etc are rolled with group loot but the epics are dealt with by the masterlooter.

**Comment by Suzaru** [comment] 2019-12-05 22:00
Actually, thats a bad idea. If the masterlooter is out of range and an epic drops, its lost. With grouplooting the window will pop up for people in range. 
It's just dangerous that people and loot ffa when lootmaster is set and very counterintuitive.

**Comment by Easyfraggy** [comment] 2019-12-06 20:34
This is not a bug.

**Comment by Suzaru** [comment] 2019-12-06 23:25
Well it was different back in the day. Sadly I tried hours to find proof, but a question this specific is hard to find proof for. So I hope you guys reflect about it and work with reason on the subject.

**Comment by Easyfraggy** [comment] 2019-12-07 07:03
No it was not different back in the day unless you mean previously on this server.

Loot was always decided on mob death. If you had wrong settings when the mob died that is your problem.

**Comment by Suzaru** [comment] 2019-12-07 11:58
Alright then :). Let's agree to disagree. Thanks for your hard work anyways, both of you. Appreciate it!

**Comment by Suzaru** [comment] 2019-12-08 21:38
Btw. it doesn't work the other way around aswell. So if you kill the boss with Masterloot, you can not put it into FFA. I'm even more sure that this is not right ;). Just saying!

**Comment by Easyfraggy** [comment] 2019-12-08 22:15
I don't know if you ever did Vashj on retail when the ML forgot to change loot threshold? 

Well I can tell you if he didn't change to FFA before the tainted elemental died you could not change it afterwards to salvage it.

**Comment by DaedalusMachina007** [comment] 2019-12-17 17:54
The current behavior is correct for TBC; I was focused on raiding T6 at the time in a very hefty progression guild so I wouldn't know about random runs.

Set the loot ahead of time and stay in range.  If you cannot manage to do that then you cannot complain when loot gets 'lost' or otherwise.  If you're setting ML then you are likely doing a friends/guild run because random puggers rarely (if ever) are ok with that kind of thing.

**Comment by Wolffenstein** [comment] 2019-12-17 22:31
Closing for now. If any information is found I will change the behaviour.

**Closed by Wolffenstein** 2019-12-17 22:31 UTC
