### ISSUE TITLE
[Spell][Paladin] Consecration

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2502] opened 2018-11-09 14:22 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/43505031/48619736-c475ec80-e99d-11e8-9293-a5064a9566c3.png)

**Current behaviour**:
Using Consecration does not trigger combat:
![wowscrnshot_110918_151730](https://user-images.githubusercontent.com/43505031/48267590-04375400-e433-11e8-8d06-18feec44dc27.jpg)
![wowscrnshot_111618_124313](https://user-images.githubusercontent.com/43505031/48619762-d9528000-e99d-11e8-9681-1f04b541a06c.jpg)
![wowscrnshot_111618_124603](https://user-images.githubusercontent.com/43505031/48619782-e7a09c00-e99d-11e8-8a23-24cbcbc6cdb6.jpg)

If I am in combat with something else and I accidentally hurt the drake with my consecration then the mob doesn't attack me, but I stay in combat until the drake is alive:
![wowscrnshot_110918_151751](https://user-images.githubusercontent.com/43505031/48267633-20d38c00-e433-11e8-95d0-9c29e0b21b54.jpg)
![wowscrnshot_110918_151806](https://user-images.githubusercontent.com/43505031/48267640-25984000-e433-11e8-8277-78848d87234e.jpg)

**Expected behaviour**: 
Consecration should put me in combat.

**Server Revision**: 
2270

**Comment by Mikik3jr** [comment] 2018-11-16 11:51
I refreshed this report, because it is not specific, but global issue.

**Comment by Tenoutoften** [comment] 2018-12-13 10:38
This is duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/1757

**Closed** 2018-12-13 10:56 UTC
Labels: Class: Paladin, Misc, NPC
