### ISSUE TITLE
[Spell][Hunter] Feign Death ability can't be used

### ISSUE THREAD

**Issue by Lualie** [Atlantiss/NetherwingBugtracker#3652] opened 2018-12-25 16:49 UTC
**Description**: The feign death ability is occasionally not able to be used or clicked when mid-combat in dungeons. This is not referring to the resist chance - it won't let me even use the ability in the first place. I've tried two different clients with the same issue, and this has only been happening the last week or so.

**Current behaviour**: Feign death ability cannot be used or clicked occasionally when in combat in dungeons. The ability can be used if you're not in combat and/or spamming the ability mid-combat.

**Expected behaviour**: Should be able to feign mid-combat whenever you want, whether you're shooting, pet is attacking, etc.

**Server Revision**:

**Comment by Wolffenstein** [comment] 2018-12-26 14:32
I need more information, a video for example.

**Comment by Easyfraggy** [comment] 2018-12-26 19:09
Can't reproduce - were you oom?

**Comment by mbzz88** [comment] 2018-12-27 01:56
I've had this happen a couple of times, it seems pretty random/rare.
Haven't been able to reproduce on demand.
AFAIK it was always when fighting multiple mobs, Bloodelves in Netherstorm was one place (Sunfury Conjurer and Sunfury Bowman).

Pressing a hotkey to cast does nothing, either with a macro or the spell directly placed on actionbar, clicking FD from spellbook, or typing /cast Feign Death all had the same effect.

Simply nothing happens, pressing Esc a bunch of times, or ALT, before trying to cast, makes no difference.
Had full (or close to full) mana, there's no error message or anything, it's like you're clicking a blank macro.

Pet was always active when this occurred, and in combat.

**Comment by Lualie** [comment] 2018-12-27 02:00
> Can't reproduce - were you oom perhaps?

Nope, I wasn't out of mana. It just doesn't register the cast, as mbzz mentioned. I wouldn't say it's rare, however. It happens to me quite often.

**Comment by Thugli** [comment] 2018-12-27 06:17
Does the icon become greyed out? Similarly to this?**https://github.com/Atlantiss/NetherwingBugtracker/issues/2096**

**Comment by Wolffenstein** [comment] 2018-12-27 14:34
A recording would be quite useful.

**Comment by Zarant** [comment] 2018-12-31 19:20
Sometimes the spell goes off but the spell cooldown doesn't show up on the game client. If you try to use it again, the server returns an error saying that the spell is not ready yet. I managed to reproduce it consistently by canceling a cast mashing the feign death button using the following macro:

```
/stopcasting
/stopcasting
/cast Feign Death
```

https://streamable.com/eqjb5

**Comment by Zarant** [comment] 2019-02-01 18:41
@Wolffenstein Any respectable hunter player will macro stopcasting into feign death. This spell should trigger its cooldown as soon as the buff is removed, and if you mash the macro I just mentioned the spell cooldown is not displayed at all.

**Comment by Kristoferhh** [comment] 2019-05-04 21:36
Just wiped on a boss we would have killed for the first time because my FD was bugged meaning I had to auto attack half the fight. Please fix this jesus christ.

**Comment by Zarant** [comment] 2020-07-07 18:50
Issue still persists, spells that trigger their cooldown upon losing an aura (like Nature's Swiftness and Feign Death) don't seem to behave properly when you use them with a stopcasting macro.

As a half arsed measure I modified the OmniCC addon to show the feign death cooldown client side whenever you lose the feign death aura: https://github.com/Zarant/OmniCC

**Comment by Wolffenstein** [comment] 2020-07-07 22:15
Fixed in rev 3457.

**Closed by Wolffenstein** 2020-07-07 22:15 UTC
Labels: Status: Need Research
