### ISSUE TITLE
Farming and Herbing

### ISSUE THREAD

**Issue by KidKrazy78** [Atlantiss/NetherwingBugtracker#6240] opened 2019-08-24 00:41 UTC
Where is all the Sun Grass located? I've been to 3 places Feralas, The Hinterlands and Felwood. Trying to bring up my Herblism and seem I can't get past 240 cause the lack of herbs. Please help.

**Comment by danbopes** [comment] 2019-08-26 08:24
Dupe of #5687

**Closed** 2019-08-31 00:33 UTC
