### ISSUE TITLE
Childrens Week quests

### ISSUE THREAD

**Issue by LoGReeper** [Atlantiss/NetherwingBugtracker#453] opened 2018-09-25 00:24 UTC
**Description**: Childrens Week first 3 quests auto completing without going to the destinations.

**Current behaviour**: When you accept each of the first 3 quests, it auto completes without you taking the child to the destinations : https://i.imgur.com/LZMYXHd.png

**Expected behaviour**:  Take your child to each destination and use the whistle to summon your child to hand in.

**Server Revision**:

**Comment by wtRCH** [comment] 2018-09-25 01:30
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/146

**Closed by wtRCH** 2018-09-25 01:30 UTC
