### ISSUE TITLE
Target Dummy is not dropping parts

### ISSUE THREAD

**Issue by Shakikka** [Atlantiss/NetherwingBugtracker#3936] opened 2019-01-08 09:26 UTC
Target Dummy is not dropping parts (fused wiring, copper bolts, etc).

**Comment by Tim130** [comment] 2019-03-24 09:03
Yes thats a big problem for engineering, ´cause we need the "fused wiring" for crafting.

Source:
https://vanilla-twinhead.twinstar.cz/?npc=2674#drop

**Comment by Kolmarwow** [comment] 2019-03-28 15:49
Seconded, this is a very annoying issue for engineers until patch 2.1 where the fused wiring schematic gets added. The only way to get fused wirings atm is to kill robots in Gnomeregan which is a bit dreadful.

**Comment by Evolvee** [comment] 2019-04-13 13:20
https://github.com/Atlantiss/NetherwingBugtracker/issues/5627

**Comment by samzispheq** [comment] 2019-06-07 14:02
True this target dummy and advanced target dummies should be lootable. They should have a chance of droping fused wiring

**Comment by czarecoo** [comment] 2019-06-16 14:40
please fix

**Comment by Manaci** [comment] 2020-01-04 17:58
Duplicate of #2882

**Closed by Manaci** 2020-01-04 17:58 UTC
Labels: - Core Mechanic, Loot, Professions
