### ISSUE TITLE
[NPC] Bonechewer Scavenger odd tethering

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2038] opened 2018-10-31 09:14 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC Entry: 18952

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/PeppyEsteemedCobblerWTRuck)

I'm not sure what caused this. the mob appears to head back to its spawn, yet still remains in combat with me.

**Expected behaviour**: 
N/A

**Server Revision**: 
2243

**Comment by towneh** [comment] 2018-10-31 09:46
Confirming this behaviour happens with every single pull as a caster on Bonechewer Scavengers. They would aggro after I land a spell cast, and then as they reach me, will turn back towards their spawn location whilst still in combat. Once they reach the spawn location they then run back to me and continue with their melee attacks. This only happens once per combat with each NPC.

**Comment by Easyfraggy** [comment] 2018-10-31 23:02
Can't recreate per 2244

**Comment by KevinTyrrell** [comment] 2018-11-08 10:01
[Twitch Clip](https://clips.twitch.tv/BraveAmorphousScallionOhMyDog)

Just experienced this again. I believe it has something to do with their scripting for Throw. They seem to randomly decide to walk away and begin throwing.

**Comment by towneh** [comment] 2018-12-05 22:32
Still happening on latest server version 2395

https://www.youtube.com/watch?v=_NF_424N4II

**Comment by nullfoxh** [comment] 2018-12-05 22:38
Looking at towneh's clip the Orc that was mid animation ran back and the one that had no animation prior to aggroing didn't run back. So maybe it's related to whatever state the mobs are in.

**Comment by towneh** [comment] 2018-12-05 22:44
Seems like this is reproducible every time you pull a bonechewer that is mid-way through their animation:

![image](https://user-images.githubusercontent.com/25694892/49548984-53ac5b00-f8df-11e8-9acc-8fb975765dba.png)

**Comment by Evolvee** [comment] 2018-12-30 13:06
@Wolffenstein 
![image](https://user-images.githubusercontent.com/1942409/50547555-161bc300-0c3c-11e9-9523-5059fec089c1.png)

this action probably doesnt work

**Comment by The14me** [comment] 2020-07-07 05:02
rev .3451 cant reproduce anymore.

**Comment by Wolffenstein** [comment] 2020-07-08 00:09
Fixed in rev 3459.

**Closed by Wolffenstein** 2020-07-08 00:09 UTC
Labels: - Core Mechanic, Misc, NPC, Status: Confirmed
