### ISSUE TITLE
[Druid] [Bear] Threat Issues

### ISSUE THREAD

**Issue by mace3** [Atlantiss/NetherwingBugtracker#5250] opened 2019-02-28 03:38 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Seems that bear tanks have an issue with threat when tanking. I have experienced this the whole time on this server. Lacerate, Mangle, and other skills seem to not pull that much threat as they do on other tbc servers and when retail was out. There are many other druids experiencing this same issue. 

**Current behaviour**:
Low Threat

**Expected behaviour**: 
Higher Threat

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 2851 [Branch: master, Hash: de901f76879a]

**Comment by ircfelix** [comment] 2019-02-28 07:12
Maybe your bear tank is retarded?
We run a bear in 25m and his threat is super gold.

**Comment by Wolffenstein** [comment] 2019-02-28 13:05
Nobody from the top guilds complained about their druid tanks threat nor has this report provided me with any research or calculations, therefore I am closing this issue.

**Comment by ircfelix** [comment] 2019-06-06 15:41
Requesting reopen.

In bear form, druids should do 130% threat (100 damage he does is = 130 threat for him) from the bear form itself and with the talent Feral instinct he should do an additional 15% aggro. According to threat meters the values should stack additively (so druids should do 145% threat).

Now a druid friend and I did some testing and I pulled aggro at 11,3k of his 15,2k, our healer pulled aggro at 986 of the bear's 1400 threat (all threat was auto attacks only).

Our reasonable suspicion is that the talent and the bear form bonus don't buff threat caused by bears by 45%, but they reduce it by 45%, which means bears do only 55% aggro instead of 145%.
If you crunch the numbers now, it perfectly fits:
11,3/(15,2*0,55) = 1,35 (which means I overaggroed a bit over 130% and mb there is also some range of error in threat meters)
986 / (1400*0,55) = 1,28
So the healer and me both pulled aggro around the 130% aggro mark for the case that the talent does decrease aggro in bear form by 45% instead of increasing it by 45%

**Comment by jauho-1** [comment] 2019-06-06 16:09
Requesting reopen.

Did some testing on blasted lands elites (50k hp) with bear tank (me), healer and arcane mage.

We had both Omen and DTM active. According to both addons, range pulled the mob off me between 70-75% of bear threat as shown on the meters. The mage pulled aggro at 11,3k threat vs my 15,2k, and the healer pulled threat at 986 vs my 1,4k. 130% threat threshold would be expected at range. Based on these numbers, it seems Bear is doing only ~55% of the supposed threat.

The Omen and DTM threat values themselves seem correct. Dealing autoattack damage as bear yields exactly 145% threat (30% bonus from bear form, 15% bonus from feral instincts talent).

**Comment by Wolffenstein** [comment] 2019-06-06 21:18
Feral Instinct was not working at all. Fixed in rev 2989.

**Closed by Wolffenstein** 2019-06-06 21:18 UTC
