### ISSUE TITLE
[Thousand Needles][Quest] A dip in the Moonwell

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#626] opened 2018-09-26 03:20 UTC
**Unable  to use "Gather Water" as it seems to require a target**: 

**Requires a target**:

**Shouldnt need a target, rather a trigger zone IE the moonwell**: 

![wowscrnshot_092618_051731](https://user-images.githubusercontent.com/18479169/46055299-ad5c1080-c14b-11e8-9e30-7be2bc29190b.jpg)

**Comment by asatorrr** [comment] 2018-09-26 23:53
I was able to do this quest just fine earlier today. I got an etched vial from the dryads, went to the moon well south of the road on the western shore of the river and right clicked the vial from my inventory while standing on the eastern side of the well and collected with no issues. 

Are you sure you went to the right moon well? I ran south on the edge of the river and saw it to the west, dropped down and completed the objective.

**Comment by xmesaj2** [comment] 2018-09-28 19:34
![dip](https://user-images.githubusercontent.com/550384/46229337-9abd2380-c365-11e8-9043-78394329323d.png)
cannot reproduce, also tried with auto self cast disabled, need more details

**Comment by totaemoeggerli** [comment] 2018-09-29 13:35
[reopen issue still exists](https://gfycat.com/GrotesqueQuerulousCats)
https://www.wowhead.com/quest=9433/a-dip-in-the-moonwell
**Server Revision:** 2083

**Comment by Easyfraggy** [comment] 2018-09-29 15:51
Give more detail, what race/faction are you? What level etc.

**Comment by xmesaj2** [comment] 2018-09-29 15:52
@Easyfraggy I know already what causes it and got a fix

**Comment by xmesaj2** [comment] 2018-09-29 19:44
fixed in 2084

**Closed by xmesaj2** 2018-09-29 19:44 UTC
Labels: Item, Quest
