### ISSUE TITLE
[npc] servant of grol/Allistarj/Razelikh/Sevine chasing issue (blasted lands)

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#7066] opened 2020-06-24 10:02 UTC
**Description**: 
tested on ptr 3403 with servant of grol and razelikh (so i belive it's multiple issue).
Those mobs are chasing you for a good 2 minutes before they leash (even if you don't deal any damage to them).
https://tbcdb.com/?npc=7668
https://tbcdb.com/?npc=7669
https://tbcdb.com/?npc=7670
https://tbcdb.com/?npc=7671

for example - I was able to pull servant of grol up to follow sanctuary (nort-east swamps of sorrow) without dealing a single damage.

**Expected behaviour**: 
I'm 50% sure this should not work like this.
There are some comments (https://classic.wowhead.com/npc=7668/servant-of-razelikh#comments) that ppl back in vanilla pulled those guys to stormwind but I'm sure they did it by dealing damage (just like kazzak for example).

![WoWScrnShot_062420_114314](https://user-images.githubusercontent.com/43931626/85534885-005d4300-b612-11ea-9c89-bd63cd61bffa.jpg)
![WoWScrnShot_062420_114334](https://user-images.githubusercontent.com/43931626/85534920-06ebba80-b612-11ea-972e-1af1eef09a4b.jpg)
![WoWScrnShot_062420_114821](https://user-images.githubusercontent.com/43931626/85534972-13701300-b612-11ea-87bf-2580377eb492.jpg)
![WoWScrnShot_062420_114912](https://user-images.githubusercontent.com/43931626/85535015-1b2fb780-b612-11ea-9381-3c085e37a71b.jpg)
![WoWScrnShot_062420_114954](https://user-images.githubusercontent.com/43931626/85535053-22ef5c00-b612-11ea-984c-36fedc30df34.jpg)
![WoWScrnShot_062420_114957](https://user-images.githubusercontent.com/43931626/85535080-28e53d00-b612-11ea-9633-276a20e1e74e.jpg)
![WoWScrnShot_062420_114806](https://user-images.githubusercontent.com/43931626/85534949-0d7a3200-b612-11ea-8705-f77e9027455f.jpg)

**Comment by Evolvee** [comment] 2020-06-24 14:35
the problem is that threatDistance (which was set to prevent ppl from leashing it to cities) disables chasing refreshing mechanic entirely and allows it to chase until the X radius set in that column

**Comment by Wolffenstein** [comment] 2020-12-21 22:56
Fixed in rev 3577.

**Closed by Wolffenstein** 2020-12-21 22:56 UTC
Labels: - Core Mechanic
