### ISSUE TITLE
Challenging Shout

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4915] opened 2019-02-08 13:54 UTC
If people pass you in aggro after the debuff is applied, the mob targets them. It should work like mocking blow where they're forced to focus you 
Source: ability tooltip

edit: can't reproduce but definitely had it happen once where mob was targetting other player with the debuff applied

**Comment by WarriorTSW** [comment] 2019-02-10 21:51
ive seen this issue with taunt. i think also mocking blow

**Comment by Godmatik** [comment] 2024-07-03 04:27
Unable to reproduce, tested multiple different ways on PTR, the target always stuck on the warrior as long as challenging shout was active. Tried mocking blow too, 

Also never once heard anyone say this has happened to them during the past year that Netherwing has been running.

Closing for now.

**Closed by Godmatik** 2024-07-03 04:27 UTC
Labels: Class: Warrior, Spell, Status: Need Research, - Outdated: Need retest/research
