### ISSUE TITLE
Karazhan Server - Mind Flay (and possibly other channels) being randomly cancelled

### ISSUE THREAD

**Issue by Caskayde** [Atlantiss/NetherwingBugtracker#7630] opened 2020-10-12 18:03 UTC
I'm mostly going to be harping on about the movement speed debuff findings I found out because it's the only new information I can bring to this issue. The same or a very similar issue has already been brought up for the Netherwing server in this thread:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6478
I wasn't sure which was the bigger sin in this situation, necroing this thread or creating another thread about the same issue, but seeing as how this is happening on the Karazhan server I thought I would create this for the Karazhan server and bring attention to the previous thread.

I have noticed an issue where sometimes my mind flay will be cancelled as if it was interrupted, even against mobs that clearly did not interrupt my casting (It will break when caster mobs are in the middle of casting a spell). I check the combat log and there is no mention of a resist or and interrupt yet it still cancels the channel. I have also noticed that when my mind flay breaks it will continue to not work on repeated casts. 

When I repeatedly cast Mind Flay after the issue starts, it applies the first tick of damage, applies the movement speed slow debuff to the enemy, and then immediately cancels the channel. I have also noticed that if I let the movement speed slow debuff fall off the mob Mind Flay will continue working as expected.  If I repeatedly cast Mind Flay and re-apply the slow debuff that was applied when Mind Flay first broke it will continue the behavior until I allow the slow debuff to fall off, even if the normal amount of time for the first application of the debuff to fall off has already passed. If I allow the movement speed debuff to fall off after Mind Flay breaks I can continue casting Mind Flay on the same mob.

It is also worth noting that I am using a lot of addons including elvui and quartz and have not tested to see if the issue still arises without any addons enabled, as it is so infrequent and random I would probably have to play all day to be even kind of sure the issue was or was not caused by addons , but I am lazy and picky about my UI.

2.0.3|Revision: 3536

**Comment by Caskayde** [comment] 2020-10-13 23:44
I may have more information. This issue seems to be fairly repeatable by casting Mind Flay right before my current channel of Mind Flay ends. I have been letting my Mind Flay channels fully complete before casting it again and it hasn't happened for like 20 levels, but I can fairly reliable cause the issue to happen by trying to clip the last tick of my Mind Flay channel with another Mind Flay.

**Comment by v4nd** [comment] 2020-10-14 09:09
This has been reported many times before and despite being marked as fixed this bug is still valid and affects multiple channelled spells  (I can vouch for warlocks drain life and health tunnel)

Some references I was able to gather:

https://github.com/Atlantiss/NetherwingBugtracker/issues/6478
https://github.com/Atlantiss/NetherwingBugtracker/issues/7252
https://github.com/Atlantiss/NetherwingBugtracker/issues/4018

I dont have a 100% method to reproduce but I noticed this usually happens when you cast a new channelled spells right after finishing existing one. So start spamming channelled spells one after another and eventually you will hit this bug.

**Comment by Caskayde** [comment] 2020-10-14 11:58
> 
> 
> This has been reported many times before and despite being marked as fixed this bug is still valid and affects multiple channelled spells (I can vouch for warlocks drain life and health tunnel)
> 
> Some references I was able to gather:
> 
> #6478
> #7252
> #4018
> 
> I dont have a 100% method to reproduce but I noticed this usually happens when you cast a new channelled spells right after finishing existing one. So start spamming channelled spells one after another and eventually you will hit this bug.

I have also noticed that this bug is actually rather reproducible, which makes it relatively easy to avoid if I am just careful with my recasting of the ability. Essentially if you use that macro or just time your subsequent casts perfectly you should be able to avoid the bug without losing out on dps. 

Being fairly confident I can avoid this bug my tightening my play means it's not so bad imo, but it is still quite annoying to have this extra landmine waiting there to punish me hard for mistiming my casts. It's bad enough I clip the last tick of damage, but then to also lose the ability to cast mind flay for 3 more seconds? Brutal. It also means every time my mind flay gets resisted I pretty much have a window of time as long as the GCD to realize if it was an actual resist or the bug, because that makes a huge difference as to what my next cast should be.

**Comment by v4nd** [comment] 2020-10-15 09:27
Which macro are you using ?  `/cast [nochanneling:Mind Flay] Mind Flay` ?

**Comment by Caskayde** [comment] 2020-10-15 10:55
That's the macro I was talking about, but I don't actually use it myself.

**Comment by Drevil-Dion** [comment] 2021-04-09 16:23
> > This has been reported many times before and despite being marked as fixed this bug is still valid and affects multiple channelled spells (I can vouch for warlocks drain life and health tunnel)
> > Some references I was able to gather:
> > #6478
> > #7252
> > #4018
> > I dont have a 100% method to reproduce but I noticed this usually happens when you cast a new channelled spells right after finishing existing one. So start spamming channelled spells one after another and eventually you will hit this bug.
> 
> I have also noticed that this bug is actually rather reproducible, which makes it relatively easy to avoid if I am just careful with my recasting of the ability. Essentially if you use that macro or just time your subsequent casts perfectly you should be able to avoid the bug without losing out on dps.
> 
> Being fairly confident I can avoid this bug my tightening my play means it's not so bad imo, but it is still quite annoying to have this extra landmine waiting there to punish me hard for mistiming my casts. It's bad enough I clip the last tick of damage, but then to also lose the ability to cast mind flay for 3 more seconds? Brutal. It also means every time my mind flay gets resisted I pretty much have a window of time as long as the GCD to realize if it was an actual resist or the bug, because that makes a huge difference as to what my next cast should be.

Just because you are able to avoid it not all players can this is a major bug for some classes yet still remains not fixed despite multipul reports saying it was fixed this needs fixing asap

**Comment by Godmatik** [comment] 2024-07-01 19:37
Fixed some months ago - closing

**Closed by Godmatik** 2024-07-01 19:37 UTC
