### ISSUE TITLE
Weapon Skill ups only happen on weapon hit.

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7225] opened 2020-07-26 13:02 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

When training a new weapon skill, the skill will only train upon hitting the mob. It should be skilling up on weapon miss/dodge etc

**Current behaviour**:

As description

**Expected behaviour**: 

Weapon training skill up on miss/dodge/parries

**Server Revision**: 

Kara server 26/7/2020

**Comment by Tereneckla** [comment] 2020-07-26 14:19
Duplicate of #3999

**Closed by Tereneckla** 2020-07-26 14:19 UTC
