### ISSUE TITLE
[Hunter] [Pet Scorpid] Scorpid Poison is not scaling properly.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5398] opened 2019-03-16 19:24 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Scorpid Poison is intended to gain a certain amount of bonus spelldamage based on the hunter RAP.  Changelog 2856 was mentioned to fix this.  It changed something, but it's still not working correctly.

**Current behaviour**: Currently, no amount of gear, or lack therof, has any effect.  Scorpid Poison is locked to 60 damage per ten seconds per stack no matter what.

**Expected behaviour**: Scorpid Poison's damage should be calculated as SP_Damage = SP_Base + ( RAP * 0.125 * 0.14286).  RAP*0.125 is the coefficient in which pets gain Spell Bonus.  0.14286 is the coefficient that scorpid poison gets from that Spell Bonus.  My hunter has 1720 AP, my scorpid should be doing 55+30.71 damage per stack over ten seconds.  Stacking up to five times.   Right now, it ticks for 12, whereas it should be 17.1.  

Further, happiness is not increasing Scorpid Poison's damage either.  So depending on happiness, it should be modifying damage by .75/0/1.25. My "happy" Scorpid should be doing 21.375 damage per tick, per up to five stacks.  Ticking five times.

https://www.engadget.com/2007/08/08/bigredkitty-the-whole-scorpid-thing/
The Coefficient was nerfed in 2.2 from 0.4286 to 0.14286.  

**Server Revision**: 2891

**Comment by NatsumeLily** [comment] 2020-02-11 03:21
Bump.

**Comment by Zarant** [comment] 2020-07-10 23:20
Duplicate of #5241

**Closed** 2020-07-11 06:20 UTC
