### ISSUE TITLE
Diminishing rerurn bug

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#6608] opened 2020-02-02 12:31 UTC
Some time Diminishing rerurns bugging and you can get full time CC after previous CC.
https://www.twitch.tv/ur0b0r0s/clip/SassySuccessfulGoshawkJKanStyle?filter=clips&range=30d&sort=time
server revision **3247**

**Comment by Tereneckla** [comment] 2020-02-02 12:59
Duplicate of #6607

**Closed by Tereneckla** 2020-02-02 12:59 UTC
