### ISSUE TITLE
[NPC][Teron Gorefiend] Shadow of Death bug

### ISSUE THREAD

**Issue by Refuge001** [Atlantiss/NetherwingBugtracker#6991] opened 2020-05-22 02:06 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When Shadow of Death ends on a player it sometimes fails to allow a player to control ghost - the ghost is completely inactive but Shadow Constructs still spawn. It was reported earlier this week but wasn't very clear.

**Current behaviour**: We've had it occur across multiple classes, more reliably on priests - Shadow of Death ending fails to allow player to fully control a ghost. Ghost will spawn but is inactive and incapable of being in control.

**Expected behaviour**: When Shadow of Death ends, player dies and a ghost spawns that allows them to control it to kill the corresponding Shadow Constructs

**Server Revision**: 3375

**Comment by veekk** [comment] 2020-05-24 15:24
#6759

**Comment by Tereneckla** [comment] 2020-05-24 18:16
Well, this one actually is readable.

**Comment by Tereneckla** [comment] 2020-06-18 12:24
Duplicate of #6162

**Closed by Tereneckla** 2020-06-18 12:24 UTC
