### ISSUE TITLE
Mobs walking like a jesus

### ISSUE THREAD

**Issue by tbc123** [Atlantiss/NetherwingBugtracker#8349] opened 2023-04-16 11:36 UTC
![image](https://user-images.githubusercontent.com/46471537/232307180-2beb0762-3f8f-455a-87c7-a59aebbc64f1.png)
i think AI mobs work incorrect

**Comment by Godmatik** [comment] 2024-07-02 04:51
It's specifically has to do with SM Cath

Duplicate of #7097

**Closed as completed by Godmatik** 2024-07-02 04:51 UTC
Labels: Duplicate
