### ISSUE TITLE
Dire Maul East

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1227] opened 2018-10-05 00:14 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The instance has a lot of bugs. There are almost no packs spawned on the top floor, except for some patrols. The door for the last boss is opened to begin with and you can't talk to the Old Ironbark for the RP event where he opens it, and there are packs and patrols missing on the lower floor. Pusillin (Entry 14354) was aggressive from the very beginning, and was moving in the direction he runs to, but slowly.
**Current behaviour**:
![screenshot_533](https://user-images.githubusercontent.com/40346279/46509611-39d89400-c81a-11e8-8f70-052315010edb.png)
![screenshot_534](https://user-images.githubusercontent.com/40346279/46509612-39d89400-c81a-11e8-8923-0c938a727148.png)
![screenshot_535](https://user-images.githubusercontent.com/40346279/46509614-39d89400-c81a-11e8-975f-db0807bef999.png)
**Expected behaviour**: 
There should be packs spawned on the top floor, more packs and patrols on the lower floor. The door to the last boss shouldnt be open from the beginning, should need to talk to the old ironbark for it to be opened. Pusillin should have an event for it to be targetable, all the running after him thing.
**Server Revision**: 2126

**Comment by Xaero252** [comment] 2019-02-03 23:55
For more information:
There should be 4 packs of 7 non-elite lashers on the lower floor, the packs should be stationary. There should be two packs of 3 elite treants that pat the room in a semi-overlapping Z pattern.
The elite lashers are also stationary.

**Comment by KevinTyrrell** [comment] 2019-04-21 03:41
This instance really should be looked at as it is not at the quality level of the rest of the game's content. Still a mess as of revision 2944.

**Comment by polygxn** [comment] 2020-07-18 20:50
A group of people just reported that they escorted Pusillin just fine, but when they arrived at the last checkpoint he spawned his guards, then dissapeared. They had to go back to the start of the dungeon where Pusillin originally located, but this time he was hostile for the group. They killed him just fine, but this obviously should've not happened. I can't reproduce it on PTR, but when a ticket was made I saw them killing him at the start.

Also, at the end of the dungeon Isalien (ID: 16097) should be summoned by an item called Brazier of Invocation (ID: 22057), but she is there by default. Rev: 3482

**Comment by Godmatik** [comment] 2024-07-15 17:59
Closing - consolidating all information into one thread

**Closed by Godmatik** 2024-07-15 17:59 UTC
Labels: Movement, Dungeon, NPC
