### ISSUE TITLE
Spell tooltip shows ready , even if its on CD

### ISSUE THREAD

**Issue by FIXTHISFASTERRR** [Atlantiss/NetherwingBugtracker#5350] opened 2019-03-10 13:21 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Sometimes Using spells like Nature's Swiftness or other of that kind, the spell goes off but the tooltip shows it ready, so you have no idea when next time it will be ready or not, since it already shows it ready after u casted it
**Expected behaviour**: 
All tooltips of spells should be on CD once u cast the spell and not remain ready
**Server Revision**:

**Comment by Tenoutoften** [comment] 2019-03-10 19:44
Have to figure out the cause or the report is close to useless

**Comment by mbzz88** [comment] 2019-03-11 05:41
Guessing it is the same issue as https://github.com/Atlantiss/NetherwingBugtracker/issues/3652

**Comment by Zoups** [comment] 2019-03-13 14:14
I have the same issue when using NS healing touch macro, Both macro tooltip and NS icon in the spellbook do not go in cd

**Comment by Wolffenstein** [comment] 2019-03-31 04:07
Should be fixed

**Closed by Wolffenstein** 2019-03-31 04:07 UTC
