### ISSUE TITLE
Tome of Valor part 2

### ISSUE THREAD

**Issue by Magibum** [Atlantiss/NetherwingBugtracker#7227] opened 2020-07-26 14:15 UTC
https://classic.wowhead.com/npc=6182/daphne-stilwell#comments

[Quest][Westfall] The Tome of Valor
[NPC] Daphne Stilwell

**Description**: 
Bugged Paladin Quest
**Current behaviour**:
The Npc just despawns 1 second after spawning
**Expected behaviour**: 
The Npc shouldnt despawn instantly and let me do my Quest

**Comment by Tereneckla** [comment] 2020-07-26 14:16
Duplicate of #707

**Closed by Tereneckla** 2020-07-26 14:16 UTC
