### ISSUE TITLE
[Quest] Digging Through the Bones is not able to be completed and the chain isn't scripted.

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7067] opened 2020-06-24 20:14 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

When you start the quest from Chief Archaeologist Letoll, the NPC's do not acompany him through the quest. He leaves the camp by himself to the first dig site. Where he will dig at the ground and spawn an invisible worm. After killing the invisible worm, the texture of the worm will appear and Chief Archaeologist Letoll will despawn.

**Current behaviour**:

Listed above

**Expected behaviour**: 

This is the expected behaviour:

https://www.youtube.com/watch?v=MQ3LbkaokT4

**Server Revision**: 

24/6/20

**Comment by Tereneckla** [comment] 2020-06-24 21:02
Duplicate of #2240

**Closed by Tereneckla** 2020-06-24 21:02 UTC
