### ISSUE TITLE
[Spell][Paladin][Consecration] in Neutral Zones

### ISSUE THREAD

**Issue by Hazcher** [Atlantiss/NetherwingBugtracker#7940] opened 2021-03-04 14:17 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Spell][Paladin][Consecration] in Neutral Zones

**Current behaviour**:
In a neutral zone, such as Gadgetzan, Area 52 or Ratchet, when a player engages in Player vs Player-combat, guards should appear to defend and prevent the PvP from happening. As of now, Consecration doesn't seem to trigger this "Defensive engage" until the player dies. So Consecration could just tick away on hp. 

**Expected behaviour**: 
Player dealing damage to another player should trigger Defensive Systems within Neutral Zones

**Server Revision**:

**Comment by Tereneckla** [comment] 2021-03-04 21:35
Duplicate of #6854

**Closed as completed by Tereneckla** 2021-03-04 21:35 UTC
