### ISSUE TITLE
[Dungeon] Botanica [NPC] Frayer Wildling

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2563] opened 2018-11-10 18:58 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pathing issues.
**Current behaviour**:
We pulled the left Wildlings on the left side, only 2/4 of them came, while the rest were evading.
**Expected behaviour**: 
Completely opposite of that should happen. All should assist in the fight and not evadebug.
**Server Revision**: 
2282

**Comment by Evolvee** [comment] 2018-11-12 17:55
@Wolffenstein the issue is when they pull it from the bridge
mmap debug:
![image](https://user-images.githubusercontent.com/1942409/48365913-8c745e00-e6ac-11e8-8aa7-15964dcd9fa3.png)

If u pull it from the ground and then walk on the bridge they follow just fine.

**Comment by The14me** [comment] 2020-07-07 14:31
Rev.3451 still an issue. Some come... others stay.
https://streamable.com/rdx84p

**Comment by Godmatik** [comment] 2024-07-28 22:00
Rev 4016 - no longer an issue.
Pulled from the bridge and no evading occurred.
Likely resolved with pathing fixes done last year.

**Closed by Godmatik** 2024-07-28 21:59 UTC
Labels: Dungeon, NPC, Status: Confirmed, - Core Mechanic
