### ISSUE TITLE
[Quest] Bitter Rivals - unable to complete

### ISSUE THREAD

**Issue by WhyAreLess** [Atlantiss/NetherwingBugtracker#4355] opened 2019-01-19 14:40 UTC
**Description**: 
Having issues with the quest, Bitter Rivals (https://www.wowhead.com/quest=310/bitter-rivals), and I've given him like 2-3 Thunder Ale now without being able to replace the barrel. 
This quest has worked in earlier patches.

**Current behaviour**:
After you speak with the dwarf and give him Thunder Ale, the old barrel despawns but doesn't spawn the new barrel that you can replace.

**Expected behaviour**: 
Barrel should be replaceable to finish the quest.

**Server Revision**: 
2647

**Comment by The14me** [comment] 2020-07-15 10:08
Rev.3483 still an issue,u cant turn the quest on the barrel and take the new one.

**Comment by Zarant** [comment] 2020-07-15 16:45
You have to right click the guarded barrel to be able to turn in the repeatable quest. This is working as intended.

The issue comes once you turn in the repeatable quest: The NPC moves away from the guarded barrel, the guarded barrel will despawn and the unguarded barrel will take forever to spawn. I can't reproduce this consistently, sometimes the unguarded barrel spawns but sometimes it doesn't.

**Comment by The14me** [comment] 2020-07-19 05:36
https://github.com/Atlantiss/NetherwingBugtracker/issues/5569

**Comment by DoctorRaymos** [comment] 2020-07-28 03:53
Just updating this after speaking with Smaily,

the barrel seems to despawn slower than it should be, probably shouldn't be despawning at all. 

Current behavior: https://streamable.com/breqlj despawns almost immediately


Expected behavior: https://www.youtube.com/watch?v=EElKpo1mu6U (you can see the barrel does not despawn at all at the end of video)

the youtube link is a video from classic, but I am sure it is the same for original vanilla, doesn't make sense that the barrel is despawning

**Comment by Wolffenstein** [comment] 2020-07-28 22:19
Fixed in revision 3490.

**Closed by Wolffenstein** 2020-07-28 22:19 UTC
Labels: Hotfix Issue - Priority, NPC, Quest
