### ISSUE TITLE
[Quest][Item] Arena charter now a grey item after being partially signed

### ISSUE THREAD

**Issue by zitzen** [Atlantiss/NetherwingBugtracker#5498] opened 2019-03-28 21:57 UTC
**Description**: 
I purchased an arena 3v3 charter and got one signature and did not complete it. When I logged in a few days later the charter is now a grey item which cannot be used.
![WoWScrnShot_032819_153115](https://user-images.githubusercontent.com/49044716/55195394-0bf15e00-5172-11e9-83c2-4804ac3a3c25.jpg)

**Current behaviour**:
3v3 arena charter has turned into a useless grey item
**Expected behaviour**: 
3v3 arena charter can be clicked on to gather signatures and turn into an Arena Organizer once complete
**Server Revision**: 
2909

**Comment by Evolvee** [comment] 2019-03-28 22:29
if you want to refund the money you spent on this, contact me on discord when you get online ^^

**Comment by Godmatik** [comment] 2024-07-07 04:24
Have not heard of this ever happening in past year on Netherwing.

Going to try and reproduce on PTR, I created a 3v3 charter and took only one signature, will check back in a few days.

**Comment by Godmatik** [comment] 2024-07-08 03:32
Can't reproduce.
Also did a server restart and a server crash - arena charter never turned gray.

Closing.

**Closed by Godmatik** 2024-07-08 03:32 UTC
Labels: Status: Need Research, - Core Mechanic, Item
