### ISSUE TITLE
[Raid][NPC][Lady Vash'j] Persuasion

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3415] opened 2018-12-13 22:01 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
MC'd target are CC'able. https://clips.twitch.tv/SweetTangibleClamBleedPurple

Was debating whether the MC AI is too dumb, casters and healers melee much more than cast spells and heals. (needs research)
https://clips.twitch.tv/MildRelatedClamJonCarnage Notice the paladin doesn't cast a single spell. Teleports at the end?

https://clips.twitch.tv/ScaryBraveSharkNomNom (on the left) MC'd player kills another player in the MC ends, leaving only 1 MC target up. Should be 2 targets at all times?
https://clips.twitch.tv/GeniusAthleticBulgogiVoHiYo MC ends prematurely again for the warrior, looks like someone died.

https://clips.twitch.tv/AmazonianBlightedHerbsNomNom Target gets MC with toxic pool on him, damage gets evaded according to his health bar, then he and the other MC target dies instantly when the MC ends prematurely. Tank gets teleported to platform after.

**Server Revision**: 
2431

**Comment by aresbrutus** [comment] 2018-12-13 22:05
From the data we have gathered regarding MC'd targets, other servers make them too strong and/or make them use random spells that on retail MC'd targets never casted. We have gathered a list of confirmed behaviour + spells and have added it to the MC AI. However, there is always room for improvements + we might have missed some other spells/behaviours. 

So requesting people to do some research and put stuff here that happens on retail but does not on NW.

**Comment by Imbaslap** [comment] 2018-12-13 22:05
https://www.youtube.com/watch?v=SYypbzs9d44 Source video.
all players under Pursuasion are immune to any CC form including banish/cyclone/stuns/fears etc.
the players who can cast healing spells Should be targeting vashj and casting heal spells as much as possible to utilzie the +heal% buff from pursuasion, currently healer classes just melee random people.

the MCed players should be tauntable by warriors/bears and can be fixated by mocking blow/challenging roar/shout as shown in the method world first video.

https://imgur.com/a/p3SiqYz  screenshot of the warrior Taunting the MCed player in method video.

**Comment by Drayo** [comment] 2018-12-14 11:49
I think the last point of OP happens because she resets (all non-MC players died) and everyone who is still under MC just gets killed due to that.

**Comment by Wolffenstein** [comment] 2018-12-14 20:18
Fixed in rev 2434.

**Closed by Wolffenstein** 2018-12-14 20:18 UTC
Labels: Raid
