### ISSUE TITLE
[Quest] To Legion Hold

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2533] opened 2018-11-10 12:14 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Demon is spassing about. (Uncompletable quest on my end... I've heard people can complete it and it works, but for me no
**Current behaviour**:
As I disguise myself as a crate, the demon is spassing about, never making it to the communication device and after 1 minute as my crate "debuff" disappears, he despawns.
**Expected behaviour**: 
Should run/walk smoothly to the device, talking to his overlord and then at the end ask his overlord what is in that crate.
**Server Revision**: 
2279

**Comment by xmesaj2** [comment] 2018-11-10 12:41
cannot reproduce

**Comment by Mewmewww** [comment] 2018-11-10 12:43
If you are in game, I can try to do the same quest again. (Character, Drain)

**Comment by xmesaj2** [comment] 2018-11-10 12:45
can you record it?

**Comment by Mewmewww** [comment] 2018-11-10 12:50
I don't have a recording device, shadowplay doesnt work.

**Comment by xmesaj2** [comment] 2018-11-10 12:52
https://getsharex.com/
https://obsproject.com/

**Comment by Mewmewww** [comment] 2018-11-10 13:00
Recon(Scottie) will link 3 gifs about it momentarily

**Comment by ScottieDOESknow** [comment] 2018-11-10 13:01
Eredar shuffle 1
https://gyazo.com/3601afe7107c0601b77899684b20a858

Eredar shuffle 2
https://gyazo.com/dfc09ccaba5a248b1142fb04ae31284a

Eredar shuffle 3
https://gyazo.com/d733c52e2c6f4c9c895b2b94468d5ba9

**Comment by Wolffenstein** [comment] 2018-11-10 15:32
Fixed in rev 2281.

**Closed by Wolffenstein** 2018-11-10 15:32 UTC

**Comment by xmesaj2** [comment] 2018-11-10 15:41
fix in 2281
