### ISSUE TITLE
[Spell][Mage] Arcane Missiles

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#3045] opened 2018-11-25 21:48 UTC
**Description**: 
Arcane missiles stops channeling if facing backwards at the target. My guess is that atm the spell periodically checks for player's facing, which it shouldn't. The check with arcane missiles should only be done at the start of the cast. The spell should check for facing and LoS only when the player presses the button.

**Current behaviour**:
Arcane missiles stops channeling if facing backwards at the target

**Expected behaviour**: 
Arcane missiles should never check for facing after they have started casting and should continue channeling.

**Server Revision**: 
2361

**Comment by Easyfraggy** [comment] 2018-11-26 01:13
Please post some retail proof - im pretty sure you are right - but just for certainty.

**Comment by Saben65** [comment] 2018-11-26 08:21
I would check to see if AM is breaking on LOS from a pillar or such. If it is, I am guessing that would be a good indication that it is checking for LOS on each cast which would be incorrect. I tried finding some examples from old videos, but unfortunately AM isn't a highly used ability in PVP.

> Mages will no longer see line of sight errors if the target moves behind an obstacle after the spell "Arcane Missiles" has begun casting.
[Patch 2.0.3](http://wowwiki.wikia.com/wiki/Patch_2.0.3#toc)

The same also applies for other channeled spells like Mind Flay and drain life/mana. Might be worth checking those as well.

**Comment by Easyfraggy** [comment] 2018-11-26 08:32
Frontal spells and LOS are seperate checks. Lots of spells don't check frontal but do check LOS.

**Comment by somnu** [comment] 2018-11-26 11:41
Don't try to derail the issue, AM isn't breaking on LOS. The issue is that the channeling is currently breaking if you turn your character, or if the target goes behind you. So it's only breaking on facing.

**Comment by Easyfraggy** [comment] 2018-11-26 20:20
I asked you to provide some proof from retail that it should not cancel...

**Comment by knasen88** [comment] 2018-11-28 13:20
well the character is supposed to follow the target if right click camera is unused? Does it cancel if you don't let mess with the camera?

**Comment by somnu** [comment] 2018-11-28 13:30
@Easyfraggy I was telling Saben65 not to derail the thread.

I found some proof for drain life which is essentially the same thing, it might be definitive because of the editing going on in the video, but it's a starter. I'll try to find more:

https://youtu.be/IAoe3akMZUE?t=668

**Comment by killablink** [comment] 2018-11-28 16:06
Yeah the way arcane missiles cancel itself when someone goes behind you and your camera faces in front is definitely not correct, it should keep casting wherever you're facing. The videos also prove it

**Comment by Easyfraggy** [comment] 2018-11-28 21:45
Those videos don't prove your claim at all - there should be a leeway for reacting and turning your camera before it fails - I believe it is only periodic checks on facing - which would automaticly give you that leeway.

The videos actually show the players purposely changing their camera angles to follow the other player - the second video he isn't rightclick panning his facing it is simply the auto facing.

**Comment by killablink** [comment] 2018-11-29 03:10
Actually to me, it just seems he's obv purposely changing his camera to face the from because he's spamming drain life asap, you still need to be facing him when you want to start a new one. Look closely in slow motion and you'll the troll mage walks behind him at 11:11

![image](https://user-images.githubusercontent.com/43510874/49196700-edad5a00-f359-11e8-876a-b7b44210e2e0.png)

This is currently the interaction in NW: https://gfycat.com/ThisUntimelyGoat

I've played mage all my life and this interaction, stopping completely your spell feels REALLY off. Could probably find other drain life clips but yeah pretty sure it's not correct

**Comment by Easyfraggy** [comment] 2018-11-29 09:21
Theres a facing check on each missile/tick - like I said it's not a constant check - you can see that your AM isn't cancelled untill the next missile is supposed to fire. On the video you SS the guy behind the warlock draining life between 2 ticks aswell.

Need more evidence - you might be right that it shouldn't check facing on each tick/bolt - but the above videos are not sufficient.

**Comment by killablink** [comment] 2018-11-29 13:32
You see the drain life doing 260 dmg tick when he is behind the warlock

![image](https://user-images.githubusercontent.com/43510874/49225132-40663080-f3b1-11e8-876f-cb62629eefd9.png)

**Comment by killablink** [comment] 2018-11-29 14:40
https://youtu.be/dVu80XgRZB4?t=341
Other clip but from wotlk

**Comment by Easyfraggy** [comment] 2018-11-29 17:35
The wotlk video shows it much better than the original videos linked - so that is for drain spells - still need to see for arcane missiles - channeled missile spells behave differently than channeled drains.

By retail retail do you mean current retail aka BfA?

**Comment by killablink** [comment] 2018-11-29 17:52
Yeah I meant retail BFA

I know they behave slightly differently, drain life has a first "tick" and then channels completely, while missiles is a separate projectile. The thing is you can see that if you turn around before the first "tick" of drain life it just bugs and interrupts it, which is the same error that missiles have. The only differences is that there are multiple ticks for AM vs 1 for drain life. Finding clips for AM is pretty hard since no one was really using AM in tbc

**Comment by Easyfraggy** [comment] 2018-11-29 18:53
I'm not sure that what you are saying about turning around before first tick is actually a bug. It is surely a hard thing to find evidence for or against though!!! I don't know when the frontal check is made for drains - that's smth wolf would know more about - not me.

Anyway would be nice with some proof in regards to AM - for example drain spells have full duration reflected on spell reflect where as AM is checked on every projectile. So the to types of spells don't always go by the same logic.

**Comment by killablink** [comment] 2018-11-29 18:58
It makes completely 0 sense that you would get interrupted randomly after casting drain life and turning around quickly. Also played mage all my life and never had arcane missiles being interrupted because you were facing the wrong direction. I'd like proof on why it doesn't work as it's very likely a bug made in a private server. Anyways I've researched it enough not my problem anymore lol

**Comment by somnu** [comment] 2018-12-01 15:02
Adding some more proof. Although it's from vanilla, the fact that the channel isn't interrupting when the target goes behind the caster should be pretty much unchanged in TBC as well.

https://youtu.be/0ydX5IM6ek4?t=53

Watch for his mindflay cast and how the other guy gets behind him and it doesn't interrupt.

**Comment by somnu** [comment] 2018-12-01 15:06
> Anyway would be nice with some proof in regards to AM - for example drain spells have full duration reflected on spell reflect where as AM is checked on every projectile. So the two types of spells don't always go by the same logic.

I tried finding arcane missiles, but I had no luck. I'm pretty sure that in terms of casting mechanics all these channel spells are pretty much alike.

**Comment by killablink** [comment] 2018-12-03 12:30
https://youtu.be/lhl-GOLhSew?t=1235

AM going off when rogue is in the back

**Comment by Easyfraggy** [comment] 2018-12-04 00:11
I mean sometimes I don't know if we watch the same videos - the rogue isn't behind when that bolt is fired. Hes deadcenter on the mage. It's just the animation that fires after hes moved through.

**Comment by killablink** [comment] 2018-12-04 00:17
Dude, sorry but you just don't know what you're talking about
![image](https://user-images.githubusercontent.com/43510874/49409678-a21af780-f72f-11e8-8e25-7d9e98521ba5.png)

I don't know how many more proofs you need, specially me as a glad/r1 mage player to tell you that that interaction is normal. The bolt didnt come off before. Why didn't that glad mage also didn't move his camera to adjust himself if it breaks? Because it doesn't.

There is clearly a stupid facing check every tick goes off which IS A BUG. It's the reason why drain life is bugging right now if you move the camera away. Channeled spells only check facing and LoS on cast, not on ticks.

**Comment by killablink** [comment] 2018-12-04 05:07
Sorry but you're just proving how unknowledgeful you are.  Do you realize the cast bar is half way because he got attacked by the rogue, making it so that the mage loses his cast time on arcane missiles? holy it's fucking incredible did you even ever play mage or warlock?

This bug that's happening with drain life: https://gfycat.com/BasicElaborateJackal is the same reason why AM is bugging right now. There's a facing check after the spell goes off that SHOULDN'T exist. Do you honestly believe that Blizzard had some dumb shit interrupting a channeled spell .2 seconds after you managed to actually cast it? That's just plain stupid. Also the mage isn't dead at this instant as you can see the rogue stll walks and casts shiv a few moments after.

You literally have NO proof that how it is right now is correct and against all these evidences and people reporting and, people with experience knowing that this stupid interrupt never existed, can we have someone else take care of this report.

**Comment by Easyfraggy** [comment] 2018-12-05 22:02
Killablink xD

I already told you above that you are watching the rogues POV so he is further ahead than on server side - if we went by your logic melee should also be able to melee from their ass since thats what he does on the video due to delay.

Your "evidence" is too circumstantial. The video even shows that his AM is cancelled right after the bolt fires (as shown on your own screenshot above)

**Comment by killablink** [comment] 2018-12-06 03:07
It's ok, Wolf said that the bug with drain life interrupting is indeed a bug (there's a facing requirement check going off when the first "missile" is going off (drainlife) which is the same bug as AM. Thanks.

And yes, I played warrior and rogue to Gladiator to top 10 in BC/WOTLK too thanks.

**Comment by Easyfraggy** [comment] 2018-12-06 06:42
> Please post some retail proof - im pretty sure you are right - but just for certainty.

I haven't once said that you are wrong - just that your "evidence" doesn't show anything at all.

**Comment by killablink** [comment] 2018-12-06 07:02
Please provide me retail proof that this interrupt was how it was in retail derpderp. Don't have time to waste 2349 hours on something I know is bugged.

Let me explain to you one last time why this is bug.

Look again at the gfy with the drain life being interrupted. Here's how it's going on, drain life is casted, then the game is looking at facing requirement for the first "tick" (Missile, however you wanna call it) and gets interrupted because you turned too quickly. WOLF himself said it's a bug:

![image](https://user-images.githubusercontent.com/43510874/49567031-8a439f00-f8fa-11e8-82ce-bdd11b7c88a6.png)

Similarly, if we know that that drain life tick was a BUG, we can say that Arcane missiles is the same thing except that it has 5 "TICKS" (Missiles). It's interrupting itself because it's doing a facing check on the tick that shouldn't happen. It should only happen upon cast and then continue casting no matter what

![image](https://user-images.githubusercontent.com/43510874/49567091-be1ec480-f8fa-11e8-8830-c1d961e3afa8.png)

Doesn't mention interrupted if you turn around while casting.

If you add all the damn pieces in this stupid thread you'd realize that it's a bug.

**Comment by Easyfraggy** [comment] 2018-12-06 07:04
>I'm not sure that what you are saying about turning around before first tick is actually a bug. It is surely a hard thing to find evidence for or against though!!! I don't know when the frontal check is made for drains - that's smth wolf would know more about - not me.
>Anyway would be nice with some proof in regards to AM - for example drain spells have full duration reflected on spell reflect where as AM is checked on every projectile. So the two types of spells don't always go by the same logic.

Facing check =//= out of range/LOS check.

**Comment by killablink** [comment] 2018-12-06 07:06
?? Who mentioned out of range LOS check? They're both frontal check errors

**Comment by killablink** [comment] 2018-12-06 07:09
Provided you don't get interrupted, meaning that the only way your cast stops is by getting pummeled, silenced, not you facing away from your target. This is going no where

**Comment by Easyfraggy** [comment] 2018-12-06 07:10
You could get "interrupted somehow" by facing the wrong way. Still 0 proof of AM casting with back turned.

**Comment by killablink** [comment] 2018-12-06 07:18
Yeah it's pretty hard to understand people who don't know what they're talking about and don't know how to reason. "Provided you don't get interrupted somehow, like also pressing your jump key huehuheu" No obviously he's talking about being interrupted by an ability use your brain.

https://gfycat.com/UnlinedFearfulHagfish

No changes mentioned in the changelog for arcane missiles about frontal check
Drain life frontal check bug being the same bug with arcane missiles (THAT WOLF CONFIRMED)
Literally no information about arcane missiles being interrupted depending on where you face
This is private server, of course there will be bugs (Just like with drain life frontal check right after starting it wow!!!!!!!!)

Stick to melee classes.

**Comment by Easyfraggy** [comment] 2018-12-06 07:34
Well yeah - in common wording by jumping would definitely count as "interrupted somehow".

Links BfA video as proof... more useless "evidence". There's no changelog for tons of things like this.

And just to repeat myself for the 10th time - I have not once said you are wrong - your evidence just doesn't prove anything.

**Comment by killablink** [comment] 2018-12-06 16:24
![image](https://user-images.githubusercontent.com/43510874/49596945-78d5b380-f949-11e8-8224-68c6f6f0c693.png)

Posting here cause Evolve told me to

**Comment by killablink** [comment] 2018-12-08 03:49
https://gfycat.com/DigitalArcticFlicker
You can interrupt someone just by walking on him, obviously this stupid facing thing is bugged

**Comment by torrenzGH** [comment] 2018-12-18 21:31
Take a look at missiles rank 1, which has a shorter duration and only 3 max missiles. It seems to automatically interrupt at the end, without me or my target moving. In the last cast it actually stops channeling before the third missile fires.
https://www.youtube.com/watch?v=MtPUF00p6w0
No, I don't understand what this means. Hope it helps

**Comment by rikhx** [comment] 2018-12-27 15:18
Yo fix this shit already, plenty of evidence has been posted and this shit is a pretty big deal. You have always been able to continue your AM cast while facing your back to the target ever since from vanilla to retail even and you should always follow your target wether its going thru you or LoS. The only time it should ever get interrupted if target runs out of range or someone interrupts you.

**Comment by Easyfraggy** [comment] 2018-12-27 17:38
Like i've said before - if it was always possible why is there 0 evidence of this other than BfA footage?

For @torrenzGH you shoot 3 missiles on your video - no idea what you are even talking about?

**Comment by killablink** [comment] 2018-12-27 17:46
https://gfycat.com/DigitalArcticFlicker
Is evidence that AM is bugged. You shouldn't be able to walk through someone to interrupt his AM cast. Why aren't you able to read about this totally legit strat anywhere on the web? 🤔 

Glad we have Tester Easy on the case and can't read or watch people's reports correctly, the guy's video https://www.youtube.com/watch?v=MtPUF00p6w0, the last AM cast only casted 2 missiles. And even if you finish casting your 3 missiles correctly you get an interrupted message for no reason.

but it's ok, we have PVE Master Tester Easy on the case, who thinks there are no DR when pve mobs stun you 😆

**Comment by Easyfraggy** [comment] 2018-12-27 17:52
> https://gfycat.com/DigitalArcticFlicker
> Is evidence that AM is bugged. You shouldn't be able to walk through someone to interrupt his AM cast. Why aren't you able to read about this totally legit strat anywhere on the web? 🤔

You are locking your camera stopping the tracking on the video from NW... It might very well be bugged but it shouldn't be so hard for you to find a retail video if this was always the case. Still waiting for multiglad killablink to find some proof of his claim.

> Glad we have Tester Easy on the case and can't read or watch people's reports correctly, the guy's video https://www.youtube.com/watch?v=MtPUF00p6w0, the last AM cast only casted 2 missiles. And even if you finish casting your 3 missiles correctly you get an interrupted message for no reason.
> 
> but it's ok, we have PVE Master Tester Easy on the case, who thinks there are no DR when pve mobs stun you 😆

Ahah he recorded more than just 1 AM - fair enough - I see it now - that does indeed need to get fixed. Is it just random or do you know someway to replicate?

**Comment by killablink** [comment] 2018-12-27 17:54
You do realize that I didn't lock my camera? That's just me pressing arcane missiles and doing nothing. Even if the game auto lock the camera for you you still can't cast AM properly if something is moving around you.

**Comment by Easyfraggy** [comment] 2018-12-27 18:10
> You do realize that I didn't lock my camera? That's just me pressing arcane missiles and doing nothing. Even if the game auto lock the camera for you you still can't cast AM properly if something is moving around you.
> 
> You fail to properly using your brain though, and you're not even knowledgeful in PVE either (lol DRs)

Keep up with the personal insults - you still haven't provided a single retail video after what - 12 posts? I keep telling you that im not saying you are wrong - but you have to prove it.

**Comment by Wolffenstein** [comment] 2018-12-31 01:05
Fixed in rev 2543.

**Closed by Wolffenstein** 2018-12-31 01:05 UTC
Labels: Class: Mage, Spell, Status: Need Research
