### ISSUE TITLE
[Tauren] Aggro Radius seem significantly higher than other races

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3816] opened 2019-01-04 00:42 UTC
**Description**: 
I am unsure if this is blizz-like or not; however it seems extremely high.

**Current behaviour**:
Tauren have a very large aggro radius, much higher than other races. This means that while every other race can skip certain pulls, you can not do that with tauren in the group without use of invis pots or similar. Items that change your model (deviate delights for example) do not seem to affect the aggro radius (probably working as intended?).

Two pulls in particular to use as an example are the two seperate retainer pulls on the ground floor ball room in Karazhan. You cannot enter Moroes' room without a Tauren pulling the retainer group just outside of it. Additionally, you can not get past the 2nd group of retainers in the middle of that room if you take go left along the wall outside of Moroe's room. I do not recall this being the case when I ran Karazhan earlier on the server.

**Expected behaviour**: 
While Tauren's hit boxes are documented as being larger than others due to their size, I do not recall ever having to pull retainers in Karazhan with Tauren in the group. I believe the aggro radius should be slightly lower for Tauren to compensate for the large hitbox (assuming aggro range is defined by hit box).

**Server Revision**: 
2574

**Comment by Jseay1313** [comment] 2019-01-04 03:46
This is a common issue on most private servers, the agro radius issues generally also persist with moonkin/bear form as well I.e a tauren moonkin cannot walk to the back side and spread out in gruuls room without agroing him whereas every other class/race combo can.

**Comment by Tenoutoften** [comment] 2019-01-04 04:06
Would need evidence....

**Comment by Jseay1313** [comment] 2019-01-21 05:09
http://wowwiki.wikia.com/wiki/Aggro_radius

Agro radius in general is a little wonky on many mobs, and I noticed it more so as a tauren. Doing Gruul today most everyone had positioned themselves around the mob and a tauren doing the same thing agrod when slightly further away from another player. The entire thing should be checked to see if it matches this wiki.

**Comment by Jseay1313** [comment] 2019-01-30 21:13
https://www.youtube.com/watch?v=b7mL7QgUUxc&feature=youtu.be

awful please help

**Comment by Domceru** [comment] 2019-01-30 21:34
I mean, if it was a thing, you would think it would be better documented somewhere like their hitboxes are. Instead, references to aggro mechanics make it sound universal. It is pretty difficult to find evidence that something like this is incorrect, probably because it was never an issue to begin with. It makes absolutely no sense their aggro range would be higher, because that is a distinct disadvantage they would have over every single class. It just feels bad.

**Comment by Jseay1313** [comment] 2019-01-30 22:18
The problem is that the agro radius is currently attached to the hit box instead of the center of the tauren, this was said to me by evolve specifically

Evolve01/22/2019
maybe aggro radius should be calculated from center
instead of from hitbox
Evolve01/22/2019
he wont change it just because its pain in ass

**Comment by Wolffenstein** [comment] 2019-02-01 03:08
Fixed in rev 2742.

**Closed by Wolffenstein** 2019-02-01 03:08 UTC
Labels: Status: Need Research
