### ISSUE TITLE
[Spell][Paladin] Holy Shock does nothing when cast at max range

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#3766] opened 2019-01-01 15:17 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://gfycat.com/ThoroughPersonalAuk

**Current behaviour**:
Holy Shock sometimes does nothing when cast at max range. It can be reproduced almost 100% of the time. Higher reproduction rate if you move away from the target immediately after casting. Does nothing and then goes on CD.

**Expected behaviour**: 
It should have an effect if cast when in range.

**Server Revision**: 
2550

**Comment by killablink** [comment] 2019-01-01 16:32
What Brasso said

**Comment by Godmatik** [comment] 2024-07-05 03:17
I can't reproduce this at all, tried both against enemies and friendlies, always it goes off everytime even when cast at max range or moving away. Maybe it was fixed at some point.

Closing

**Closed by Godmatik** 2024-07-05 03:17 UTC
Labels: Spell, - Core Mechanic
