### ISSUE TITLE
Arena icon on minimap upon joining is not visible.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6519] opened 2019-12-29 23:14 UTC
Arena icon on minimap upon joining is not visible.
![image](https://user-images.githubusercontent.com/45521546/71564004-5d2fd480-2a99-11ea-9c2f-33bde55e912a.png)

**Comment by Evolvee** [comment] 2019-12-30 00:06
joining what

**Comment by veekk** [comment] 2019-12-30 12:30
can confirm, if ur mate que arena u can't see icon until arena pop

**Comment by AWIDIUS** [comment] 2020-01-01 15:50
Upon joining an arena battle. Either 2v2 or 3v3.

**Comment by Evolvee** [comment] 2020-03-28 13:26
confirmed, not sure yet if its due to the partner being on different map

**Comment by AWIDIUS** [comment] 2020-03-28 17:15
😂😂

**Comment by AWIDIUS** [comment] 2020-03-28 17:16
Faith in NW PvP is slowly restoring 🙄

**Comment by Wolffenstein** [comment] 2020-05-02 14:47
Fixed in rev 3350.

**Closed by Wolffenstein** 2020-05-02 14:47 UTC
Labels: - Core Mechanic, Misc, PvP: Battleground & Arenas, Status: Confirmed
