### ISSUE TITLE
Cyclonian quest

### ISSUE THREAD

**Issue by hitssss** [Atlantiss/NetherwingBugtracker#5456] opened 2019-03-23 14:48 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I had all the materials, quest said it was complete on the log. Could not complete it, abandoned it and lost all the materials please helppppp

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by danbopes** [comment] 2019-09-07 20:04
Dupe of #5719

**Closed by danbopes** 2019-09-07 20:04 UTC
