### ISSUE TITLE
[Quest] Conjurer Luminrath  [NPC] Conjurer Luminrath 

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7084] opened 2020-06-30 11:35 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

https://www.wowhead.com/quest=10306/conjurer-luminrath

**Current behaviour**:

Once you click the quest item by the wardrobe, the NPC spawns, but you are unable to attack them. They will also follow you forever.

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment] 2020-06-30 11:40
Duplicate of #7083

**Closed by Tereneckla** 2020-06-30 11:40 UTC
Labels: Duplicate
