### ISSUE TITLE
[NPC] Twilight Runner [Quest] [Loot]

### ISSUE THREAD

**Issue by Hoffa1337** [Atlantiss/NetherwingBugtracker#6749] opened 2020-03-13 12:09 UTC
**Description**: 
Creature 4067 Twilight Runner is missing item 5584 Twilight Whisker from it's loot table for quest 1058.

**Current behaviour**:
The quest item does not drop.

**Expected behaviour**: 
The quest item should drop.

**Server Revision**: 
3297

Links:
https://tbcdb.com/?item=5584
https://tbcdb.com/?npc=4067
https://tbcdb.com/?quest=1058

**Comment by The14me** [comment] 2020-03-13 12:13
[Twilight Runner](https://classic.wowhead.com/npc=4067/twilight-runner)
There is no loot at all, not just for the quest.
Tested on PTR too.

**Comment by Evolvee** [comment] 2020-03-19 16:01
![image](https://user-images.githubusercontent.com/1942409/77087325-46977a80-6a03-11ea-96ed-60c6844bee2c.png)

??

**Comment by Evolvee** [comment] 2020-03-31 17:57
closing this as I cant reproduce it, and you didnt comment so...

**Closed by Evolvee** 2020-03-31 17:57 UTC
Labels: Loot, NPC, Status: Confirmed
