### ISSUE TITLE
[Class][Hunter] Auto Shot bugged

### ISSUE THREAD

**Issue by redghost4** [Atlantiss/NetherwingBugtracker#5298] opened 2019-03-04 19:56 UTC
**Description**: Auto-shot gets stuck when you switch targets.

**Current behaviour**: the character starts the autoshot animation and keeps doing it on loop, but doesn't attack at all. /startattack macros don't fix it, and it only starts working again when you use an ability.

Happened to my GF on her night elf hunter (lvl 30) with a bow (Raptor's end), and with her draenei hunter (lvl 22) with WC bow.

It happens every single time, very easy to reproduce:
1. Start attacking 1 mob.
2. Right click another mob.

**Expected behaviour**: Hunter starts attacking normally after switching targets.

**Server Revision**: 2865

**Comment by gunzbngbng** [comment] 2019-03-05 01:51
Right clicking a totem and watching your character get stuck in an endless windup loop is painful.

**Comment by Wolffenstein** [comment] 2019-03-06 21:18
Can't reproduce on local, a video would be nice.

**Comment by wcraycroft** [comment] 2019-03-20 20:34
Steps to reproduce (almost 100% for me):
- Pull 2 mobs
- Autoshot mob A
- Without cancelling autoshot, dropping target, or moving, right click mob B.
- You will get anywhere from 2 to infinite loop of "Interrupted" messages and autoshot will not cast
- Retargetting, moving or casting another shot will sometimes fix the error/animation loop.

Here's a not so great video, best I could cap: 
https://i.gyazo.com/180f51b1a286f289fb35b02f147c99c0.mp4

When I first swap to the right target, I get 2 Interrupted messages but the autoshot still goes off on time.
When I swap back to the left target (and sadly the gif cuts off), I get stuck in an infinite loop of "Interrupted" messages. Autoshot doesn't go off until I take one of the actions above.

**Comment by Phil4242** [comment] 2019-04-28 17:19
would be nice if this could get fixed soon :)
its a major bug and afflictes the overall raid performance + quality of life

**Comment by Dragunovka** [comment] 2019-06-15 15:37
still bugged, its time to fix

**Comment by Dragunovka** [comment] 2019-06-25 18:23
please

**Comment by Dragunovka** [comment] 2019-06-25 18:27
#5509

@Wolffenstein

**Comment by Wolffenstein** [comment] 2019-07-02 01:21
Hopefully fixed in rev 3055. Please test on the PTR before it hits live.

**Closed by Wolffenstein** 2019-07-02 01:21 UTC
