### ISSUE TITLE
[Enginnering][NPC] Gnomish Flame Turret

### ISSUE THREAD

**Issue by Peachusftw** [Atlantiss/NetherwingBugtracker#8462] opened 2023-05-31 20:41 UTC
**Description**: 
[Item] Gnomish Flame Turret [https://www.wowhead.com/tbc/item=23841/gnomish-flame-turret] should spit fire around in an AoE until it's destroyed or it wears off.

**Current behaviour**:
The turret doesn't throw fires, instead hits in melee and follows the player around.

**Expected behaviour**: 
The turret should throw fires in the AoE and remain stationary as per [https://www.youtube.com/watch?v=Oq338xVbWJ4&ab_channel=SimonizeShow]

**Server Revision**: 
3787

**Comment by Godmatik** [comment] 2024-07-01 22:26
Duplicate of #3809

**Closed as completed by Godmatik** 2024-07-01 22:26 UTC
