### ISSUE TITLE
Quest not working

### ISSUE THREAD

**Issue by 666nosferatu** [Atlantiss/NetherwingBugtracker#8536] opened 2023-07-06 20:31 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Hello, Quest not working, Event is not fired. Link:
https://www.wowhead.com/classic/ru/quest=8519/%D0%BF%D0%B5%D1%88%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%B4%D0%BE%D1%81%D0%BA%D0%B5-%D0%B2%D0%B5%D1%87%D0%BD%D0%BE%D1%81%D1%82%D0%B8

**Comment by Godmatik** [comment] 2023-07-12 02:46
Duplicate of this:

https://github.com/Atlantiss/NetherwingBugtracker/issues/1434

**Closed as completed** 2023-07-14 10:52 UTC
