### ISSUE TITLE
[Hunter] Pet skills get lost/bugged when re-training pets.

### ISSUE THREAD

**Issue by Suzaru** [Atlantiss/NetherwingBugtracker#6437] opened 2019-11-26 02:06 UTC
**Description**: 
When you "re-specc" your pet as a hunter, the pet naturally loses all its abilities temporarely (as it should). The problem is, it seems to be losing the ability to retrain them. They vanish completely. The character gets stuck in a state where the pet can not re-train skills and it can not "discover" them again, because they seem to be there in a weird way. I tried to tame a new pet - no difference.

The only fix to this is a manual GM training (it got fixed by .learn command on the player!).

**Current behaviour**:
As you retrain pet skills it loses its abilities, but abilities like "Screech" for example drop out the table completely. Sadly some abilities vanish. 
For example: I had an owl with "screech". I retrained the owl - all abilities lost. They were gone from the pet skills table. No chance to re-train them. They just vanished. There was no player-able fix to this. I tried to retame a new owl and it never discovered screech again. I guess the player gets stuck in a state where the character "knows" the spell, but the pet doesn't anymore. That way the pet can't "train" the spell to the player, who in return could skill it in the pet skills tab.

**Expected behaviour**: 
You should be able to retrain pet skills you "discovered" once, without them vanishing ever again. Even if you retrain your pet.

**Server Revision**: 
3196

**Comment by Zarant** [comment] 2020-07-07 21:55
Tried to reproduce this bug on the PTR and I can't, need more info.

**Comment by Godmatik** [comment] 2024-07-15 23:26
Unable to reproduce.
I have played Hunter for past year on Netherwing and respec my pet all the time.
Never once heard of this happening from anyone else either.

Closing.

**Closed by Godmatik** 2024-07-15 23:26 UTC
