### ISSUE TITLE
[Hunter Class] [Feign Death] Once pet is dead and you're in FD enemies will still attack you

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5966] opened 2019-06-22 07:32 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When using Feign Death because you got aggro, FD will 90% of the time not work and you just stand there, but when it does work. Your pet will get aggro, but once your pet is dead. The enemies go to you WHILE you are still in Feign Death mode. 

**Current behaviour**: Feign Death not working as Intended, still getting attacked while using Feign Death, and most times Feign Death won't work at all, your character just stands there or an error message pops up saying "resisted"

**Expected behaviour**:  Feign Death working 100% to lose aggro, so your pet gets aggro, also if your pet dies. Enemies de-aggro and leave you alone, while under Feign Death. 

**Server Revision**:  3031

**Comment by danbopes** [comment] 2019-06-22 07:52
Dupe of #5716

**Comment by Kaidalen** [comment] 2019-06-25 07:33
It is not a dupe. It is just MY experience and raising awareness. If it hasn't been fixed in MONTHS then Devs should be fixing it and not leaving it alone. Hunters are broken! and its unfair to hunter players.

**Comment by Easyfraggy** [comment] 2019-06-28 06:53
Duplicate

**Closed by Easyfraggy** 2019-06-28 06:53 UTC
