### ISSUE TITLE
[Item][Food] Eating food sometimes doesnt award buff

### ISSUE THREAD

**Issue by liek0r** [Atlantiss/NetherwingBugtracker#4642] opened 2019-01-27 15:25 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This has started happening recently. Food doesn't work.

https://streamable.com/d5kpy

**Expected behaviour**: 
Should get food buff.

**Server Revision**:

**Comment by nullfoxh** [comment] 2019-01-27 22:16
Duplicate of this. You can see your character continue turning just like in this report: https://github.com/Atlantiss/NetherwingBugtracker/issues/3962

**Comment by Manaci** [comment] 2020-01-04 00:16
Fixed

**Closed by Manaci** 2020-01-04 00:16 UTC
