### ISSUE TITLE
[Spell][Hunter] Feign Death

### ISSUE THREAD

**Issue by RoboboR77** [Atlantiss/NetherwingBugtracker#5716] opened 2019-04-30 21:53 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Feign Death does not reset the mob if your pet was alive when you cast FD. This has been a bug for many months please fix.

**Current behaviour**:
You are attacking a mob with your pet out and alive. You have the mob's aggro. You cast Feign Death and it successfully goes off without resists (get the FD buff). You leave combat and the mob attacks your pet until your pet dies. The mob immediately goes back to attack your FD body and you get put back into combat.

I believe this bug also happens in dungeons if you FD before your pet or party members die. In this way, Feign Death only works as a threat reset like Priest Fade instead of a way to exit combat/avoid death like Rogue Vanish. 

**Expected behaviour**: 
You are attacking a mob with your pet out and alive. You have the mob's aggro. You cast Feign Death and it successfully goes off without resists (get the FD buff). You leave combat and the mob attacks your pet until your pet dies. The mob drops aggro and goes back to its spawn point/patrol area.

Source: https://youtu.be/dXE_RR5XzE8?t=638 - Video from retail vanilla. Hunter feigns, pet dies after feign death and then the boss is reset.

**Server Revision**: 
2947

**Comment by RoboboR77** [comment] 2019-05-02 00:05
https://www.wowhead.com/spell=5384/feign-death#comments:0

I also found this comment:

"If you're in Outland or Northrend and you find yourself in a sticky situation, there's a neat little trick you can do to escape. Simply put your pet on passive and feign death. You're pet is still getting attacked, but you yourself are removed from combat. All you have to do is mount up and presto! The mobs reset when your pet despawns, and you're out of combat and free to fly away. Note that this obviously won't work against players, but it's a convenient way to escape any hostile NPCs."

You can see that in the above situation, when you feign death the mobs attack your pet. Once the pet despawns (or dies), the mob should reset. This is not happening currently on the server and needs to be fixed! You lose so much utility out of FD if you can't reset a mob when you FD with pet or party members still alive.

**Comment by KevinTyrrell** [comment] 2019-05-03 02:23
Possible duplicate of #2252

**Comment by Kristoferhh** [comment] 2019-05-04 21:43
There are multiple duplicates, but still worth posting since it isn't getting a fix after many, many months for whatever reason despite being an insanely annoying bug for hunters

**Comment by Dragunovka** [comment] 2019-05-05 18:33
up

**Comment by Dragunovka** [comment] 2019-06-13 21:39
up

**Comment by czarecoo** [comment] 2019-06-27 16:56
pls fix

**Comment by Wolffenstein** [comment] 2019-07-01 21:47
Retest again after revision 3052.

**Closed by Wolffenstein** 2019-07-01 21:47 UTC
Labels: Class: Hunter, Spell, Status: Need Research

**Comment by Kaidalen** [comment] 2019-07-12 14:43
Feign Death **still** broken

**Comment by Nuy** [comment] 2020-07-26 16:48
STILL BROKEN.
