### ISSUE TITLE
Hunter Pet damage issues

### ISSUE THREAD

**Issue by Lecia2134** [Atlantiss/NetherwingBugtracker#6055] opened 2019-07-02 13:22 UTC
**Description**: 
Pet damage seems to be off at random. Either one hunter's pet is doing far too much damage (the most likely thing) or the others are not doing enough. 
**Current behaviour**:
In a raid, (example, gruuls) one hunter's pet will do 150k auto attack damage while 3 other hunter's pets do around 75-80k 

**Expected behaviour**: 
I believe something is occurring to increase the one pet's damage (some kind of incorrect value probably attack speed) for some unknown reason. All pets should do similar damage (especially considering they're all the same type of pet). Each pet should do 75-80k in the instance I described based on gear and other variables such as the hunter's number of crits. It just should not vary as much as it does (150k is far too much of a difference to be gear related). 
 
I will try and get the logs to show exactly what I'm talking about asap.

**Comment by Eidous** [comment] 2019-07-02 13:32
some legacylogs where a pet did double damage as example (not sure if linking like this works):

https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7740&exp=1&upl=11562
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7692&exp=1&upl=11484

we validated the data from the Tempest raid with the data we got from WoWCombatlog.txt and recount, so it's not a legacylogs bug.

For our raids it also happened at Hydros where the hunters pet was constantly attacking the boss with a 0.8s attack speed (normal is 1-1.2s). There's no legacylogs of this, but i think we still have the wowcombatlog.txt for it.

**Comment by Easyfraggy** [comment] 2019-07-02 14:31
You need to specify pet names - we don't know your players.

**Comment by Eidous** [comment] 2019-07-02 16:37
ah true my bad. if you navigate to the gruul fight, and click on the top hunters damage, it'll show you a breakdown of the damage. You can see that the autoattacks (which are the pets autoattacks) deal as much damage as the autoshots of the hunter himself. 

I agree that being able to reproduce the effect would really help, but we've had no luck so far. 

It only occurs in raids during boss fights for 1 hunter. (that is to say it always happens for the pet of a certain hunter, it doesn't randomly switch between different hunter pets).

Furthermore the effect seems to be random as well, in Gruul it was a damage increase, but in SSC it was an attack speed increase for the pet. 

Since nothing shows up in the combatlogs, there's no aura stacking or anything, we're absolutely clueless on how we could reproduce it.

**Comment by Easyfraggy** [comment] 2019-07-02 18:38
That does seem extremely weird. I did dig around in your log and found that the pet for the hunter in question did around 613 dps on gruul and compared it to other hunters. And found some other cases of pet doing equal or higher dps: 

Pet "Hiss" 774 dps https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7692&exp=1&upl=11484
Pet "PewPew" 750 dps https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7741&exp=1&upl=11565
Pet "salah" 657 dps https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7250&exp=1&upl=10755

Maybe this can help you isolate a pattern? I don't know much about hunters.

**Comment by Saronitian** [comment] 2019-07-03 00:51
there are a few vey important questions to be asked:
1. Are both hunter bm and have a similiar choice of talents?
2. Wich pets do they use? Ravenger and Serpants dmg vary drasticly.
3. Do they have the same support or are they in the same group?

this makes it also very difficult to test or recreate any kind of problem. you would need to build your raid around a test.
_________________________
From what I have seen so far is that the dmg of the melee hits of pets across the board are pretty normal depending on how much those scale with ap.
I just don't wuite understand how a Serpant does more dmg with melee hits than a Ravenger when a ravenger with same gear should do at least the same amount of dmg as a serpant if not more (because is deals 3% more dmg) but if serpant scales better with ap it is normal for him to do more dmg per hit.
[something I don't know cause I can't look into the server]

another thing I still could not figure out is the "random" increase in attackspeed of the serpant down to 0.85-0.9 without skills like bloodlust/hero, drums etc. it just happens!
maybe someone has an explanation for that behavoir that I've missed.

**Comment by gunzbngbng** [comment] 2019-07-03 01:03
Ten bucks says a pet decided to not be happy (25% damage bonus loss).

**Comment by Zerexx** [comment] 2019-07-03 09:52
We had a similar experience last week on Karathress, where one pet (Hunter Ynizzle) did ~80k more autoattack dmg on near close amount of attacks (355 vs 341). Targets were the same. Only difference is that no special attacks were used by said pet.

https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7695&exp=1&upl=11488


Same happened yesterday on Gruul (unfort no log here). Ravager landed 41% dmg of the hunter's damage and outdpsd a Serpent by ~100k dmg. I don't know if the gap is realistic, as the Serpent had nearly 100% uptime on the boss and the respective hunter has around 35% crit. That however might correlate with this issue: 

https://github.com/Atlantiss/NetherwingBugtracker/issues/5921


For the Karathress fight we have no explanation except extreme crit luck of the pet.

**Comment by Saronitian** [comment] 2019-07-03 13:08
Zerexx first please name wich hunter has wich pet I spent a few minutes figuring that out but.
Had all your hunters the same conditions? where they in the same group on FLK?

The normal damage of the 3 other pets is pretty similiar with a 390 / 350 dmg per hit but Ravenger ( Ynizzles pet had a normal hit of 610 / 470 that seems strangely high. Sadly Legacylogs does not provide enough detailed informations to get better informations on whats behind those numbers.

If all 4 hunters where in the same group, pets are all sated, everyone was buffed and bm (wich I guess they all where).

ravengers strangely higher critrate let's me think he was not in the same group. 27% instead of 12% like everyone else doesnt really fit and is highly unlikely.

**Comment by Zerexx** [comment] 2019-07-03 13:18
Zerex - Laplace
Ynizzle - Ravager
Seruka - redrum
Elwyn - Antaares

All hunters had the same conditions: same group, buffs, specc and similar gear.


I found the log for yesterdays Gruul as well. the variance in crit rating is even larger here. ravager had like 32% melee crit vs serpent 16% causing ~110k difference in dmg.

https://legacyplayers.com/Raids/Viewer/Default.aspx?id=7753&exp=1&upl=11587

**Comment by Saronitian** [comment] 2019-07-03 14:25
in this case its "probably" because Orc versus Troll, disregarding the critrates the ødamage is still pretty normal "around 25-30% more"

**Comment by Zerexx** [comment] 2019-07-03 14:54
Sure, Orc vs Troll would be 5% difference. But this dmg gap between Ravager and Serpent is hard to believe at this state of equip. And it does not explain the FLK fight where it was Blood Elf vs Troll, both on Ravagers.

**Comment by Saronitian** [comment] 2019-07-03 15:04
The only thing I could find after days is a "maybe" . Bestial Wrath 's effect does not end. maybe some kind of permanent aura. would require Detailed testing.

**Comment by Wolffenstein** [comment] 2019-07-04 20:52
Let me know when it's happening so i can check in-game. Saying it after the fact doesn't help me at all.

**Comment by Evolvee** [comment] 2019-07-04 20:52
when it happens, u need to immediately contact Wolf, not 2 months later

**Comment by The14me** [comment] 2020-07-08 15:40
Rev.3460 Pets look fine to me.

**Closed** 2020-07-08 19:52 UTC
Labels: Exploit/Abuse - Priority, Pets
