### ISSUE TITLE
[Paladin][Spell] Divine Shield and Lay on Hands

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5586] opened 2019-04-07 16:14 UTC
**Description**: Sometime when you use bubble or LoH on very low HP before death CD starting but spell not affect caster, no bubble or heal depends on spell

**Server Revision**: 2930

**Comment by Evolvee** [comment] 2019-04-07 16:58
no spell delay 😢 😭 😿 🐺 😠

**Comment by veekk** [comment] 2019-04-07 18:54
is it ok or that's bug then?

**Comment by Evolvee** [comment] 2019-04-07 19:49
"bug"

**Comment by Godmatik** [comment] 2024-07-07 04:20
Unable to reproduce and have not heard anyone complain about this in past year on Netherwing, perhaps fixed at some point.

Closing for now.

**Closed by Godmatik** 2024-07-07 04:20 UTC
Labels: - Core Mechanic
