### ISSUE TITLE
[Profession][Fishing] Unable to fish in Terokkar

### ISSUE THREAD

**Issue by Lillaeth** [Atlantiss/NetherwingBugtracker#4676] opened 2019-01-28 14:42 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Can't catch any fish in Terokkar. Have 355 fishing, the +25 fishing rod and used Aquadynamic fish attractor and it doesnt even say that the fish ran away, nothing happens. The fishing bobber just fades out.
**Current behaviour**:
The fishing bobber just fades out, tho if we do not use a lure, it tells us the fish ran away. Have tried fishing in the lakes, ponds and the river. Even had someone else also try it. Same problem for them as for me. The fishing pools works just fine.
**Expected behaviour**: 
To be able to catch all the fishes.
**Server Revision**:

**Comment by transphenomenal** [comment] 2019-01-31 22:20
I'm having the same problem. No fish with no "Your fish got away" message. I am however, getting fishing skill occasionally, even though I'm not getting any fish. And I am getting "Your fish got away" messages sometimes as well.

**Comment by ttghnw** [comment] 2019-02-13 11:47
This ^^ still happening as described above.

**Comment by Setzer1994** [comment] 2019-02-26 18:50
Still happening, unable to fish anywhere in Terokkar.

**Comment by Nythius** [comment] 2019-03-08 22:36
Still happening.

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment] 2019-03-09 03:41
Confirmed still happens. Fish pools work correctly however.

**Comment by Liince** [comment] 2019-03-13 16:03
I can confirm this.

**Comment by Dollywog** [comment] 2019-03-18 00:17
can confirm lol feelsbad

**Comment by caiopmartins** [comment] 2019-03-27 19:15
Same here. Only fishing in Terokkar is on fish schools.

**Comment by OffeSwedin** [comment] 2019-04-06 10:28
Same, fishing golden darter is a nightmare because of this lol

**Comment by Cyal** [comment] 2019-04-10 12:36
That was disappointing :D.

**Comment by Daniel-Steinberger** [comment] 2019-07-28 12:18
Same here.

**Comment by Wolffenstein** [comment] 2019-08-12 21:20
Fixed in rev 3104.

**Closed by Wolffenstein** 2019-08-12 21:20 UTC
