### ISSUE TITLE
Prayer of Mending attributes threat to priest

### ISSUE THREAD

**Issue by dimiwilson** [Atlantiss/NetherwingBugtracker#9153] opened 2024-08-11 13:58 UTC
Current behaviour:

Prayer of Mending spell attributes it's threat to the casting priest when the target takes damage and PoM heals.

Expected behaviour:

This threat is supposed to be considered a "selfheal" of the target, and should attribute its healing threat to the target it is currently cast on.

Steps to reproduce the problem:

Cast PoM on a target (e.g. tank in dungeon)
Target runs to target and doesn't cast any spells, aggroing mob but not generating any threat.
Target takes damage leading PoM to proc and target to heal. Mobs will run to priest, where as this threat should be given to the target instead.
Reference information: Prayer of Mending: when Prayer of Mending procs (i.e. dmg taken, PoM charge gets used up), the threat from the healing done is attributed directly to the person being healed. This is incredibly useful for tank threat, as you can put PoM and a PW:S up on a tank just before the pull, and instantly refresh the PoM when the first charge is used up for an easy 2k+ threat for your tank. This is enough to land a 4k heal without pulling aggro: very useful for heroics where you have no salv and no CC.

**Comment by Godmatik** [comment] 2024-08-24 00:59
Unable to reproduce.

Followed your exact steps - the threat is properly transferred to the target that is healed, see the below video clip where the paladin did 0 damage but still held aggro after a wand was used from the priest.

Even installed Stormforge Threat Meter (which takes threat data directly from server API) to verify.

https://streamable.com/te2kgy

**Closed as completed by Godmatik** 2024-08-24 00:59 UTC
Labels: invalid
