### ISSUE TITLE
Inviting someone to group says they're ignoring you

### ISSUE THREAD

**Issue by seitzcasey** [Atlantiss/NetherwingBugtracker#7413] opened 2020-08-19 02:09 UTC
**Description**:
Inviting someone to party who is in a dungeon that is set to a difficulty that is different than the person inviting says the invitee is ignoring the inviter.

Player A is in a heroic dungeon not in a party.
Player B is in Azeroth with their dungeon difficulty set to normal.

Player C is in a normal dungeon not in a party.
Player D is in Azeroth with their dungeon difficulty set to heroic.

**Current behaviour**:
Player B invites Player A to group. Chat says Player A is ignoring Player B. Player A does not receive a group invite.
Player D invites Player C to group. Chat says Player C is ignoring Player B. Player C does not receive a group invite.

**Expected behaviour**: 
Player B invites Player A to group. Player A receives a group invite.
Player D invites Player C to group. Player C receives a group invite.

**Server Revision**: 
3517

**Comment by Tereneckla** [comment] 2020-08-19 06:32
Duplicate of #2604

**Comment by Wolffenstein** [comment] 2020-09-07 18:38
Fixed in rev 3523.

**Closed by Wolffenstein** 2020-09-07 18:38 UTC
