### ISSUE TITLE
[Core] Logout in flight puts you at start of flight when you log in again

### ISSUE THREAD

**Issue by Nixon-Joseph** [Atlantiss/NetherwingBugtracker#6260] opened 2019-09-04 00:57 UTC
**Description**: 
Logout in flight puts you at start of flight when you log in again

**Current behaviour**:
I was in a chained flight, from a flight master, and logged out in the middle of the second leg out of a 2 leg flight, and when I logged back in (I don't think it had been long enough to reach the destination if that matters), I was put to the start of the second leg, as if I just started the flight.

If I remember correctly, doing this is regular WoW put you back into the flight where you would have been had you not logged out, or at your destination if you were logged out longer than the flight duration.

Potentially could be same issue as  [6044](https://github.com/Atlantiss/NetherwingBugtracker/issues/6044)

**Expected behaviour**: 
Log in at destination (if it's been long enough) or where I would have been in flight had I not logged out, or, at the very least, where I was in flight when I logged out.

**Server Revision**: 
3116 [Branch: master, Hash: f1051b45fa39]

**Comment by The14me** [comment] 2019-09-26 08:07
Its wrong,but still there is a bug with flight path.Its suppose to port you in next flight path when u log in again.
https://www.wowhead.com/forums&topic=33705#p304865

**Comment by Zarant** [comment] 2020-07-07 04:22
This issue is a duplicate of #4016

**Closed** 2020-07-07 07:29 UTC
Labels: Other
