### ISSUE TITLE
Nature's Swiftness rendered unusuable

### ISSUE THREAD

**Issue by Zaegan** [Atlantiss/NetherwingBugtracker#6062] opened 2019-07-03 23:20 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Battlegrounds, sometimes dying while under the effect of Nature's Swiftness makes you lose the ability to cast Nature's Swiftness until the battleground ends.

**Current behaviour**:
In Battlegrounds, dying while under the effect of Nature's Swiftness makes Nature's Swiftness uncastable. When you try to use Nature's Swiftness, it says that it is on cooldown, but the cooldown countdown does not start, so it stays on cooldown for the rest of the battleground. 

/reloadui does not get the countdown to start.

**Expected behaviour**: 
When dying while under the effect of nature's Swiftness in battlegrounds, the effect should be the same as dying anywhere else while under the effect of Nature's Swiftness. The buff does not persist through death, so you lose the Nature's Swiftness buff and the 3 minute spell cooldown starts counting down as soon as you die.

And, if the cooldown does get bugged, it seems like there ought to be some way to giggle it loose. Maybe /reloadui isn't the thing to do, but there should be some way that you can make the system check whether you currently have nature's swiftness, and if you don't, allow the 3 minute cooldown on nature's swiftness to start counting down.

**Reproducibility**
Unfortunately, I have not been able to completely reproduce this bug. It has only happened two times, both times in battlegrounds. When I tried dying to Lv 62 mobs in Terrokar Forest while under the effect of Nature's Swiftness, nothing unusual happened. It is possible that this can only happen in battlegrounds.

One line of inquiry I'm currently pursuing is that it happens, not when NS is removed by death, but when it is removed by purge, or when it is stolen. 

If it's due to spellsteal, and there was just a mage gleefully waltzing around for 10 minutes with my Nature's Swiftness in those battlegrounds, this isn't a bug at all. There are a couple of reasons why I think it's not working that way currently:
1. It is really hard to stay alive for that long in a battleground. Most likely the mage would have died around the same time I did, at which point he would have given me my NS back. 
2. It is highly unlikely that the server keeps track of who has whose Nature's Swiftness, given how rare it is that anyone has Nature's Swiftness other than the one who casted it.

If it happens again, I will try to take a screenshot.

**Server Revision**: 
Server Revision: 3054 [Branch: mail_rework, Hash: 86e2f37b05e4]
Current Patch 210.

**Comment by Zaegan** [comment] 2019-07-06 04:52
Update, screenshot taken
![NS Bug](https://user-images.githubusercontent.com/52512866/60751682-eb624c80-9f87-11e9-9e00-a670f33a6cd9.png)

This is a screenshot of me in a battleground not being able to use NS. As should be clear, I don't have NS on me, but the nature's swiftness button is acting as if I have nature's swiftness already activated. if you click it says spell is not ready yet, but instead of counting down, it stays unusable.

This situation went back to normal as soon as the battleground ended, but not until then.

**Comment by jasonbourne109** [comment] 2019-07-08 23:16
Also happens to Shaman's version of Nature's Swiftness. I have had this happen to me outside of battlegrounds as well. The only way to fix it is to zone in to a new instance. Leaving the dungeon or battleground that I was in has always fixed it. 

I'm not sure exactly what causes it either. Sometimes I die with NS active and it works normally, sometimes this bug as you described it happens instead.

**Comment by The14me** [comment] 2020-07-05 07:27
Not able to reproduce it at 3441.

**Comment by Wolffenstein** [comment] 2020-07-07 22:14
Fixed in rev 3457.

**Closed by Wolffenstein** 2020-07-07 22:14 UTC
