### ISSUE TITLE
([Quest][The Barrens] The Angry Scytheclaws)

### ISSUE THREAD

**Issue by Humanadam** [Atlantiss/NetherwingBugtracker#3866] opened 2019-01-05 22:09 UTC
The quest works fine,but the feathers from the raptors are not loot shared!

**Comment by dmrljes** [comment] 2019-01-05 23:12
I farmed last feather for 2 hours *literally*, it cannot be dropped for some reason. I wasn't in party. The other 2 feathers were totally fine, I got them within 10 minutes.

**Comment by dmrljes** [comment] 2019-01-05 23:32
#376 Is also not fixed

**Comment by wtRCH** [comment] 2019-01-06 11:49
@Shanghi

**Comment by RelmAtlantiss** [comment] 2019-01-07 03:08
The feathers are loot shared. The issue is, if you use a feather on the nest, you can't loot a feather again.
https://github.com/Atlantiss/NetherwingBugtracker/issues/376

**Comment by H2714** [comment] 2019-01-19 09:56
I've tried to complete it four times now.  The nests don't register properly in the journal, have never been able to get the red one to work. Think it registers the wrong color and messes it all up.

Most raptors have empty loot windows instead of feathers (should be an 80% drop). Sometimes abandoning the quest and retaking it makes the drop work.

**Comment by Aesso** [comment] 2019-02-13 06:26
Still bugged. 100+ raptors and quest abandoned twitce I still don't have all the feathers.

**Comment by CCmagro** [comment] 2019-04-22 17:32
After using 2 feathers the 3rd never drops. Tried this quest twice.

**Comment by shatich** [comment] 2019-05-21 11:08
I confirm it. 3rd feather never drops, empty lootboxes from 80% of the raptors.

**Comment by Godmatik** [comment] 2019-08-19 20:52
Still doesn't work :(

**Comment by Evolvee** [comment] 2019-12-23 19:25
fixed in next rev

**Closed by Evolvee** 2019-12-23 19:25 UTC
Labels: Loot, Quest
