### ISSUE TITLE
[Hunter][Pet] Issue with pet and stay command.

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#620] opened 2018-09-26 02:22 UTC
**The pet sometimes acts as its on "stay" even tho its on follow and no such commands have been issued, difficult to replicate. But happends frequently in dungeons, specialy Razorfen Kraul**:

**Comment by Knoox** [comment] 2018-09-26 23:31
Happend again @ Scarlet Mona Cath gate, paulizzy's Voidwalker refused to move. Follow command had to be spammed

**Comment by Ahmpy** [comment] 2018-10-12 04:39
i've had this a few times when leveling and i still can't figure out what causes it. I've tried multiple times to replicate it but can't, what I can say is that I noticed the client issues a stay command, and the pet will be set into the stay mode by itself, afterwhich the bug happens. It is removed if the pet dissapears via mounting/dismissal or death.

**Comment by xycz** [comment] 2018-10-25 13:59
Can confirm what Ahmpy wrote, difficult to replicate, does still occur, basically reenabling follow will only move the pet to your current position and it will sit there instead. It can be temporarily solved by dismissing  pet.

**Comment by scarabadookie** [comment] 2018-11-28 22:02
This happened to me multiple times in SSC recently, after using stay to keep pet away for various reasons. Need to do more experimenting to reproduce and find the cause, but it seemed to happen a lot in the instance.

**Comment by aresbrutus** [comment] 2018-11-30 21:57
https://gfycat.com/CapitalSevereBullmastiff
https://gfycat.com/CavernousSameArctichare

Need a way to reproduce.

**Comment by Tenoutoften** [comment] 2018-12-07 05:42
* Pet stay bug occurs when you interrupt the movement of 'return to stay position' with an attack command.
* When your pet is in 'stay' mode and you send it to attack it stores the position of stay and will 'return to stay position' when it either kills a mob or you initiate passive mode.

Reproduction video [here](https://www.youtube.com/watch?v=E0XAvZyUVfo&feature=youtu.be)

**Comment by Wolffenstein** [comment] 2018-12-14 20:19
Fixed in rev 2434.

**Closed by Wolffenstein** 2018-12-14 20:19 UTC
Labels: - Core Mechanic, Class: Hunter, Pets
