### ISSUE TITLE
[Dungeons][General] Party members are getting ported to the wrong instance after resurrection or re-entering via ghost

### ISSUE THREAD

**Issue by Kornstalx** [Atlantiss/NetherwingBugtracker#5406] opened 2019-03-18 00:06 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I've had this happen 3 separate times this past week, all in a long dungeon (BRD). At some point after a party member dies, if he leaves the instance by releasing, he cannot get back in the same instance. 

On the first occasion we had two players die in a boss fight; both released. We could see their bodies and the priest resurrected them but they appeared in another mirror copy of the instance. They would accept the resurrection, and suddenly be in the same spot as we were, however they could not see us nor could we see them, and they said the whole room was re-populated. They would die from mobs almost immediately.  

On the second occasion a day later I was in a group that lost 3 players in a fight. Two of them did not release but one did. Upon resurrecting the two players that did not release, everything was fine. However again like before, the player that released was resurrected into a mirror copy of the instance and killed by mobs immediately. 

On the third occasion (last night) I was in a pick-up group again in BRD and we lost a single player in a fight, and he released. Same situation as before (rez'd into a different instance) but we did some troubleshooting with this guy. We tried everything from transferring party leader around, to him relogging, to the party leader relogging, we even had him corpse run back to the instance and enter it again manually. When he entered the front door of BRD again he said it was a different instance (everything was repopulated). The four of us that were still alive back-tracked to the entrance to try and see him. We could not see him, and to us the dungeon was still clear.

However, after the 4 of us left the dungeon instance and stepped outside, we saw the missing party member as normal. Then all 5 of us re-entered; the dungeon was completely reset.

**Current behaviour**:
After some time in a dungeon (I believe a timeout is causing this) if one player gets out of the dungeon by releasing on death, they cannot get back in with the party as it puts them in another instance of the same dungeon.

**Expected behaviour**: 
Party members should always be in the same instance of a dungeon as the party leader.

**Server Revision**: 
2891

**Comment by Evolvee** [comment] 2019-03-18 00:46
this is BRD-only afaik

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment] 2019-03-29 05:05
I have seen this happen both in BRD (dupe of #1902) and in Maraudon. 
In my Maraudon report #5213
I assumed using the scepter was the cause but I did no further testing. It may simply be a timeout and if so it may be the same bug as BRD.

**Comment by danbopes** [comment] 2019-04-21 14:54
This is not just related to BRD, as this has happened in SSC as well as Maraudon (Although, most of the issues seem to stem from BRD).

**Comment by Zaytsev313** [comment] 2020-02-24 04:15
My friends and I have this happen to us a lot. It may something to do with the length of time a party spends in the dungeon, which is why most people report it on the longest dungeon in the game (BRD). However, until we hit 70, my two friends and I would 3-man dungeons for the hardmode aspect of it, regularly taking 2-3 hours to clear all vanilla and TBC dungeons. After about 2 hours we notice the issue occurs more frequently-- not trash respawning (expected), but players spawning into entirely new dungeons (bugged). We have verified this by having the living players from the old instance go back to the beginning to see that, in fact, the ressed players are not visible.

If you want to test this danbopes, try sticking two characters in a dungeon for 2-3 hours. Kill one of them after that and res him. Rinse and repeat for a while and it will inevitably occur.

**Comment by Wolffenstein** [comment] 2020-07-04 04:00
Fixed.

**Closed by Wolffenstein** 2020-07-04 04:00 UTC
