### ISSUE TITLE
[Sunken Temple][NPC] Spawn of Hakkar

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1107] opened 2018-10-03 00:09 UTC
**Does not path**: 

**Server Revision 2108
![wowscrnshot_100318_010347](https://user-images.githubusercontent.com/18479169/46383594-6c1ab200-c6b1-11e8-88d3-4c8095f2734e.jpg)
**:

**Comment by Easyfraggy** [comment] 2018-10-03 07:29
Do you have some evidence that he should? On videos he is always with this pack.

**Comment by aresbrutus** [comment] 2018-10-05 22:16
https://www.wowhead.com/npc=5708/spawn-of-hakkar#comments

Fixed in one of the upcoming updates.

**Closed by aresbrutus** 2018-10-05 22:16 UTC
Labels: Dungeon, Movement

**Comment by Easyfraggy** [comment] 2018-10-05 22:33
Did you remove him from the formation aswell Kutsal?

**Comment by aresbrutus** [comment] 2018-10-05 22:48
There were not part of the formation, just was standing in the middle of them.

**Comment by Firroth** [comment] 2018-10-08 20:46
Well rather than make another issue with the same NPC, I will add it to this one.

**How it is now**
[Spell] [Acid of Hakkar](https://classicdb.ch/?spell=12280) does nothing. No damage, no DoT, no visual effect.

**Expected behaviour**
[Spell] [Acid of Hakkar](https://classicdb.ch/?spell=12280) should give on his target undispalable 1min DoT, which deals damage every 2s.

**Server Rev**
2137

**Comment by Easyfraggy** [comment] 2018-10-08 20:54
Should make a new report on that because it's a spell and needs a core fix most likely, so if you could copy pasta your comment into a new issue that would be great.
