### ISSUE TITLE
[Item] Hallowed Raiment 4p set bonus not working

### ISSUE THREAD

**Issue by Columbia24** [Atlantiss/NetherwingBugtracker#4766] opened 2019-02-01 23:37 UTC
**Description**: The Hallowed Raiment set bonuses don't appear to be active 

**Current behaviour**: The 4p bonus is not affecting initial or subsequent bounces of prayer of mending

**Expected behaviour**: "Your prayer of mending heals for an additional 100 health"

**Server Revision**: 2789

**Comment by Tenoutoften** [comment] 2019-02-02 00:14
[[Spell]Improved Prayer of Mending#37558](https://db.excalibur.ws/?spell=37558)

**Comment by Manaci** [comment] 2020-01-04 00:15
Duplicate of [this](https://github.com/Atlantiss/NetherwingBugtracker/issues/2780)

**Closed by Manaci** 2020-01-04 00:15 UTC
