### ISSUE TITLE
Mind Vision

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9111] opened 2024-05-26 01:05 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mind Vision is regarded as an attack.

**Current behaviour**: Using it will aggro guards, even in Neutral areas like Shattrath.

**Expected behaviour**: Should not be flagged as an attack.

**Server Revision**: 4002

**Comment by ghost** [comment] 2024-05-26 01:05
Also, /cancelaura Mind Vision is no longer working.

**Comment by Godmatik** [comment] 2024-05-26 04:18
Confirmed that Mind Vision is aggroing neutral guards but should not

/cancelaura Mind Vision works fine for 2.4.3, but not in 3.3.5
You can still cancel it though by moving or jumping

**Comment by Wolffenstein** [comment] 2024-05-27 16:17
Mind Vision aggro will be fixed with next update.

Cancel won't work on WotLK client because the aura flags have changed and it's no longer possible to make negative spells be cancellable

**Closed as completed by Wolffenstein** 2024-05-27 16:17 UTC
