### ISSUE TITLE
air clouds

### ISSUE THREAD

**Issue by notoriouscow** [Atlantiss/NetherwingBugtracker#7971] opened 2021-04-13 11:10 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Air clouds in Nagrand can't be reached

**Current behaviour**:
clouds are spawned mid sky, and can't be zapthrottle at all. out of range.

**Expected behaviour**: 
cloud radius is expected to be nearer the "sky earth islands". so they can be reached with zap
**Server Revision**:

**Comment by Tereneckla** [comment] 2021-04-14 10:34
Duplicate of #7960

**Closed as completed by Tereneckla** 2021-04-14 10:34 UTC
Labels: Duplicate
