### ISSUE TITLE
Invisibility in Arenas

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#5500] opened 2019-03-28 22:11 UTC
**Description**: 
Mage with active Invisibility is bumped out of it when enemy mage enters invisibility during arena.

**Current behaviour**:
Mage A enteres invisibility before arena starts.
Mage B from opposite team enters invisibility after arena starts.
Mage A looses his invisibility immediately.

**Expected behaviour**: 
Mage A should not loose his invisibility.

**Server Revision**: 
2909

**Comment by Wolffenstein** [comment] 2019-03-31 03:18
Cannot reproduce. Can you record that?

**Comment by kemotix** [comment] 2019-04-01 16:41
Yeah, sure!

**Comment by kemotix** [comment] 2019-04-06 09:20
2 days ago met mage in Blade's Edge Arena and Invisibility worked as intended. Bug didn't occur.
It happened on Ruins of Lordaeron, so maybe it's bug specific to that arena only.

**Comment by Godmatik** [comment] 2024-07-01 21:36
Was fixed in rev 4012

**Closed by Godmatik** 2024-07-01 21:36 UTC
Labels: Spell, PvP: Battleground & Arenas, PvP: Mechanics, - Core Mechanic
