### ISSUE TITLE
[Core] Combat zoning on and off

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1269] opened 2018-10-05 22:23 UTC
These NPC's seem to be causing this problem from my point of view.
[NPC] Entry: 11620 Spectral Marauder
[NPC] Entry: 11621 Spectral Corpse

**Current behaviour**:
Combat in this place seems to be broken, since these ghosts which are not attackable "neutral" are combat zoning you on and off, even if they don't enter combat themselves. Just by being near them turns this combat zoning on and off.

![2018-10-06_00-15-42](https://user-images.githubusercontent.com/43505196/46562635-58fc2200-c8fd-11e8-93fe-85899b44c48a.gif)

**Expected behaviour**: 
Combat zoning on and off shouldn't be happening.

**Server Revision**: 
2130

**Comment by Tereneckla** [comment] 2020-01-08 14:26
It is not the NPCs though, I killed them all and it still happens. Probably related to #1179

**Comment by Tereneckla** [comment] 2020-01-22 10:02
Duplicate of #1376

**Closed by Tereneckla** 2020-01-22 10:02 UTC
Labels: Misc, NPC, Status: Confirmed
