### ISSUE TITLE
Cant use my trinkets

### ISSUE THREAD

**Issue by Shadowybolt** [Atlantiss/NetherwingBugtracker#7785] opened 2020-12-12 18:21 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Shadowybolt** [comment] 2020-12-12 18:22
So I have a rare problem here, I use one of my trinkets and I cant use the other one until the used trinket is ready again, I'd really need some help here, this is frustrating

**Comment by Shadowybolt** [comment] 2020-12-12 18:22
So I have a rare problem here, I use one of my trinkets and I cant use the other one until the used trinket is ready again, I'd really need some help here, this is frustrating

**Comment by Godmatik** [comment] 2020-12-12 19:20
Would've helped if you said what the trinkets are... but I'm assuming this is a duplicate of an issue already reported.

https://github.com/Atlantiss/NetherwingBugtracker/issues/7446

**Comment by Shadowybolt** [comment] 2020-12-15 04:28
the trinkets are Xi'ri's Gift and Scryer's Bloodgem @Godmatik

**Comment by Shadowybolt** [comment] 2020-12-18 08:39
@Godmatik

**Comment by Wolffenstein** [comment] 2021-01-19 09:54
Duplicate. Will be fixed in rev 3587.

**Closed by Wolffenstein** 2021-01-19 09:54 UTC
