### ISSUE TITLE
Stranglethorn Vale Buccaneer ships chainpull 

### ISSUE THREAD

**Issue by Lanakh187** [Atlantiss/NetherwingBugtracker#7911] opened 2021-02-13 20:21 UTC
https://classic.wowhead.com/quest=608/the-bloodsail-buccaneers

 ([Quest][Stranglethorn Vale] The Bloodsail Buccaneers)
 ([NPC] Garr Salthoof and nearby npcs)

If you try to pull mobs to clear the ship, the whole ship chainpulls, making the quest impossible to complete at that level it should be done on. 8+ mobs - including the quest mobs - chainpulls from the bottom of the ship to the top, when you try to pull the first patrol, moving up and down the stairs leading to the middle floor inside the ship.

everything aggroes at once

mobs out of line of sight should not aggro

revision: 3604

**Comment by Tereneckla** [comment] 2021-02-13 20:38
Duplicate of #7048

**Closed as completed by Tereneckla** 2021-02-13 20:38 UTC
Labels: Duplicate
