### ISSUE TITLE
Hunter Quiver

### ISSUE THREAD

**Issue by corkus1111** [Atlantiss/NetherwingBugtracker#2] opened 2018-09-22 19:19 UTC
Cannot move quiver to last spot as it thinks you are trying to equip a second quiver.

**Comment by Vigor021** [comment] 2018-09-23 09:59
Also you can shoot without having quiver or arrows in it.

**Comment by Easyfraggy** [comment] 2018-09-23 19:53
> Also you can shoot without having quiver or arrows in it.

This is not a bug.

**Comment by RandomGuyFromDiscordServer** [comment] 2018-09-29 19:03
Was this fixed?

**Comment by RandomGuyFromDiscordServer** [comment] 2018-09-29 19:04
@Wolffenstein

**Comment by xycz** [comment] 2018-10-21 16:40
No, issue is still not fixed as of rev 2194, to recreate the issue in game, simply have quiver in a bagslot and try to move it to another one, it should give you an error message stating "You can only equip one quiver.". 

The player is only requesting to move the one quiver from bagslot1 to bagslot2 (does not matter which one is used as origin or target). As of now, the only way to move the quiver to a new bagslot is to empty the quiver, move it inside another bag, and then place it on the bagbar again on the desired bagslot.

**Comment by RandomGuyFromDiscordServer** [comment] 2018-10-21 21:07
@Evolvee @aresbrutus is this fixed?

**Comment by Evolvee** [comment] 2018-10-21 22:33
![image](https://user-images.githubusercontent.com/1942409/47273273-1e97b380-d592-11e8-8cb1-391d8e105be3.png)

**Comment by RandomGuyFromDiscordServer** [comment] 2018-12-26 16:13
Still can't move the quiver, because it thinks you want to equip another one. @Evolvee @Wolffenstein

**Comment by Zarant** [comment] 2018-12-27 22:43
You should be able to equip both a quiver and an ammo pouch at the same time, according to the following forum post from ArenaJunkies, where people were discussing between using S3 rifle or illidan bow as a dwarf:

>One itemrack set for Waraxe + Gun, another with 30 int 1's and Black Bow.
Switch happens when I change to viper aspect at about 1k mana. :)
Takes two quivers but oh well. 

http://www.arenajunkies.com/topic/10714-vengeful-gladiators-rifle-vs-bbotb-for-dwarfs/


Also reading the patch notes from patch 1.3.0, leads to believe that equipping multiple quivers is possible, however only one of the bonuses should be considered:

> Fixed a bug where Ammo Pouch and Quiver bonuses were stacking together. Now only the better bonus should be considered. 

http://wowwiki.wikia.com/wiki/Patch_1.3.0

**Comment by Zarant** [comment] 2020-07-04 18:12
Issue is partially fixed, you can move quivers around but you still can't equip more than one quiver/ammo pouch

**Comment by Godmatik** [comment] 2023-07-11 02:47
It's possible this is intended

![quiverandpouch](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/3d06f894-5148-4776-899f-9a6c9552721e)

**Comment by Godmatik** [comment] 2024-07-06 03:50
The main issue of being able to move quivers is fixed.
And it seems like it is intended that you can't equip more than one quiver/ammo pouch, based on the above comment.

Closing

**Closed by Godmatik** 2024-07-06 03:50 UTC
Labels: Class: Hunter, Status: Confirmed, Item
