### ISSUE TITLE
[Quest][Desolace] Gizelton Caravan

### ISSUE THREAD

**Issue by File2006** [Atlantiss/NetherwingBugtracker#8734] opened 2023-10-12 20:31 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest Gizelton Caravan acts out completely fine, but at the end you don't get the completion mark.
**Current behaviour**:
You escort the caravan through the demon attacks, everything works fine, even the goblin says the line that you will be rewarded, but the quest doesn't complete.
**Expected behaviour**: 
You escort the caravan, everyone survives, goblin says the line, you get quest completed.
**Server Revision**: 
3880

**Comment by fondlez** [comment] 2023-10-12 22:04
Make sure you are not using Questie or Questhelper addon specifically.
Exit client and delete the Cache folder under your WoW directory.
Login again and see if it was actually completed.

You may have found a real bug (since it is [listed and open on the tracker](https://github.com/Atlantiss/NetherwingBugtracker/issues/7231#issue-666349410)), but Cache and addon issues are notorious for some quests, especially escort quests, and perhaps if it was bugged it was already fixed in-game.

**Comment by File2006** [comment] 2023-10-13 09:13
But addons shouldn't mess with the internal quest completion, only with the UI, shouldn't they? Because I went to the npc where you are supposed to complete it (twice, after I done it twice) and he had grey quest marker and when I talked to him he didn't offer quest completion, so I think there is no way, where addon could have caused this.

**Comment by Godmatik** [comment] 2024-07-10 02:04
Duplicate of #7231

**Closed as completed by Godmatik** 2024-07-10 02:04 UTC
