### ISSUE TITLE
Multiple Creature Hit

### ISSUE THREAD

**Issue by PolarCookie** [Atlantiss/NetherwingBugtracker#4976] opened 2019-02-12 14:37 UTC
**Description**: 
Certain mobs are able to perform multiple auto attack hits when there should be only 1.
This happens randomly when NO PARRY WHATSOEVER were performed.
Confirmed creatures are Chaotic Sentience and Arcane Protector in the floor area after Curator in Karazhan, on our last raid it took us 6 wipes to reach the ramp up to the shades because tanks would get one shot.
This happens also on trash mobs earlier in Karazhan, at the moment don't remember which, what would happen was at
-1.00 mob would hit
-1.00 mob would special ability
0 mob would hit again
0 tank be dead
still no parry.

I've seen this also on Fel Reaver in Hellfire; my attempt to tank him went fine until he suddenly hit me 4 times for ~2.5k each in the same instant, but unfortunately my combat log was bugged at the time.

Fuzz is a bear tank, Legbiter is a prot warrior, we didn't have priest with us for that raid.

4 hits in 3 seconds
![outchie](https://user-images.githubusercontent.com/1158801/52641686-b4f13b80-2ed9-11e9-9036-7415bcf2d61f.jpg)

a double hit early and a triple hit for the kill
![leg1](https://user-images.githubusercontent.com/1158801/52641699-bde20d00-2ed9-11e9-964f-e44b61acde8f.png)

a single hit, a double hit and a triple hit for the kill
![fuzz1](https://user-images.githubusercontent.com/1158801/52641702-bfabd080-2ed9-11e9-9f5d-0c0ba3750a36.png)

bearly survives the double hit, then healers don't save him in time
![fuzz2](https://user-images.githubusercontent.com/1158801/52641704-c0dcfd80-2ed9-11e9-9e9e-0f72716c6119.png)

**Current behaviour**:
Tanks getting instakilled by trash

**Expected behaviour**: 
Tanks not getting instakilled by trash

**Server Revision**: 
2783

**Comment by FuzzNFA** [comment] 2019-02-12 15:41
As a tank, can confirm this happens a lot in Karazan

**Comment by Wolffenstein** [comment] 2019-02-12 16:27
They both have "Double Attack" auras, that's intended.

**Comment by PolarCookie** [comment] 2019-02-12 17:27
What's your evidence they're even supposed to have a "Double Attack" aura?
I've checked wowwiki and wowhead comments for Chaotic Sentience, Arcane Protector and Fel Reaver; there's no mention anywhere of this mechanic, and it's quite a noticeable difference.

Or is it just that nobody cared to mention it since these mobs were never that dangerous to begin with and Netherwing is way overtuned?

*Fel Reaver*
Hitting for 1k on a clothie warlock, uploaded on the same day as patch 2.0.8,
https://www.youtube.com/watch?v=Wq1g1eaIH7M

*Chaotic Sentience*
First mention of his damage is "not particularly dangerous" on patch 2.0.12
https://wow.gamepedia.com/index.php?title=Chaotic_Sentience&direction=prev&oldid=601305
Patch 2.1.1, melee hits for 2000
https://wow.gamepedia.com/index.php?title=Chaotic_Sentience&direction=next&oldid=622219

If indeed Chaotic Sentience could one shot tanks that would be on the first edit of his wiki.

*Arcane Protector*
Patch 2.0.10 hits tank for 2500-3000
https://wow.gamepedia.com/index.php?title=Arcane_Protector&direction=next&oldid=562511
Patch 2.0.12 hits well geared tank for 3000-4000
https://wow.gamepedia.com/index.php?title=Arcane_Protector&direction=next&oldid=575223

Naxx vs outland greens geared tank difference maybe, still no warning that he'll either one shot or double hit the tank.

**Comment by Wolffenstein** [comment] 2019-02-12 20:38
Double Attack comes from sniffs, the damage may be a bit overtuned.

**Comment by FuzzNFA** [comment] 2019-02-12 21:13
I don't think that tanks dying in one second is working as intended tho. So there is an issue somewhere.

**Comment by PolarCookie** [comment] 2019-02-13 06:09
@Wolffenstein show the sniffs, both of Double Attack aura and undisputed proof that these mobs should hit for 4-5k on a tank.

To summaries the situation:
**Wolffenstein**:  Certain trash mobs should have a higher damage potential than any of the bosses in the same raid, causing instant tank death.
**PolarCookie**: If that was true, there would be comments screaming bloody murder about it somewhere.
There are no such comments to be found.
**Wolffenstein**: 
![source-s-dude-trust-me-3924292](https://user-images.githubusercontent.com/1158801/52690271-65ecea00-2f5d-11e9-876c-0b582bf94fce.png)

**Comment by GosuNFA** [comment] 2019-02-13 20:18
https://clips.twitch.tv/CharmingIntelligentCaribouDeIlluminati  

@Wolffenstein  So how is this explained then ?

**Comment by Easyfraggy** [comment] 2019-02-13 22:16
Please understand that you wont find a single video or wowhead comment about the first versions of Karazhan, Gruul, Mag, SSC or TK because they were changed - sometimes live within the first day/days of people attempting them there are maybe 100 people in the world who actually attempted these version on retail. 

The burden of proof is on you if you want something changed. Sniffs are accurate to 99% degree the only thing that can cause them to be wrong is when something was changed by blizzard before the sniffs were done - for example if sniff is from wotlk and blizzard removed an ability from a mob before then the sniff won't have that ability in the sniff. Blizzard adding double attack to mobs in karazhan during later expansions is very very unlikely.

I don't know about the Negaton Warp-Master from the clip above only wolf knows.

**Comment by PolarCookie** [comment] 2019-02-14 06:10
@Easyfraggy in your first paragraph you're admitting that there's zero evidence to be found that any of these mobs should have a double hit ability.
In your second paragraph you tell me to go find evidence that these mobs should not have a double hit ability, which you just admitted doesn't exist, ignoring the on-patch-day 2.0.8 video (assuming it was uploaded on the same day as recording) I linked. At the same time claiming you possess sniffs proving they should.
The burden of proof is on you guys, show the sniffs or at least give the spell id.

**Comment by FuzzNFA** [comment] 2019-02-14 07:50
The way burden of proof works is that the person that makes the claim should provide value judgements or concrete evidence.
For example: Full preraid bis tank with even some kara gear with blue gems, enchants and LW armor additions should not be one shot within a space of a GCD by a trash mob in entry level raid.
This is a value statement since it goes beyond proof of videos from retail TBC and just states the fact that a mob that cannot be CCed, slowed, kited and therefor needs to be tanked must be tank-able. Anything other than that is just silly and beyond the pale to talk about.

Second example: When we experience windfury like attack on multiple mobs in both raids, outdoor content and dungeons, some of them we started catching on film or have battle logs. Heck, it's the usual talking point in pug 5 man runs where people joke about shamans not using WF totem cause they affect the enemy. Then Leg aka PolarCookie posts videos and comments or pointed to the lack of any comment about it and the reply is "it's sniffs, we know, just trust us".

Key issues with the third example, which is "it's sniffs, we know, just trust us" is that it's a claim without any backing and with both video and value evidence against the way it ends up working in the game. This baseless approach to dismissing issues or not disclosing the research **discourages and disincentivizes ** people playing the game in worse that then when it was at the end of beta to report and help out.

Besides, we're not in 2.0.3 raid and world environment. Just look at this: https://github.com/Atlantiss/NetherwingBugtracker/issues/4813

If anything within 2.0.x goes like the portal to Aran amongst others things, then videos from any period during 2.0.x should be valid proof.

**Comment by Easyfraggy** [comment] 2019-02-14 07:57
> Why did you add `Status: Need Research`? I thought you had sniffs.

Because like FuzzNFA says above theres a lot of valid points from players about either the damage or multiple hit mechanics being faulty. However we need more data to change something like this that has solid sources on our side - even if we can't share that information publicly atm. 

It's up to wolf if he wants to share things from sniffs publicly - Please understand that data like this is stuff other projects would love to get their hands on.

**Comment by FuzzNFA** [comment] 2019-02-14 08:35
That approach leaves people that want to help the project by reporting these things in the dark on what is enough. Down that path we'll find only frustration and disappointment. **I don't want to have to struggle to help a server that I play on.** Besides, server is in a worse state now then what it was at the end of beta and you guys were a lot more receptive about video evidence then so how about we go back to that mindset.

Full pre-raid bis tanks getting killed within a GCD by trash in raid or Fel Reaver in HFP or or trash in a normal dungeon is obviously something that shouldn't happen.
I hope that is enough to at least patch up the issue for the time being so that people don't have to endure a **detrimental** bug. Rather would have it undertuned within reason then overtuned outside of what's doable without praying to RNG.

I am looking over the huge post made by Evolve on batching and I would REALLY REALLY REALLY like to see **same standard for proof** being used for all research.

Thanks for the tags tho. Just a question in regards to them - Who's to do that extra research? Us, players, people that don't know what's valid and what point we can use before it's dismissed without explanation that dignifies the work being put into the research and bug hunting or is the research on the NW team?

**Comment by Easyfraggy** [comment] 2019-02-14 09:18
For all intents and purposes consider it 2.0.3 - Wolf made a judgement call to not remove the teleport in this instance you can agree or disagree with that choice but if that's the only example of things in PvE not being 2.0.3 your case is really weak. 

The research needed tag is just a general tag that means if anyone has more info on the subject they should add it. I will research it later myself aswell. 

The bottleneck is wolf's time even if he is the most qualified to look into something it's not always possible because he has thousands of things to fix. So any help we can give him before he gets to this issue helps speed up the process - that's basicly what the Need Research tag means.

**Comment by FuzzNFA** [comment] 2019-02-14 12:42
@Easyfraggy 2.0.3 didn't have specialization change quests as well. That was 2.1.
How many instances of custom changes should I list so that we can agree we're not on 2.0.3?

Also thank you for the clarification. There still persists an issue of research being discouraged like here where Leg posted videos and links to posts or lack of comments and got ignored. Hopefully we'll get a less dismissive and more constructive reply in the future :^)

To get back to the topic, yeah, people are still getting instagibbed within a GCD, so healing it isn't possible.

**Comment by FuzzNFA** [comment] 2019-02-16 22:45
@Wolffenstein @Easyfraggy https://clips.twitch.tv/SarcasticLovelyMarrowThunBeast

@PolarCookie has the screenshot in full if its needed, I just took out my death
![tripple hit arcane cunt in kara](https://user-images.githubusercontent.com/47496491/52906055-d25d3700-3244-11e9-91aa-96ee12ff4050.png)

Can we get this fixed? I think we provided enough proof of what's going on. I am at 20k hp in raids and still I am getting rekt like this.

**Comment by PolarCookie** [comment] 2019-02-16 23:08
Fuzz took 20 359 damage in one instant, as a 20k hp fully buffed (he had fortitude, kinds and commanding at the time) feral tank. 26k+ is entry level WotLK tank hp, this is getting ridiculus.
We can go back and forth about whether the double hit aura should be in-game or not, but at least disable it until the triple+ hits are fixed.

Please be open to the idea that whatever sniffs you may have are not "prenerf" but a genuine mistake on Blizzards part. which they quickly corrected before it became well known, as the mechanic is completely antithetical to the entire WoW combat model.

**Comment by Mikik3jr** [comment] 2019-02-16 23:21
Fuzz had 20k+ HP fully buffed without food buff.

**Comment by Wolffenstein** [comment] 2019-02-17 01:18
Damage reduced in rev 2805.

**Comment by FuzzNFA** [comment] 2019-02-17 07:33
Thank you so much for the quick hotfix, Wolf.

It is really great to see that while the issue isn't fixed, the **detrimental** bug was been made trivial until the real issue is fixed.

The core issue of multiple hits still will persist on these mobs and on other mobs like Fel Reaver and plenty more. I would also like to point out that while the mysterious sniffs that are to precious to be shown to the plebeian public might be supporting the idea of **double** hits, I was hit **three** time. If my math serves me right, 2=/=3, even 3>2. Unless some new augury reveal that triple hit aura is blizzlike.
In that case I'll hunt the quadruple hit issue and get it on camera.

Again, thank you for the swift hotfix and one last question. We're going to go and grind our face against Prince today, a mob that keeps triple hitting without the parry being triggered and deleted T5 geared tanks within GCD. Should we make a new github issue thread or continue here and make it reopened since it is the same issue.

Much appreciated,
Fuzz

**Comment by PolarCookie** [comment] 2019-02-17 08:10
```
[2805][DB/Karazhan] Damage Adjustments:

[Karazhan]:
- Reduced melee damage dealt by Chaotic Sentience
- Reduced melee damage dealt by Arcane Protector
```
@Wolffenstein, what about Fel Reaver, Negaton Warp-Master and any other mobs we haven't noticed yet?
This is a very disappointing and unsatisfactory fix.
Either people are going to fight these thinking they're trivially undertuned or they're going to notice the double/triple hits and assume it's bugged server, either way demotivating them to invest any more time into a low quality server.
The damage wasn't the issue, you could even have buffed them 1k, just drop the double hits.
People are already leaving the server because of many issues in Karazhan, especially bad optics issues like this!

**Comment by mgoatoce** [comment] 2019-02-17 12:17
Prince Malchezaar also performing triple-hit at the same time as thrash. Resulting in guarenteed insta-death of tank after he's taken a couple of sunders.
No parries or anything.

**Comment by Drayo** [comment] 2019-03-19 10:40
I think this thread is still very relevant.

Every other TK trash pull becomes a shitshow for us because the tank gets tripple hits from random mobs.

I noticed this at Crystalcore Devastators, Sentinels, the big Hawks in Al'ars room and lot's of mobs in heroics.
Either all these mobs have Thresh/Double Hit Auras or there is some problem with auto attacks, especially because it seems like it happens very often after a cast. 
Crystalcore Devastators regularly one-shot a full T5 tank (even with arcane resistance gear after they cast.

https://cdn.discordapp.com/attachments/482540666052935701/556958605698400340/unknown.png

Here you can see our Tank get hit for 45 THOUSAND damage in one hit, even stacked with arcane resistance it is a straight up one-shot.

https://cdn.discordapp.com/attachments/482540666052935701/556957690585153546/unknown.png

Similar issue with the Phoenix Hawks.

It would be nice if this can be looked at again.

**Comment by Easyfraggy** [comment] 2019-03-20 06:53
![image](https://user-images.githubusercontent.com/36134067/54664678-38a7d480-4ae5-11e9-8cb5-5913e67d8dcb.png)

Aswell.

**Comment by FuzzNFA** [comment] 2019-03-20 12:42
L M O A

**Comment by 5f3759** [comment] 2019-03-25 06:47
![image](https://user-images.githubusercontent.com/43552280/54900037-1db4d600-4ed2-11e9-8555-d0e75ed55fc2.png)
Any update on this?
It makes TK trash a complete rng fest.

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment] 2019-03-26 17:20
I can absolutely confirm this happening consistently with Negatron Warp-Masters in Arcatraz, I was hit by one 4 times in the same milisecond.

In all of these cases brought up above, the mob's base melee damage is not the problem, but the fact that they can randomly oneshot players with nothing to be done about it.

**Comment by Mikik3jr** [comment] 2019-03-30 16:26
I am thinking the issue is MAYBE simillar what the Felguards are doing in Shadow Labs. If tank loses aggro the felguard can charge and then instant Uppercat+Mortal Strike+Attack the target. All these 3 in the same momentum. Like the have 0 global cooldown.

MAYBE something same happens here too.

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment] 2019-03-30 16:28
Negative, there are videos and combat logs above that show tanks not losing aggro and getting hit by simultaneous normal attacks.

**Comment by Drayo** [comment] 2019-04-30 12:17
I am here to give a status update: Reducing their melee damage no longer proves effective, in their anger of being nerfed, they have simply upped their count of multiple hits.

They have become too powerful and can no longer be stopped by halfhearted measures.

![buttfuck](https://user-images.githubusercontent.com/23145811/56960838-62c3cc00-6b52-11e9-9f24-affb7ee9e320.png)

In light of this, I propose a highscore list, show me what you got!

**Comment by rychersky** [comment] 2019-05-02 02:34
![image](https://user-images.githubusercontent.com/45608488/57054223-6c335e00-6c50-11e9-86ac-71148c0e54bd.png)

How the fuck is in anyway intended? No one gives a shit what your sniffs say; this is not fun gameplay.

**Comment by Wolffenstein** [comment] 2019-05-16 16:06
Fixed in rev 2953.

**Closed by Wolffenstein** 2019-05-16 16:06 UTC
Labels: - Core Mechanic

**Comment by PolarCookie** [comment] 2019-05-19 18:05
![WoWScrnShot_051919_200146](https://user-images.githubusercontent.com/1158801/57986149-6d96c000-7a71-11e9-99d5-119781f0ca53.jpg)
I win, or is it cheating that 1 hit wasn't a melee attack?
