### ISSUE TITLE
Minimap location for far away group members not always accurate

### ISSUE THREAD

**Issue by Shakeandbake** [Atlantiss/NetherwingBugtracker#246] opened 2018-09-23 18:16 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Minimap showing a group member location did not match where player actually was. When I approached where party member actually was, the minimap location was updated correctly. The same occurred when the player died. It did not update their correct spirit minimap location until they had resurrected.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment] 2018-09-23 18:40
It was already reported.

**Comment by wtRCH** [comment] 2018-09-23 18:41
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/91

**Closed by wtRCH** 2018-09-23 18:41 UTC
