### ISSUE TITLE
[Core][Warsong Gulch] LoS issues

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5188] opened 2019-02-24 13:04 UTC
**Description**: https://gfycat.com/WetGlossyDarklingbeetle I am fairly certain that this wall shouldn't block LoS

**Current behaviour**:

**Expected behaviour**: Shouldn't block LoS

**Server Revision**: 2771

**Comment by Godmatik** [comment] 2024-07-02 18:11
Broken image link.
Have heard no LoS complaints about WSG this past year on Netherwing, so likely whatever it is, working as intended.

Closing

**Closed by Godmatik** 2024-07-02 18:11 UTC
Labels: Status: Need Research, PvP: Battleground & Arenas
