### ISSUE TITLE
Quest not giving Imperial Plate Bracers

### ISSUE THREAD

**Issue by Ikatsukun** [Atlantiss/NetherwingBugtracker#6780] opened 2020-03-22 12:13 UTC
Description: I completed a quest from Derotain Mudsipper in Gadgetzan, says in yellow text I should have recieved Plans: Imperial Plate Bracers but I never got the plans, breaking my ability to level blacksmithing.

**Current behaviour**: Not receiving said plans from a quest

**Expected behaviour**: should be able to get Plans: Imperial Bracers from the quest

![image](https://user-images.githubusercontent.com/62504722/77249057-da08bf80-6c3e-11ea-840c-1738cca9b829.png)

**Server Revision**:  3315

**Comment by Evolvee** [comment] 2020-03-22 14:25
check your blacksmithing skill tab... it will be listed there

**Comment by DaedalusMachina007** [comment] 2020-03-24 04:17
Can confirm the entire Imperial Plate set is 'bind on pickup' recipes so whether it is a physical recipe or directly learned, the result is the same.

**Comment by Evolvee** [comment] 2020-03-24 10:03
so can i close this?
can someone provide classic video where its shown whether its a learned spell(spellbook/bs) or an actual recipe?

**Comment by DaedalusMachina007** [comment] 2020-03-30 22:41
@Evolvee took me a minute to find via 'WoWhead Classic' but ok.

https://classic.wowhead.com/item=12688/plans-imperial-plate-belt
https://classic.wowhead.com/item=12700/plans-imperial-plate-boots
https://classic.wowhead.com/item=12690/plans-imperial-plate-bracers
https://classic.wowhead.com/item=12705/plans-imperial-plate-chest
https://classic.wowhead.com/item=12701/plans-imperial-plate-helm
https://classic.wowhead.com/item=12715/plans-imperial-plate-leggings
https://classic.wowhead.com/item=12687/plans-imperial-plate-shoulders

All of these are physical plans/recipes that are given to the player to then learn.  They are all 'bind on pickup' recipes with the corresponding item numbers you can see above.

If you want a video, feel free to search on YT because all I could find are 'transmog' videos (aka modern wow) and random clickbait trash about 'op set bonuses' without any videos showing the actual obtaining of said plans.

But if wowhead links aren't enough then just leave it alone.  Long as we learn it (via recipe or directly) it is fine.

**Comment by Evolvee** [comment] 2020-03-31 17:55
I completed Imperial Plate Bracers and it gave me the recipe just fine.

![image](https://user-images.githubusercontent.com/1942409/78058948-5dd25280-7389-11ea-9bef-ee5a89eed21a.png)

you must have received it as well

what i can think of is a core bug, where the recipe would be appear in your bag if your bags were full at the time of completing the quest... would need to be tested

as for this bug, closing this, as i cant reproduce it

**Closed by Evolvee** 2020-03-31 17:55 UTC
Labels: Status: Need Research
