### ISSUE TITLE
Guardians of the Altar - Ranshalla not moving

### ISSUE THREAD

**Issue by addi011** [Atlantiss/NetherwingBugtracker#8371] opened 2023-04-23 08:39 UTC
[//]: # (https://www.wowhead.com/tbc/quest=4901/guardians-of-the-altar)
[//]: # ([Quest][Winterspring] Guardians of the Altar)
[//]: # ([NPC] Ranshalla)
[//]: # (Revision: 3758)

**Description**:  For the quest "Guardians of the Altar", you need to protect the NPC "Ranshalla" while collecting differenty crystals. Unfortunately, she does not seem to be able to collect the crystals, so the quest cannot be completed.

**Current behaviour**: Escort quest can be started until first crystal, but she cannot finish her spell to collect the crystal, it seems.

**Expected behaviour**:  Ranshalla should finalize her spell and then continue moving to the next crystal, so the quest can be completed.

**Server Revision**:  3758

**Comment by Godmatik** [comment] 2023-04-23 13:19
Did you click the torch as she instructed?

**Comment by addi011** [comment] 2023-04-23 13:33
If you mean the torch in the specific cave (and not another one in the inventory), it was not clickable for me... or I messed up completely

**Comment by Godmatik** [comment] 2023-04-23 14:44
It was clickable for me when I did the quest, maybe close game and delete cache folder, see if it helps. 

Because she is supposed to continue once you click the torch (she says for you to do so as well)

**Comment by Godmatik** [comment] 2024-07-01 19:39
Can't reproduce and have not heard of anyone else having this issue - closing

**Closed as completed by Godmatik** 2024-07-01 19:39 UTC
