### ISSUE TITLE
([Spell][Shaman] Earth Shock) Interrupt resist chance vs. ([NPC]Druid of The Fang) in Wailing Caverns)

### ISSUE THREAD

**Issue by thesmasher** [Atlantiss/NetherwingBugtracker#3958] opened 2019-01-09 02:26 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: While I didn't record or keep a data set, I was a lvl 19-21 shaman using [Spell][Shaman]Earth Shock to interrupt [NPC]Druid of The Fang in wailing caverns and the resist chance seemed high to me. This is mostly likely due to the [NPC]Druid of The Fang having nature resistance that may be tuned high.

**Current behaviour**: Resisted earth shock most of the time. At lvl 19 almost every earth shock was resisted, interrupting via earth shock unreliable.

**Expected behaviour**: Resist earth shock maybe 10-30% of the time.

**Server Revision**: I don't know, reduce the druid's nature resistance? Maybe I don't remember this correctly but I did play shaman on felmyst. Thank you, all the best.

**Comment by wtRCH** [comment] 2019-01-09 07:47
@aresbrutus

**Comment by Godmatik** [comment] 2024-07-05 00:47
![rtytryrty](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/54c3d8af-4e8c-4c57-965f-ea252fbe81f6)

Not a bug
Closing

**Closed by Godmatik** 2024-07-05 00:47 UTC
Labels: Dungeon, NPC, Status: Need Research
