### ISSUE TITLE
Slice and Dice invokes combat sometimes

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8486] opened 2023-06-13 10:04 UTC
Revision: 3794

Description:
Currently on Netherwing-Stormforge, Slice and Dice ability gets rogue into Combat.

Current behavior:
Currently on Netherwing-Stormforge, Slice and Dice ability gets rogue into Combat. Please note this happens sometimes, and some people says it refers to combat bug on this server that also happens sometimes.

Expected behavior:
Slice and Dice should NOT invoke Combat. A rogue should be able to Sap target, cancel stealth, pop Slice and Dice on target(if there are points on target), and then Stealth into next opener ability.
Side note: This has nothing to do with Slice and Dice putting Rogue out of Stealth, that's working as it should.

Peace

**Comment by Wolffenstein** [comment] 2023-06-13 17:25
Can you provide a video of that happening or anything that would help me reproduce this issue?

**Comment by sasadubi** [comment] 2023-06-13 17:43
Hey Wolf,

Let me see what I can do.
Need to check my OBS program and record some of these situations.

Thanks

**Comment by Wolffenstein** [comment] 2023-06-17 14:41
Can't reproduce this bug, would need more information and a video.

**Comment by dedestus** [comment] 2023-06-17 16:32
unable to connect to ptr at the moment but i can confirm this bug and it is completely rng based if it affects you or not and i have only experienced it in a pvp environment. i spammed slice and dice multiple times over a timespan of 5 minutes and sometimes slice and dice put me in combat multiple times in a row but sometimes it did not. if you cast it while not in combat in a pvp encounter you will eventually notice it happening but i have no idea what exactly causes it.

**Comment by dedestus** [comment] 2024-01-21 21:39
any update on this? still broken / noticeable during arena games

**Comment by Godmatik** [comment] 2024-01-28 04:30
As stated previously, a video showing this is going to be necessary. Or precise steps are required in order to reproduce the bug for him to fix it.

**Comment by dedestus** [comment] 2024-02-04 13:30
just tested again on the ptr, with 3/3 ruthlessness specced (60% chance to gain a combo point after using a finisher) my character gets put into combat state everytime the ruthlessness talent procc occurs.
after going 0/3 ruthlessness i did not experience any issue with snd and combat state again, can upload video soon.

**Comment by Wolffenstein** [comment] 2024-02-04 16:03
Fixed in rev 3965.

**Closed as completed by Wolffenstein** 2024-02-04 16:03 UTC
