### ISSUE TITLE
Thunder clap, reduce haste effect (re-open https://github.com/Atlantiss/NetherwingBugtracker/issues/8918)

### ISSUE THREAD

**Issue by Xykyta1** [Atlantiss/NetherwingBugtracker#9020] opened 2024-04-01 11:19 UTC
[//]: # https://www.wowhead.com/tbc/spell=25264/thunder-clap

**Description**: does not slow melee haste at all

**Current behaviour**: 
doesnt slow with and without talent https://www.wowhead.com/tbc/spell=12666/improved-thunder-clap at all.
My tests. 120 secs of fighting with mob https://www.wowhead.com/tbc/npc=20748/thunderlord-dire-wolf without parry haste effect for mob (I didn't attack him): 1) without thunder clap. 2) with 10% thuner clap debuff. 3) 20% thunder clap debuff, 
Look at red arrow. its shows the number of received hits. I dont know how to change language for addon, so "Попадания: 49" = "Hits: 49". Ok? Ok. "Hits" is the total number of successful attacks + avoided (dodge, parry, miss) + crits by mob.

49 attacks without thunder clap:
![no tc](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/176a2c94-40d1-4edd-acba-e1029a0e79f7)

49 attacks with 10% thunder clap:
![tc 10%](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/0ec44d21-51ed-492f-9ab3-966758f9b814)

49 attacks with 20% thunder clap:
![tc20%](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/96168626-3e80-4bbe-aa31-5232f8651f1c)

**Expected behaviour**: should reduce melee haste by 10% and with talent https://www.wowhead.com/tbc/spell=12666/improved-thunder-clap by 20%.
For example:
Mob`s attack speed ~2.4 or 1 hit every 2.4 secs. With 10% debuff should be 2.4 * 1.1=2.64 or total attacks in 120 secs 120/2.64=45/46. With 20% debuff should be 2.4 * 1.2=2.88 or total attacks in 120 secs 120/2.88=41/42

**Server Revision**: 3980

**Comment by Xykyta1** [comment] 2024-04-01 14:26
UPD. A few hours later i tested again. And it worked... for a while on low lvl mobs (tested on mobs in dungeon Stockades). I changed specs and talents few times and a little later it stopped working again and still doesnt work on high lvl mobs. 

---

UPD.2 Tested in pvp - it works correctly. my opponent told me that his speed was 2.4 and 2,8 with TC`s debuff

---

UPD.3 I came back to https://www.wowhead.com/tbc/npc=20748/thunderlord-dire-wolf and tested again
![again](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/7db45c81-c7b1-4646-992a-cb166d354049)
49 hits again. doesn't work against some mobs?

---

UPD.4 15 mins later, new test on mob https://www.wowhead.com/tbc/npc=19995/bladespire-brute. Again haste debuff doesnt work.
Without TC, 41 hits
![att2 wo debuff](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/6327eab7-50b7-44c8-aa3b-14ee1a47f6fc)
WIth TC20%, 40 hits (a small margin of error) 
![att2 tc20%](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/cdfbe980-9c00-4178-af26-970ee51baf17)

---
UPD.5 Ive unlearned talents for both spec. New test. Fight with mob https://www.wowhead.com/tbc/npc=20671/ripfang-lynx, 60 secs. Haste debuff doesnt work.
Without debuff 33 hits
![att3 wo debuff](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/16ef037f-b6dc-48d5-8d96-a065763c27ff)

With 20% debuff 34 hits
![att3 20% debuff](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/02018369-1aab-42bd-a39d-681c72c1392d)

---

UPD.6 New day, new test. Ive learned improved thunder clap on both specs. 60 secs fight with mob https://www.wowhead.com/tbc/npc=16863/deranged-helboar
no debuff 27 hits 
![att4 no debuff](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/a68e3690-30a5-4a7c-a07e-0acc0b4b1641)
20% debuff 27 hits
![att4 20% debuff](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/49ffd888-4588-4f92-9bf4-e5bea2c1dc64)

Maybe it doesnt work for warrior female dwarfs?)

**Comment by Godmatik** [comment] 2024-09-12 14:57
Unable to reproduce - it's always consistent for me.

Any outstanding issues may have been fixed with the recent aura updates.

**Closed as completed by Godmatik** 2024-09-12 14:57 UTC
Labels: - Core Mechanic
