### ISSUE TITLE
[spell][mage] Arcane missiles

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#84] opened 2018-09-23 00:00 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://streamable.com/0s0pa
**Current behaviour**:
https://streamable.com/0s0pa
**Expected behaviour**: 
not miss it lasts tick
**Server Revision**: 
idk, 5th restart?

**Comment by Kentamentiu** [comment] 2018-09-23 00:05
Description: Describe the problem

Due to slight delay on how the server processes spells, Arcane Missiles often doesn't cast the last bolt of the channel.

Current behaviour: Arcane Missles channels as per usual, but the last bolt doesn't fire off because of the delay of firing, while the channel goes without delay

Expected behaviour: It should fire all bolts all the time, every 1 second

Steps to reproduce the problem:

target a mob
cast Arcane Missiles
Count the bolts
Revision: Current server version (you can see current server revision by typing ".server info" command in the game chat)
203.

**Comment by Ceago** [comment] 2018-09-28 02:42
Also seeing this behavior as of 9/27.

**Comment by Restaf** [comment] 2018-09-30 07:44
still often when you have to fire the last rocket, writes interrupted and does not shoot
rev. 2086

**Comment by Wolffenstein** [comment] 2018-10-23 16:03
Fixed in rev 2201.

**Closed by Wolffenstein** 2018-10-23 16:03 UTC
Labels: Class: Mage, Spell
