### ISSUE TITLE
Marshfang Ripper mana

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7412] opened 2020-08-19 00:24 UTC
Marshfang Rippers spawn with 100% mana.

They are supposed to spawn with an empty mana bar, use mana drain on you, and then arcane explosion when they have enough mana.

https://www.wowhead.com/npc=18130/marshfang-ripper#comments

**Comment by Tereneckla** [comment] 2020-08-19 06:33
Duplicate of #2604

**Closed by Tereneckla** 2020-08-19 06:33 UTC
