### ISSUE TITLE
Quest "Fire at Will!" bugged

### ISSUE THREAD

**Issue by kalblake11** [Atlantiss/NetherwingBugtracker#7197] opened 2020-07-20 23:42 UTC
**Description**:  The Quest "Fire at Will!" in Blades Edge Mountains is not working correctly.

**Current behaviour**: After you use the Item u are not able to attack anything. Also the "4" Ability has no cooldown and the "5" Ability is not working.

**Expected behaviour**:  You should be able to use your "4" ability to attack the Portal on a cooldown and kill the waves of mobs coming out of it.

**Comment by Tereneckla** [comment] 2020-07-21 05:21
Duplicate of #6534

**Closed by Tereneckla** 2020-07-21 05:21 UTC
