### ISSUE TITLE
[Item] Romulo's Poison Vial

### ISSUE THREAD

**Issue by kubawww7** [Atlantiss/NetherwingBugtracker#3403] opened 2018-12-13 12:54 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: "Romulo's Poison Vial" poison doesn't work by attacking from a distance

**Current behaviour**: Poison doesn't working on a distance

**Expected behaviour**: Poison should activate by shooting from a distance

**Server Revision**:

**Comment by Tenoutoften** [comment] 2018-12-13 13:11
As seen on [Thootbot](http://web.archive.org/web/20070316010533/http://www.thottbot.com:80/i28579)
![](https://i.gyazo.com/502a55bfc2e87696bb8745e8b42fc3a2.png)

---

[[Spell]Romeo's Posion#34586](http://web.archive.org/web/20070317135522/http://www.thottbot.com:80/?sp=34586)
![](https://i.gyazo.com/f8e7a46a931068d304a06ca044e31aa3.png)

---

[[Spell]Romulo's Poison#34587](http://web.archive.org/web/20080519222616/http://thottbot.com:80/s34587)

**Comment by Jacksn5** [comment] 2018-12-13 13:14
Can't reproduce, procs on both Hunter melee and ranged attacks, even procs on Warrior Throws.

![image](https://user-images.githubusercontent.com/43507549/49940927-5e6b7f00-fee1-11e8-8cfb-e81f557ba9b9.png)

**Comment by Neophrone** [comment] 2018-12-14 12:55
Screenshots of thottbot shows that proc range should be 20yards, so **this is not a bug**, isn't it?
Poison can't stay on u'r arrow if u'r arrow flying the long distance - Logically. =)

**Comment by Wolffenstein** [comment] 2018-12-14 21:09
Fixed in rev 2436.

**Closed by Wolffenstein** 2018-12-14 21:09 UTC
Labels: Item
