### ISSUE TITLE
[NPC] [Hellfire Peninsula] Blistering Rot & Blistering Oozeling

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2040] opened 2018-10-31 10:07 UTC
**Description**: Blistering Rot & Blistering Oozeling @ Pools or Aggonar

**Current behaviour**: Not leashing properly. Will stay aggro until player dies, and then corpse camp.

https://gyazo.com/0a4f34a23bf586ab4fff703436c7f1ab

**Expected behaviour**: Should leash / reset.

**Server Revision**: 2243

**Comment by ScottieDOESknow** [comment] 2018-10-31 10:11
Also to note: 

I used vanish where you see my corpse in the picture. The mobs initially dropped combat, ran over the hill to leash, but then turned around and came at me again after their stacking debuff popped me out of stealth/vanish.

**Comment by Mikik3jr** [comment] 2018-11-02 10:45
Do guys think the burning legion is the real threat? At least they are staying in their dungeons, or not moving anywhere while, these oozlings are about to dominate the whole outland!

Jokes aside, when you leave combat sometimes they run back, but instantly attack you again. The problem is after they reset they go back to their previous place where they attacked you instead of running back to their original position.

![wowscrnshot_110218_112040](https://user-images.githubusercontent.com/43505031/47910975-afc13100-de94-11e8-99e0-e3cd28fc1e01.jpg)
![wowscrnshot_110218_112053](https://user-images.githubusercontent.com/43505031/47910976-b0f25e00-de94-11e8-88f2-097e4e4086be.jpg)
![wowscrnshot_110218_112835](https://user-images.githubusercontent.com/43505031/47910988-b51e7b80-de94-11e8-94d3-9f99b3240b23.jpg)
![wowscrnshot_110218_112845](https://user-images.githubusercontent.com/43505031/47910990-b6e83f00-de94-11e8-9d43-5f94e5e9f664.jpg)
![wowscrnshot_110218_113627](https://user-images.githubusercontent.com/43505031/47910994-b8b20280-de94-11e8-89c9-1e477f22e1dc.jpg)
![wowscrnshot_110218_113642](https://user-images.githubusercontent.com/43505031/47910997-b9e32f80-de94-11e8-986e-172b2dfcfa4f.jpg)
![wowscrnshot_110218_113756](https://user-images.githubusercontent.com/43505031/47911009-c1a2d400-de94-11e8-895a-2ad6a635c118.jpg)

**Comment by Easyfraggy** [comment] 2018-11-03 01:03
We don't need more screens of this! Thanks though =)

**Comment by Evolvee** [comment] 2018-11-13 22:43
Faulty script reworked.


Todo: patrols -- Kutsal will make that

**Comment by aresbrutus** [comment] 2018-11-14 17:16
Fixed in rev `Castilla`

**Closed by aresbrutus** 2018-11-14 17:16 UTC
Labels: Misc, Movement, NPC
