### ISSUE TITLE
[Item][Priest] T5 2 pieces set bonus for holy priest not working properly

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#5731] opened 2019-05-06 11:00 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spell ID 37594

**Current behaviour**: Only refunds mana if target missing health points

**Expected behaviour**: Should refund mana if healing target was brought to full health or just overhealed by 100%
[https://www.wowhead.com/spell=37594/heal-refund#comments](url)

**Server Revision**: 2950

**Comment by Tenoutoften** [comment] 2019-05-06 17:58
Similarities with Lay on Hands and critical heals w/ Illumination
https://github.com/Atlantiss/NetherwingBugtracker/issues/4165
https://github.com/Atlantiss/NetherwingBugtracker/issues/4471

**Comment by gabbat** [comment] 2019-06-19 15:59
can confirm, still not working properly

**Comment by DarthGamer** [comment] 2019-07-03 11:58
I can also confirm this is not working as of the 3rd of June. 

I have also noticed that when multiple heals land on a target and bring them to full health we do not get the proc. In this instance my UI shows some healing and some over healing, implying I was the one to top them off. I know this could be a UI issues though as over healing, thus who topped the target, is all a guess until the wrath client and this would most likely be resolved automatically with this fix.

I of course know nothing of your codebase but assume it’s not something as simple as: 
```
if (effectiveHealingDone > 0 && targetHp == targetMaxHp)
    TriggerManaProc()
```
As this could be easily resolved. Again I know nothing on how the server core works but I was wondering if a heal lands that does 0 effective healing it does not trigger/propagate like a normal heal would and thus the set bonus does not get triggered. If you are able to resolve this issue I would love to hear what the cause was.

**Comment by DarthGamer** [comment] 2019-07-16 10:24
Hi, I hate to pester but would it be possible to know if this can't or won't be fixed. I ask as most holy priests will build their gear set around maintaining two set T5 forever but that might be sub optimal.

**Comment by Wolffenstein** [comment] 2019-07-18 23:33
![image](https://user-images.githubusercontent.com/1576644/61498811-1d7ea000-a9c5-11e9-945c-f4be1afa7e98.png)
This should be working now. Overhealing by 100% or more triggers the effect.

**Comment by DarthGamer** [comment] 2019-07-19 08:32
My hero <3

**Comment by gabbat** [comment] 2019-07-23 21:08
when will this be implemented? <3

**Comment by Kaini27** [comment] 2019-07-25 14:50
as a revision of 3085- still not implemented

**Comment by gabbat** [comment] 2019-07-31 16:58
3093 still not working

**Comment by gabbat** [comment] 2019-08-06 08:14
there are actually 2 bugs:
1. the one discussed here, not providing the procc when doing 100% overheal.
2. when any other heal lands at the same time, it will likely also not procc. On average, I'd say I get the procc two thirds of the time when I full heal our tank to 100%, but for 1/3 of my full heals (healing done + some overheal) the procc does not happen, as there is tons of other heal incoming.

**Comment by gabbat** [comment] 2019-09-01 13:18
still not fixed

**Comment by Wolffenstein** [comment] 2019-09-24 02:36
Fixed in rev 3139.

**Closed by Wolffenstein** 2019-09-24 02:36 UTC
Labels: Class: Priest, Item, Spell
