### ISSUE TITLE
[Quest][Wailing Caverns] Deviate Hides

### ISSUE THREAD

**Issue by ndnd123** [Atlantiss/NetherwingBugtracker#4987] opened 2019-02-13 10:58 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Deviate Hides is not available for Alliance players
**Current behaviour**:
Deviate Hides is not available for Alliance players
**Expected behaviour**: 
Deviate Hide can be taken by alliance players
**Server Revision**:

**Comment by Vyriam** [comment] 2019-09-08 10:47
This quest is still not obtainable by Alliance faction members, although it should be...
Patch 2.2.0

Server Revision : 3119

**Comment by danbopes** [comment] 2019-09-08 10:52
Dupe of #4882

**Closed by danbopes** 2019-09-08 10:52 UTC
Labels: Quest
