### ISSUE TITLE
Fel Flack Fire Bug

### ISSUE THREAD

**Issue by Tollkirsch** [Atlantiss/NetherwingBugtracker#6961] opened 2020-05-14 13:24 UTC
Zone= Forge Camp Wrath/Blades Edge Mountain
NPC = Legion Flak Canon (Level 71 Mechanical Elite)
 
[
**Sometime the DOT (Damage over Time) LEGIONS FLAK CANNON´S FEL FLAK FIRE will not be over Time, It will cause instant dmg witch could result in a emedialy Dead.**: 

Current behavior= (All the Dmg will be summed up and is emedialy)

Expected behaviour= (Dmg will be released Step by step over time)

PS: Not every Time, Sometimes its Ok, Summetime not

**Comment by Tereneckla** [comment] 2020-05-14 14:08
Duplicate of #6221

**Closed by Tereneckla** 2020-05-14 14:08 UTC
