### ISSUE TITLE
[NPC] Private Thorsen

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#797] opened 2018-09-28 00:22 UTC
**Description**: Private Thorsen's patrol event does not work correctly.

**Current behaviour**: Thorsen starts patrol, walks to the end of his patrol route, stands there for 10-15min, then emotes "Time for my patrol, I'll be back shortly."
![wowscrnshot_092818_120756](https://user-images.githubusercontent.com/43509267/46181121-2a3be580-c318-11e8-86ac-2ce0f366adcb.jpg) This should occur at the Rebel Camp.
He then flies/warps through the sky & terrain until he is back at the camp, and walks the patrol route again.
![wowscrnshot_092818_120808](https://user-images.githubusercontent.com/43509267/46181193-6ff8ae00-c318-11e8-86ca-b6b0a3ef19b1.jpg)
![wowscrnshot_092818_120915](https://user-images.githubusercontent.com/43509267/46181210-8868c880-c318-11e8-87ec-7d04620bc50c.jpg)
When he gets to the end of the patrol route the 2nd time,
![wowscrnshot_092818_121151](https://user-images.githubusercontent.com/43509267/46181242-b1895900-c318-11e8-8015-adefa0601dbb.jpg)
he will stand there until getting aggro from the tiger mob that spawns, and when that is dead, he resets to this postition:
![wowscrnshot_092818_121818](https://user-images.githubusercontent.com/43509267/46181266-cbc33700-c318-11e8-9df0-659cecd57abc.jpg)
Then the cycle repeats.
At no point do the Kurzen mobs spawn.

**Comment by aresbrutus** [comment] 2018-09-28 22:10
When I tested it the issue was that once he reaches his point beside the road, the event does not continue. The Kurzen mobs should spawn and saving him should yield the quest.

**Comment by The14me** [comment] 2018-12-05 06:34
Cant reproduce too.Please re-open if happen again.

**Comment by SwiftieTBC** [comment] 2018-12-20 12:58
Ontop of this if you add the Q to yourself you are unable to hand in the next step at lieutenant Doran as hes complete un-interactive aswell

**Comment by pelekon** [comment] 2019-01-03 20:02
fixed in rev 2574

**Comment by sadfx** [comment] 2019-01-25 22:07
Hasn't been fixed @pelekon

**Comment by Dimbleglim** [comment] 2019-01-31 21:31
I can't even pick up the quest from him. The exclamation mark is there, A one line dialogue appears, but that's it.

**Comment by bimbear** [comment] 2019-02-10 23:21
Still bugged, ambush part not going to happen. He is returning to the camp ignoring los after fighting with tiger. Even if Ambush part is working, he is returning to the camp in same bugged way.

**Comment by Vyriam** [comment] 2019-03-11 14:41
The event and patrol route are still bugged as of today 03/11/2019.
Server Revision : 2883

**Closed** 2019-12-23 19:51 UTC
Labels: Movement, NPC, Quest, Status: Confirmed, Status: Need Research
