### ISSUE TITLE
[Quest][Netherstorm] Teleport This! doesn't mark off

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#5926] opened 2019-06-19 09:09 UTC
**Description**:  using the rod on ironspine forgelords, use their ability to detonate the teleporter, which then goes up in flames, but the quest does not mark as objective complete

**Current behaviour**: quest not marking off

**Expected behaviour**:  using the forgelords abilities in the teleporter should mark the quest objective as complete

**Server Revision**: 3014

**Comment by Evolvee** [comment] 2019-06-19 11:57
![image](https://user-images.githubusercontent.com/1942409/59763543-19624400-929a-11e9-8776-082bf8d24b49.png)

works for me

**Comment by Evolvee** [comment] 2019-06-19 11:59
![image](https://user-images.githubusercontent.com/1942409/59763675-62b29380-929a-11e9-8055-148c2574d295.png)

**Comment by Evolvee** [comment] 2019-06-19 11:59
please try to record it on video so we can see where the problem is

**Comment by jasonbourne109** [comment] 2019-07-09 03:00
I am having this same issue. The Western and Central Teleporters work just fine. The problem only exists with the Eastern Teleporter.

**Comment by Evolvee** [comment] 2019-07-09 10:35
![image](https://user-images.githubusercontent.com/1942409/60881451-0bbf2f00-a246-11e9-9040-341c2111dbcd.png)

...
I cant reproduce this.

Record it on video please.

**Comment by DarthNekr0s** [comment] 2019-07-10 21:21
evolve, try using the other variety of forgelords to use the teleporter. the cyber rage forgelords work alright for the quest and i was able to complete it using them, however at first i tried the ironspines who have the detonate ability, but would not work for quest completion.

**Comment by Evolvee** [comment] 2019-07-11 15:33
ironspine forgelords fixed in next rev

**Closed by Evolvee** 2019-07-11 15:33 UTC
Labels: NPC, Quest
