### ISSUE TITLE
[Spell][Warrior] Piercing howl vs stealth/vanish

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4966] opened 2019-02-11 13:00 UTC
**Current behaviour**: Using piercing howl ( http://db.hellfire-tbc.com/?spell=38256 ) does not break rogue/druid's stealth/vanish

**Expected behaviour**:  Using piercing howl (same as demoralizing shout) breaks rogue/druid's stealth/vanish

**Server Revision**:  2776

**Comment by Easyfraggy** [comment] 2019-02-11 13:08
Can confirm - this was common practice to break rogues out of stealth.

**Comment by teddys** [comment] 2019-02-14 16:04
Using devour magic on a stealthed target also doesn't break stealth. I'd assume other things such as spellsteal/purge/dispel magic are the same.

**Comment by teddys** [comment] 2019-02-25 05:27
bump

**Comment by teddys** [comment] 2019-02-25 23:26
bump

**Comment by Wolffenstein** [comment] 2019-02-26 05:32
Can't reproduce: https://gfycat.com/pl/harmfulablegazelle.

**Comment by Wolffenstein** [comment] 2019-02-26 05:43
Dispels fixed in rev 2842. Need confirmation for Piercing Howl.

**Comment by teddys** [comment] 2019-03-01 03:25
> Can't reproduce: https://gfycat.com/pl/harmfulablegazelle. Dispels are bugged indeed though.

confirmed fixed for both

**Comment by Cptnlobbe** [comment] 2019-03-17 08:08
Devour magic is bugged again.. does not bring the target out of stealth.

**Comment by teddys** [comment] 2019-03-19 23:29
Same as piercing howl :S

**Comment by teddys** [comment] 2019-03-26 00:07
https://github.com/Atlantiss/NetherwingBugtracker/issues/5431

**Comment by Wolffenstein** [comment] 2019-03-26 01:02
Fixed in rev 2906.

**Closed by Wolffenstein** 2019-03-26 01:02 UTC
Labels: Class: Warrior, Spell, Status: Confirmed

**Comment by santuzzo** [comment] 2019-04-06 17:22
still broken
