### ISSUE TITLE
[Spell][Hunter] Reapplying Serpent Sting

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3353] opened 2018-12-10 02:36 UTC
**Description**:
Can't reapply Serpent Sting while Serpent Sting is still on Target.

**Current behaviour**:
Get error message "A more powerful spell is already active"

My video here: https://youtu.be/OmVDAJaQaQ4

**Expected behaviour**:
Should reapply Serpent Sting while Serpent Sting is still on Target.

**Comment by Tenoutoften** [comment] 2018-12-10 04:18
Looks like this has already been reported: https://github.com/Atlantiss/NetherwingBugtracker/issues/3191

**Comment by wtRCH** [comment] 2018-12-10 05:50
Duplicate of #3191

**Closed by wtRCH** 2018-12-10 05:50 UTC
Labels: Duplicate
