### ISSUE TITLE
[Quest][Winterspring] "The Matron Protectorate" can not be finished

### ISSUE THREAD

**Issue by MisaHack** [Atlantiss/NetherwingBugtracker#6981] opened 2020-05-17 23:00 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hi, [Quest][Winterspring] "The Matron Protectorate" can not be finished, friend Dasinde and I found Rune on the ground in Mazthoril cavern and we have quest item from Upper Blackrock Spire, but when we stand on rune it does not teleport us, so it is 100% bug,

QUEST: https://classic.wowhead.com/quest=5160/the-matron-protectorate

**Current behaviour**:
Rune is not teleporting us to NPC.

**Expected behaviour**: 
Rune has to teleport player to NPC.

**Server Revision**: 3371

Screenshot -

![WoWScrnShot_051820_001943](https://user-images.githubusercontent.com/38266502/82162152-a34bd000-98a2-11ea-882d-265858ae8db1.jpg)

**Comment by duzyizly** [comment] 2020-05-18 00:53
kinda same as https://github.com/Atlantiss/NetherwingBugtracker/issues/5873

**Comment by Tereneckla** [comment] 2020-05-18 06:32
Duplicate of #5873
As mentioned there, you can climp up the mountain in the meantime
https://www.youtube.com/watch?v=uidnaJjIzH0

**Closed by Tereneckla** 2020-05-18 06:32 UTC

**Comment by MisaHack** [comment] 2020-05-18 22:35
@duzyizly @Tereneckla - so #5873 is there for 1 year and you still did not fixed the problem?
Why is this still an issue 1 year later on this server?
It is obvious you know about it but no one wants to fix it?
