### ISSUE TITLE
[Quest][Stormwind City] The Tome of Valor

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#707] opened 2018-09-26 21:09 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When we start the quest event in Westfall 2 things are not as they supposed to be.
**Current behaviour**:
1.) The NPC called Daphne Stilwell (the girl we have to defend from bandit waves) picks up a gun but she never use it. Waves of bandits are coming but she is just standing in one place and not shooting. She is looking towards her target, but only attacks in melee when the enemy is close.
![image](https://user-images.githubusercontent.com/43505031/46109193-27d67000-c1e0-11e8-9c25-068bd7baf7d3.png)
2.) Bandits don't have any weapons. They want to fist the poor lady instead of cutting her into pieces.
**Expected behaviour**: 
This is a video that I found:
https://youtu.be/-_4saHR9ZMk?t=1m9s
On the video it can be seen that the bandits should use swords and the lady should use her gun.
**Server Revision**: 
2065

**Comment by Evolvee** [comment] 2020-02-06 18:54
![image](https://user-images.githubusercontent.com/1942409/73968722-6c1c6900-491a-11ea-851d-17b06b9e9de6.png)

**Comment by RhadigarTV** [comment] 2020-07-12 05:48
**Quest**: The quest in question is The Tome of Valor, quest#: 1651, which is given to the Paladin player by Daphne Stilwell, npc #: 6182, who is located in the southern region of Westfall. 

**Description**: Now, they'll be coming again soon, I'd wager, so get yourself ready.

I've got myself a gun in the house. I'll grab it and be ready to help you out, but for the most part, you're on your own.

I've no idea how many they'll send, but I'm sure it'll be more than the few they sent earlier.

Ask the Light for whatever blessings you can because... did you hear that? I think they're coming.

We make our stand near the house!

**Current Behavior**: Daphne Stilwell is not spawning at all for the players and is not offering the quest complete. Daphne Stilwell can be seen coming out of what appears invisibility at some parts of the zone where she's located but can not be interacted with.

**Expected Behavior**: Daphne Stilwell should be available for the players to turn in the quest and to complete the quest that she gives to the players.

**Conclusion**: This quest is not working properly and will need further investigating.

**Comment by Tereneckla** [comment] 2020-07-13 14:00
![image](https://user-images.githubusercontent.com/50233983/87313260-eaacb080-c521-11ea-8d72-a5acb5db104c.png)

**Comment by Fuzedknight** [comment] 2020-07-17 18:18
Can confirm, I see her for half a second and she's automatically despawning. Her name appears and she instantly phases out every 50 seconds.

**Comment by Magibum** [comment] 2020-07-26 14:20
is there going to be a fix?

**Comment by Wolffenstein** [comment] 2020-07-26 17:12
Fixed in rev 3487.

**Closed by Wolffenstein** 2020-07-26 17:12 UTC
Labels: - Core Mechanic, - Priority, Class: Paladin, NPC, Other, Quest, Status: Confirmed
