### ISSUE TITLE
[Quest][Arathi Highlands] Hints of a new Plague? Undead patrol combat bug

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4038] opened 2019-01-11 10:38 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This is the 2nd part of the quest when we have to kill an undead for a letter and that undead has like 4-5 bodyguards around him.

**Current behaviour**:
I pulled away only the quest mob constantly hitting him and let the other to run back. After I killed the quest mob the bodyguards aggroed/deaggroed me nonstop. I had to come back and kill them all or I stuck in combat until I die. The other bad factor is that they were spawning back during the fight, so I was in constant 4v1 which is not that easy to deal.

**Expected behaviour**: 
The combat bug and the spawn shouldn't happen imo.

**Server Revision**: 
Content patch 203

**Comment by Wookiefister** [comment] 2019-01-11 11:39
I noticed the same bug with the rare spawn alliance outrider in the barrens that drops a quest item

**Comment by Drayo** [comment] 2020-07-11 04:10
-  I reset only the guards, killed the courier. They reaggroed once, but after I killed the courier, they rearranged and continued their patrol. (It should not be possible to separate them from the courier, they should be linked)

- They (the bodyguards) do indeed respawn very quickly, around 30 seconds. makes fighting the whole group nearly impossible and seems really weird.

**Comment by Godmatik** [comment] 2024-08-25 04:04
Duplicate of this:
https://github.com/Atlantiss/NetherwingBugtracker/issues/2260

**Closed by Godmatik** 2024-08-25 04:04 UTC
Labels: Linking, NPC
