### ISSUE TITLE
Dismounting Bug

### ISSUE THREAD

**Issue by kopavgr7** [Atlantiss/NetherwingBugtracker#7746] opened 2020-11-27 17:59 UTC
**Description**: 

I reported a bug in this server about 4 months ago, a bug that when you dismount a character that has a pet (warlock,hunter) you are dismounted without any pet, making a sudden pvp conflict instaloss (unless you're a destro lock with DS, in which case no pet is involved). As you may understand this bug makes the game unplayable in any situation that you have to dismount and initiate combat. This bug may happen once every hour or once every day, it's completely random in my experience, however it's a game-breaking bug that we were assured by the devs that it was fixed. It is not. If this isn't fixed anytime soon, people are gonna be leaving soon (more people anyway...). I'm not sure about other hunters/locks, but I'm going to be quitting this server and most probably quit WoW for good, as this server was my last resort after 15 years of WoW....

**Current behaviour**:

When a character that has a pet in his possession at the moment (lock/hunter) dismount, sometimes is dismounted with no pet at all...

**Expected behaviour**: 

Does this actually need to be filled..? Pets should remain under the controller's possession... /sigh

**Server Revision**: 

3556 (patch 2.0.3)

**Comment by Wolffenstein** [comment] 2020-11-30 16:01
> This bug may happen once every hour or once every day, it's completely random in my experience, 

Which is why I can't reproduce it to fix it fully...

**Comment by Godmatik** [comment] 2024-07-07 14:16
This issue only occurred in SMV zone and was fixed last year. Have not heard of it happening again since then.

Closing.

**Closed by Godmatik** 2024-07-07 14:16 UTC
