### ISSUE TITLE
[Instance] Reentering an instance after some time causes players to enter a different instance

### ISSUE THREAD

**Issue by Moryjani** [Atlantiss/NetherwingBugtracker#5819] opened 2019-06-01 23:47 UTC
**Description**: 
When in an instance for approximately more than an hour, wiping will cause characters to enter a different instance.

**Current behaviour**:
Trying to reenter an instance after a while will cause the players to be assigned to a different instance even if there are players remaining in the 'original' version of the instance. In some cases ressurection even puts a player in a different version of the instance.

This has happened with all dungeons (e.g. Scarlet Monestary, Razorfenn Downs) but is the most egregious with longer instances such as Maraudon, Blackrock Depths.

**Expected behaviour**: 
An instance should remain intact when players have recently been inside the instance, or some players of the party are still inside the instance. 

A soft reset should only occur after 30 minutes, and only if all players leave the instance.
https://worldofwarcraft.fandom.com/et/wiki/Instance_reset

We believe the issue could be related with the existing instance timer not resetting properly when entering or leaving.

**Server Revision**: 
2976

**Comment by Evolvee** [comment] 2019-06-02 08:03
https://github.com/Atlantiss/NetherwingBugtracker/issues/5406

**Comment by jhaerik** [comment] 2019-08-14 09:33
Still happening. Lost two separate BRD instances (and several hours of my life) today because of this.
First time we wiped right after Phalanx and zoned back into different instances.
Second time was a different group. Paladin got stuck in combat after General Angerforge and could not rez. Paladin relogged to try and drop combat to rez. Zoned back into a different instance.

**Comment by danbopes** [comment] 2019-09-07 20:07
Right now: I'm trying to investigate exactly why this is happening. I'm unable to repo. Can anyone here pop on the PTR, and try to get me a reproducible case. (Could be related to a quest, or dying on a specific fight. I could not pinpoint the issue during my trials).

**Comment by danbopes** [comment] 2019-09-07 20:08
Closing this as a dupe of #5406

**Closed by danbopes** 2019-09-07 20:08 UTC
Labels: - Core Mechanic, Dungeon, Status: Confirmed
