### ISSUE TITLE
Loch Crocolisk droprate

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#404] opened 2018-09-24 18:16 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Droprate is awful - been here for 45 minutes, dinged 1 and gained 85x light leather and still havent completed quest yet.

**Current behaviour**: ^ Above - super awful droprate

**Expected behaviour**: Unsure, and I can't even be positive about this - but I assume it needs to have its droprate tweeked drastically. I might hit lvl 20 before gaining my crocolisk meat and crocolisk skin

**Server Revision**: Current revision is 2040

**Comment by Godmatik** [comment] 2018-09-24 18:54
Duplicate of #361 

Based on Allakhazam and Thottbot comments (linked in that thread), the low drop rate is intended.

**Comment by Mewmewww** [comment] 2018-09-24 19:19
thats disappointing :/

**Comment by aresbrutus** [comment] 2018-09-25 16:30
[Crocolisk Skin] `2925` has the correct drop chance but the [Crocolisk Meat] `2924` is in global loot and needs to be upped for these mobs.

https://i.imgur.com/MZmDTxp.png

**Comment by EvanEricWells** [comment] 2018-09-26 03:49
I've found the skin droprate is good/normal, but I've only seen one meat in about 40+ kills

**Comment by Vempz** [comment] 2018-10-02 05:27
I'm finding a similar issue. I've killed 48 Loch Crocolisks and received 2 Crocolisk Meat `2924`. Here is the drop rate according to a snapshot of thottbot from patch 2.4.3: https://web.archive.org/web/20080917154625/http://thottbot.com:80/i2924

It shows a ~37% drop rate from the Loch Crocolisks in Loch Modan. Hope this helps the investigation.

**Comment by aresbrutus** [comment] 2018-10-02 07:29
Yeah thanks, the issue is related to global loot and will be fixed in the future.

**Comment by Shanghi** [comment] 2018-10-10 18:33
This should be fixed in revision 2152.

**Closed by Shanghi** 2018-10-10 18:33 UTC
Labels: Loot, Quest
