### ISSUE TITLE
[Class][Rogue] Poison procs

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#3130] opened 2018-11-29 14:59 UTC
**Current behaviour**: Poisons proc comes only from abilities that deal initial damage.

**Expected behaviour**:  Cheap Shot, Garrote, Kidney Shot, Expose armor and Rupture should be able to proc poison from main hand weap.
[Cheap Shot](https://www.youtube.com/watch?v=IB7bUNWTlh4#t=4m26s)
[Cheap Shot](https://www.youtube.com/watch?v=t8iiLNszJpU&t=30)
[Cheap Shot with CL](https://www.youtube.com/watch?v=V0UvkL-mZq8#t=2m15s)
[Cheap Shot with CL](https://www.youtube.com/watch?v=V0UvkL-mZq8#t=2m58s)
[Garrote with CL](https://www.youtube.com/watch?v=V0UvkL-mZq8#t=8m34s)
[Kidney Shot](https://www.youtube.com/watch?v=yiZ7BuwoaeI&t=2m23s)
[Kidney Shot with CL](https://www.youtube.com/watch?v=V0UvkL-mZq8#t=3m0s) Hes proccing 2 poisons in 1 batch - 1 from White Hit and 1 from Kidney
[Rupture](https://www.youtube.com/watch?v=yiZ7BuwoaeI&t=1m17s)

**Server Revision**: 
2369

**Comment by ScottieDOESknow** [comment] 2018-12-01 19:55
Working as intended. Poisons ONLY proc from white hits or abilities that generate combo points. 

Instant / Wound poisons are ppm (proc per minute) based application but can be increased by class talents or by using shiv to instantly apply poison from offhand. 

Crippling / Deadly / Mind Numbing / Anesthetic poisons are static % based but can also be increased by class talents or by using shiv to instantly apply poison from offhand.

**Comment by ScottieDOESknow** [comment] 2018-12-03 22:42
Tested indeed: 18 days played on beta

Poisons proc from eviscerate? Are you sure it's not a white hit? Any evidence?

Neilyo used crippling main so he could shiv wound from offhand? Really? :thinking:

I see no evidence from the clips that proves anything claimed. There is no combat log data and when slowing down to frame, doesn't prove it's not a white hit proc.

**Comment by Dusky1** [comment] 2018-12-03 23:37
Yes from Eviscerate. If you stand 70-90° to the target you wont hit with white but you can still attack with skills - thats how i was testing it.

I feel sorry for you that you have 18days played and still couldnt properly test it.

No offence, but you have no idea about rogue and poisons. Good rogues used to use cripp on MH in duels so they would not brake Sap in 30% of openers with Garrote/Cheap Shot.

You can clearly see in 1st Video that Wound was procced by Cheap Shot. In 2nd and 3rd video you can see the procs aswell but only if you watch frame by frame.

**Comment by ScottieDOESknow** [comment] 2018-12-04 00:17
**No need to feel sorry OR for personal attacks, this is simply a discussion.** 


>Good rogues used to use cripp on MH in duels so they would not brake Sap in 30% of openers with Garrote/Cheap Shot.

Makes no sense, and even if this was true, it's still irrelevant to the original claim. 
"Poisons doesnt proc from some abilities."


>You can clearly see

Watched it many times now and I see no proof to claim, even on slowest speed.


>"Poisons ONLY proc from white hits or > direct damage < abilities that generate combo points."

That's how poison procs have always worked... otherwise they would be extremely overpowered. Lookup rogue poison theorycrafting via waybackmachine: shadowpanther, roguerogue, worldofming, roguecrap

If I remember correctly, Happyminti (world of ming) used to have a (pay to learn) TBC video that highlighted poisons proc mechanics and exactly what should and should not proc them. Used to be on AJ too. This was considered basic knowledge even before the video came out tbh.


>Also, there was LOGICAL exception for Gouge

Gouge used to proc poisons before 2.1 patch...

http://wowwiki.wikia.com/wiki/Patch_2.1.0

**Patch 2.1.0 (5/22/2007)
Gouge: This ability will no longer trigger poisons (and thus break itself).**

If you are online right now msg me on discord. We can test your theories.
@ScottieDOESknow

**Comment by Dusky1** [comment] 2018-12-04 01:34
Updated 1st post with combat log video proofs

**Comment by ScottieDOESknow** [comment] 2018-12-04 11:20
OP videos also provide evidence that poison procs function contrary to thier claim.
Just to be 100% clear what is being shown, here is a breakdown of abilities used per clip.
>only if you watch frame by frame
--------------------------------------------------------------------------------------------------

**SAME VIDEO: 'Neilyo: RIP harp'
SAME FIGHT as OP linked @ 0:40
https://youtu.be/t8iiLNszJpU?t=40**

trinket + Blind opponent Kidney Shot
Sap off Blind
Premeditaion (2cp)
Garrote + macro (stopattack / cleartarget to prevent breaking sap)
STILL NO POISON PROC/DEBUFF <<<<<<<<<<<<<<<<<<<

4cp Kidney Shot (still has Sap debuff)
Bloodlust Brooch trinket used (lust for battle)
STILL NO POISON PROC/DEBUFF <<<<<<<<<<<<<<<<<<<

MISS white hit (mainhand)
151 white hit (offhand)
607 Hemo
178 Garrotte tick
651 Hemo
915 white crit (Crippling Poison applied from mainhand)

204 white hit (offhand)
Evasion
180 white hit (offhand)
177 Garrotte tick
MISS white hit (mainhand)
Vanish opponent Blind

**SAME FIGHT - NEXT OPENER @ 1:20
https://youtu.be/t8iiLNszJpU?t=80**

Sap
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<<
520 white hit (mainhand)
162 white hit (offhand)
762 Hemo (Crippling Poison applied same time as Hemo debuff) <<<<<<<<
etc.

------------------------------------------------------------------------------------------------------

**SAME VIDEO: 'Akrios: Eviscerate Arenas Vol I' 
SAME FIGHT as OP linked @ 3:20
https://youtu.be/V0UvkL-mZq8?t=200**

185 Shiv (poison resisted - Cloak of Shadows)
MISS white hit (mainhand)
MISS white hit (offhand)
Shadowstep + Kidney Shot
271 white crit (offhand)
STILL NO POISON PROC/DEBUFF <<<<<<<<<<<<<<<<

917 Hemo (Wound Poison applied same time as Hemo debuff)
77 Wound Poison proc
550 white hit (mainhand)
Crippling Poison applied <<<<<<<<<<<<<<<<<<<<<<
201 white hit (offhand)
etc.

------------------------------------------------------------------------------------------------------

**SAME VIDEO: 'Akrios: Eviscerate Arenas Vol I' 
VERY NEXT FIGHT @ 3:33
https://youtu.be/V0UvkL-mZq8?t=213**

Cheap Shot while mage is jumping (no poison proc/debuff) <<<<<<<<<<<<
spamming Shiv (doesn't land)
ABSORB white hit (Mage Blink)
115 Deadly Throw
250 white hit
1259 Mutilate (no poison on target, lower damage) <<<<<<<<<<<<<<<<<
Crippling Poison applied from Mutilate <<<<<<<<<<<<<<<<<<<<<<<<<
etc.

**SAME FIGHT (after mage dies) @ 4:05
https://youtu.be/V0UvkL-mZq8?t=245**

Vanish opponent Rogue opener
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<<
636 white crit (mainhand)
TWO (2) SECONDS LEFT ON CHEAP SHOT (no poison proc/debuff) <<<<<<<
377 white hit (offhand)
492 white crit (Wound Poison applied from mainhand)
77 Wound Poison proc
etc.

------------------------------------------------------------------------------------------------------

**SAME VIDEO: 'Akrios: Eviscerate Arenas Vol I' 
VERY NEXT FIGHT (vs Neilyo) @ 4:23
https://youtu.be/V0UvkL-mZq8?t=263**

Shadowstep
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<<<
564 white hit (no poison proc/debuff)
Bloodlust Brooch trinket used (lust for battle)
147 white hit (no poison proc/debuff)
2 SECONDS LEFT ON CHEAP SHOT (still no poison proc/debuff) <<<<<<<<<<
Neilyo trinkets Cheap Shot and Blinds Akrios
etc.

**SAME FIGHT (after druid dies) @ 5:40
https://youtu.be/V0UvkL-mZq8?t=340**

First Aid bandage
Stealth
Cheap Shot Wariror (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<
404 white hit (no poison proc/debuff)
3 SECONDS LEFT ON CHEAP SHOT (no poison proc/debuff) <<<<<<<<<<<<<<<
killing blow

-------------------------------------------------------------------------------------------------------------

**SAME VIDEO: 'Destram - Killer Instinct II'
SAME FIGHT as OP linked @ 1:35
https://youtu.be/yiZ7BuwoaeI?t=95**

Sap
Premeditation (2cp)
Shadowstep
Garrotte (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<
Evasion
548 white hit (mainhand)
MISS (offhand)
Rupture (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<
opponent Vanish + Blind
Destram trinket + Vanish
203 Rupture tick
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<
535 white hit (Wound Poison applied from mainhand)
70 Wound Poison proc
203 Rupture tick
678 Hemo (Wound Poison still only 1x) <<<<<<<<<<<<<<<<<<<<
DODGE - Kidney Shot
MISS (offhand)
DODGE (mainhand)
203 Rupture tick
220 Deadly Throw
203 Rupture tick
203 Rupture tick
220 Deadly Throw
MISS (offhand)
DODGE - Hemo
etc.

**SAME FIGHT @ 2:15
https://youtu.be/yiZ7BuwoaeI?t=135**

1 sec on Kidney Shot
85 Gouge
Cheat Death procs
Vanish
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<
460 white hit (mainhand) 
614 Hemo
152 white hit (offhand)
175 white hit (offhand)
840 white crit (mainhand) 
Kidney Shot (OP linked this part)
157 white hit (Wound Poison applied from offhand) <<<<<<<<<<<<<<<<
71 Wound Poison
741 Hemo
932 white crit (mainhand)
191 white hit (offhand)
859 Hemo
etc.

----------------------------------------------------------------------------------------------------


**SAME VIDEO: 'Destram - Killer Instinct II'
SAME OPPONENT - NEXT FIGHT @ 2:50
https://youtu.be/yiZ7BuwoaeI?t=170**

Sap fades from both players
Stealth (tries to Cheap Shot)
opponent Shivs out of Stealth
DODGE - Gouge
Vanish
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<
DODGE (mainhand) 
@ 2:55 (frame cap) https://gyazo.com/a757d36510d434fc738bc673bc6ef087

536 Hemo (Wound Poison applied) <<<<<<<<<<<<<<<<<<<<<<<<<
71 Wound Poison proc
196 white crit (offhand)
@ 2:56 (frame cap) https://gyazo.com/245b1c0a98ee0bef2ae54e81328666bc

etc.

----------------------------------------------------------------------------------------------------


**SAME VIDEO: 'Destram - Killer Instinct II'
SAME OPPONENT - NEXT FIGHT @ 3:40
https://youtu.be/yiZ7BuwoaeI?t=220**

double Sap
opponent trinket + Vanish
Destram trinket
opponent Cheap Shot trinket (no poison proc/debuff) <<<<<<<<<<<<<
-168 white damage (no poison proc/debuff) 
**FULL DURATION CHEAP SHOT (no poison debuff/proc)**
@ 3:50 (frame clip) https://gyazo.com/14287c7e58ffe3492772668f05ba4dcf

-572 Hemo (Wound Poison applied x1)
-73 Wound Poison proc
@ 3:51 (frame cap) https://gyazo.com/d1d3d7f716c153f9e85871b944fa859f

Kidney Shot
-322 white crit (Crippling Poison applied from offhand)
-1258 Hemo
-1402 Hemo (Wound Poison applied x2) <<<<<<<<<<<<<<<<<<<<<
-73 Wound Poison proc
-188 white hit (offhand)
etc.


**SAME FIGHT @ 4:30
https://youtu.be/yiZ7BuwoaeI?t=270**

Vanish
Premeditation (2cp)
Shadowstep
Cheap Shot (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<
524 white hit (mainhand)
1603 Eviscerate (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<
163 white hit (offhand)
624 Hemo (no poison proc/debuff)
190 white hit (offhand)
MISS (mainhand)
Evasion

**Rupture (no poison proc/debuff)** <<<<<<<<<<<<<<<<<<<<<<<<<<
@ 4:34 (frame cap) https://gyazo.com/cbb65c1b8098cfd5b43fb7b0b274e58e

**STILL NO POISON DEBUFF** <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
@ 4:35 (frame cap) https://gyazo.com/056e3ff2a40fa557dd57de23a835bb63

1106 Hemo (Crippling Poison Applied)  <<<<<<<<<<<<<<<<<<<<<<
177 white hit (offhand)
@ 4:35 (frame cap) https://gyazo.com/82fbb71eacc67e01e76397d03d8067a2

etc


----------------------------------------------------------------------------------------------------


**SAME VIDEO: 'Destram - Killer Instinct II'
SAME OPPONENT as OP linked @ 5:52
https://youtu.be/yiZ7BuwoaeI?t=315**

Premeditation (2cp)
Garrotte (no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<<<
595 white crit (mainhand)

**STILL NO POISON DEBUFF** <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
@ 5:53 (frame cap) https://gyazo.com/fda381df9d752f125816ef3eb437d188

spamming Shiv 
134 Shiv (still no poison proc/debuff) <<<<<<<<<<<<<<<<<<<<<<<
99 white hit (offhand)

**STILL NO VISIBLE POISON DEBUFF** <<<<<<<<<<<<<<<<<<<<<<<<
@ 5:54 (frame cap) https://gyazo.com/21bad0ec60503cab13ce73edeacadfd5

**Crippling Poison debuff applied in next frame (miliseconds)**
@ 5:54 (frame cap) https://gyazo.com/3ae7ba0a6d812c4dc20ad6ccf13e1fc6

98 white hit (Wound Poison applied from offhand)
71 Wound Poison proc
**NO WOUND POISON DEBUFF VISIBLE** (even though showing white hit / WP hit)
@ 5:55 (frame cap) https://gyazo.com/a72d422092f638db91769e3413dd1915

**Wound Poison debuff applied in next frame (miliseconds)**
Rupture applied (but didn't proc Wound Poison, as shown in above cap)
@ 5:55 (frame cap) https://gyazo.com/52294c0385a4c5f845495c651e7ccc6e

etc.

----------------------------------------------------------------------------------------------------

**Comment by Dusky1** [comment] 2018-12-04 12:35
What are your videos? Its obvious that you will find no procs more often since it was 70%/80% for NOT proccing poison.

**Also, can you please reffer to my videos if you wanna continue this discussion?**

Posting timesnaps of no poison proc makes just no sense. Going your way I can prove almost everything but thats not normal at all..

**Comment by matthewRHill91** [comment] 2019-02-12 00:07
I'm surprised. I was under the same impression as Scottie initially, but those videos provide pretty conclusive evidence that poison should be able to proc off of CS / KS / Garrote, etc.

**Comment by Evolvee** [comment] 2020-02-01 11:56
cs doesnt proc poisons rn? wth, it was working in closed beta @Wolffenstein -.- http://tbc.internal.atlantiss.eu/showthread.php?tid=344&highlight=poison

**Comment by Wolffenstein** [comment] 2020-06-28 20:58
Fixed in rev 3412.

**Closed by Wolffenstein** 2020-06-28 20:58 UTC
Labels: - Core Mechanic, Class: Rogue, Spell

**Comment by Evolvee** [comment] 2020-06-29 17:34
its not just cs and ks btw -.- read the forum topic
