### ISSUE TITLE
Seal of Righteousness does not proc sometimes.

### ISSUE THREAD

**Issue by worugru** [Atlantiss/NetherwingBugtracker#208] opened 2018-09-23 15:31 UTC
**Description**: 
Seal of Righteousness does not proc sometimes. It should be proccing %100.
**Current behaviour**:
As seen in the combat log in the provided SS 

![wowscrnshot_092318_172302](https://user-images.githubusercontent.com/7393809/45929757-ad8abf00-bf45-11e8-98bd-007e687f1c5e.jpg)

 even tho the Seal is active, it procs sometimes but does not proc later, but then gets used by judgement
**Expected behaviour**: 
%100 chance on hit.
**Server Revision**:

**Comment by Mikik3jr** [comment] 2018-11-03 09:33
I confirm the same. It can be seen that the seal is up, but I don't do holy damage on hit. The cause of this is still unknown for me:
![wowscrnshot_110318_102545](https://user-images.githubusercontent.com/43505031/47950526-cc706e00-df53-11e8-922d-c7837a3dce83.jpg)
![wowscrnshot_110318_102644](https://user-images.githubusercontent.com/43505031/47950527-cc706e00-df53-11e8-979e-a97b8e23adbb.jpg)
![wowscrnshot_110318_103001](https://user-images.githubusercontent.com/43505031/47950528-cc706e00-df53-11e8-89d0-9d8be4ff65ad.jpg)

**Comment by Wolffenstein** [comment] 2019-02-01 10:31
Fixed in rev 2743.

**Closed by Wolffenstein** 2019-02-01 10:31 UTC
Labels: Class: Paladin, Spell
