### ISSUE TITLE
[Guildbank] Moving items between tabs causes it to appear both places

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6637] opened 2020-02-16 01:10 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When moving an item from one guild bank tab to another (through dropping it over the guild tab icon) the item appears to be at both the new and the old location. Cannot be moved from the original location, and if you move something to the slot where it was originally, it disappears (and everything is back as it should be.)
Hard to explain, but try moving an item through clicking the tab icon and see if it still appears in the old location. Should be easy to replicate as it happens all the time.

Misc. fix, and not very important, although not "as it should be" :) 
I guess there is something wrong where it only refreshes the visuals if you move an item from your bag to the bank or within a tab. No between tabs.

**Current behaviour**:
Moving an item from one guild bank tab to another causes it to appear in both places.

**Expected behaviour**: 
It should disappear from the old location.

**Server Revision**: 
3255

**Comment by The14me** [comment] 2020-02-17 06:36
Delete your cache folder and try again.And u can try it without addons.I still cant reproduce it.

**Comment by dshgrove** [comment] 2020-02-19 16:36
Deleted cache folder after closing the game.
[Reproducing it with no addons enabled](https://streamable.com/ba91h)

**Comment by The14me** [comment] 2020-07-12 10:05
That must be fixed with Guild rework.

**Comment by The14me** [comment] 2020-07-12 17:40
Rev.3478 not an issue anymore.Can be closed.

**Closed** 2020-07-12 18:11 UTC
Labels: Misc, Status: Confirmed
