### ISSUE TITLE
[Talent/Mechanic] [Warlock] Improved Shadow Bolt Applying on Full Resist

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7732] opened 2020-11-21 23:39 UTC
[//]: # ([Talent][Warlock] [Improved Shadow Bolt](https://tbcdb.com/?spell=17803)
[//]: # Video: https://www.youtube.com/watch?v=ZI0Xy0U9cN0
[//]: # Revision: 3556

**Description**: 
A fully resisted shadowbolt still procced ISB. It's like the game calculated that the Sbolt would crit, applied the debuff from ISB,  but then rolled a full resist on the spell.

Video: https://www.youtube.com/watch?v=ZI0Xy0U9cN0

**Current behaviour**:

Applies ISB on Full Resist.

**Expected behaviour**: 
Spell resisted, so the caster shouldn't have applied an on-crit only effect.

**Server Revision**: 3556

_Note: Not entirely sure if this is intended "Blizzlike" behaviour for the talent._

**Comment by Wolffenstein** [comment] 2020-11-26 21:13
I cannot reproduce even with forced crit/resists, so no idea how that could happen.

**Comment by Wolffenstein** [comment] 2020-11-26 22:14
Fixed in rev 3557.

**Closed by Wolffenstein** 2020-11-26 22:14 UTC
Labels: - PvP Priority, Class: Warlock
