### ISSUE TITLE
Xizzer Fizzbolt

### ISSUE THREAD

**Issue by Dimbleglim** [Atlantiss/NetherwingBugtracker#5331] opened 2019-03-08 11:05 UTC
Xizzer should spawn with fuill invent. Including the limited supply engineering schematics like the fused wiring and the delicate arcanite converter.

Currently He doesn't spawn with any schematics after being killed.

**Comment by Valmere** [comment] 2019-03-08 20:13
killing an NPC to force refresh it's limited stock items?

200 IQ if not a bug

**Comment by Dimbleglim** [comment] 2019-03-08 21:20
He is very much supposed to spawn with the limited supply schematics. Not sure if it ever changed but at least in vanilla, killing him was the only way to restock the fused wiring schematic.

https://www.wowhead.com/npc=11185/xizzer-fizzbolt#comments

**Comment by Tenoutoften** [comment] 2019-03-09 11:45
[Wowhead comment](https://www.wowhead.com/npc=11185/xizzer-fizzbolt#comments:id=1168153)
![](https://i.gyazo.com/4ee67623359d6f80d720fe64840055ed.png]

This is probably a core mechanic with all vendors with limited stock

**Comment by Dimbleglim** [comment] 2019-03-09 14:41
It is but currently that's not how it works.

**Comment by Oldmantrouble** [comment] 2019-03-14 20:10
@Dimbleglim If we could just google things we wouldn't be clogging the bug tracker with things that are correct. Please check [https://www.wowhead.com/item=32381/schematic-fused-wiring](url) where it clearly says "Added in patch 2.1.0.6692".  We at 2.0 . It sucks but we engineers need to wait.
![image](https://user-images.githubusercontent.com/45834722/54388192-353ac600-466b-11e9-9673-307c2dcc5613.png)

 
Please somebody close this issue

**Comment by Dimbleglim** [comment] 2019-03-16 17:19
That information is not correct. The schematic was added in 2.0.12. Even if that wasn't the case, no limited stock items spawn when the vendor spawns. Vendors should spawn with their full inventory including limited stock. This has been the case since vanilla.

**Comment by 5f3759** [comment] 2019-06-19 22:01
Shouldn't this be in game now?

**Comment by 5f3759** [comment] 2019-06-19 22:08
Nevermind, it's in. Can close this.

**Comment by danbopes** [comment] 2019-06-19 22:18
You should be able to close the issue.

**Closed** 2020-01-03 22:46 UTC
