### ISSUE TITLE
[Item]Engineering: Compact Harvester Reaper Kit - Compact Harvester is not attacking 

### ISSUE THREAD

**Issue by subi900** [Atlantiss/NetherwingBugtracker#7317] opened 2020-08-07 01:07 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Item "Compact Harvest Reaper Kit - Compact Harvest Reaper not attacking 

**Current behaviour**: The compact harvest Reaper is taking enemies in target but is not doing anything but following them. In addition it does not die after 10 Minutes.

**Expected behaviour**: The compact harvester Reaper, created by the compact harvester Reaper Kit should fight with you. It should attack enemies in reach. (Like the dog from the "Dog Whistle") It should keep up for 10 Minutes or until it dies.

**Server Revision**: 3504

**Comment by Godmatik** [comment] 2024-08-11 16:40
Was fixed last year, duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/8150

**Closed by Godmatik** 2024-08-11 16:40 UTC
Labels: Status: Need Research
