### ISSUE TITLE
Earth Shield fading on weapon switch

### ISSUE THREAD

**Issue by Bolinha221** [Atlantiss/NetherwingBugtracker#9098] opened 2024-05-14 00:34 UTC
Hello! Etherious told me to contact about a bug thats happening when we switch shields on TBC server. I'v notice that the buff Earth Shield is fading when we switch shields or off hands. That should happen since we can use Earth Shield on non shield users.

Also can check the 6:08 time on the TBC Classic footage that that doesnt happen when he put shield on and then switch back to 2hand.

https://www.youtube.com/watch?v=ifcDdY58XPY

Hope that helps to solve the prob.

Regards,

Oxfort

**Comment by Wolffenstein** [comment] 2024-05-14 13:44
Can you record it happening? I can't reproduce this issue. Also which weapons are you using? They might be the culprit

**Comment by Bolinha221** [comment] 2024-05-23 20:21
https://files.fm/u/akf9yf2p4m

Em ter., 14 de mai. de 2024 às 10:44, Wolfenstein ***@***.***>
escreveu:

**Comment by Godmatik** [comment] 2024-07-02 13:30
Also can not reproduce

**Comment by Godmatik** [comment] 2024-07-09 16:15
No further information and still can not reproduce.

Closing.

**Closed as completed by Godmatik** 2024-07-09 16:15 UTC
