### ISSUE TITLE
[Spell] [Shaman] [Windfury Weapon]

### ISSUE THREAD

**Issue by Suptski** [Atlantiss/NetherwingBugtracker#5580] opened 2019-04-06 20:27 UTC

**Comment by wtRCH** [comment] 2019-05-17 13:43
Description: The issue with Windfury Weapon frequently granting one extra attack instead of the intended two extra attacks persists even though the issue has been marked as resolved. This has been on-going for months but I didn't report it because I thought it might only have been a display bug but after more extensive testing and looking at combat log I'm now 100 % sure it works incorrectly.

Current behaviour: Windfury Weapon all too often only grants one extra attack instead of two.

Expected behaviour: Windfury Weapon should always provide two extra attacks.
WoWScrnShot_040619_212418

Server Revision: 2930

**Comment by Lariari** [comment] 2019-06-14 19:20
Has anyone looked any further into this? Any updates?

**Comment by Easyfraggy** [comment] 2019-06-15 13:28
It has been shown to be addon issue every single time this has been reopened it is simply misses/parries/dodges not being shown on the addon.

**Comment by Lariari** [comment] 2019-06-15 14:48
Ohhh, ty for clearing that up.

**Closed** 2019-06-29 16:57 UTC
Labels: Class: Shaman, Spell, Status: Need Research
