### ISSUE TITLE
[Item][Spell] Elixier of Demonslaying only works on Autoattacks.

### ISSUE THREAD

**Issue by MartMlr** [Atlantiss/NetherwingBugtracker#6156] opened 2019-07-24 10:40 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Use: Increases attack power by 265 against demons. Lasts 5 min. Battle Elixir.

**Current behaviour**:
Increases attack power against Demons only for Autoattacks, abilities don't get buffed at all.

I've tested this against Demons and even though the sample size was not very large, the verdict is: only Autoattacks get buffed, since every other ability stayed the same damage wise. 

Did the same tests with Flask of Relentless Assault active and the abilites showed a damage increase right away. (like they should)

**Expected behaviour**: 
Increases attack power against Demons for all abilities (including pets).

**Server Revision**: 
3085

**Comment by therealSKAS** [comment] 2019-07-24 13:24
Yap i can say after testing it is the same problem for me i clearly see that my AA gets the buff but my stady does not get any buff

**Comment by Easyfraggy** [comment] 2019-07-24 18:54
Confirmed it on PTR steadyshot does not gain benefit from demonslaying.

**Comment by Easyfraggy** [comment] 2019-07-24 18:55
> Confirmed it on PTR steadyshot does not gain benefit from demonslaying.
> 
> The OP isn't accurate though it works fine for melee attacks and abilities. It appears to only affects Steadyshot. Not tested other hunter shots.

**Comment by Haipethdev** [comment] 2019-07-27 12:34
Technically Elixir of Demonslaying should not be affecting ranged attack power at all until patch 2.4.2  It was a melee only consumable until then.

[Elixir of Demonslaying]: This elixir now grants ranged attack power against demons as intended.

https://wowwiki.fandom.com/wiki/Patch_2.4.2

**Comment by MeckieH** [comment] 2019-08-02 14:42
That is a clear bug though. If you intend on replicating bugs then this server has a long way to go. It clearly states it is "attack power" - not ranged or melee - and the patch adds "as intended".

This should be fixed and it should be an easy fix. Hunters losing out on a lot of AP because of this bug.

**Comment by Wolffenstein** [comment] 2019-08-12 21:19
Fixed in rev 3104.

**Closed by Wolffenstein** 2019-08-12 21:19 UTC
Labels: Class: Hunter, Item, Spell, Status: Confirmed
