### ISSUE TITLE
[Core Mechanic] "Fake" GCD caused by spamming of abilities

### ISSUE THREAD

**Issue by MeckieH** [Atlantiss/NetherwingBugtracker#6142] opened 2019-07-20 21:53 UTC
**Description**: 
Spamming an ability on Netherwing while another ability is being cast can trigger a GCD for no apparent reason. This is confirmed affecting several classes: Mages, Paladins and Hunters. It is extremely likely to also affect other classes (but I dont play other classes, sadly).

**Current behaviour**:
For whatever reason, spamming an ability while another ability is being cast, sometimes trigger GCD being refreshed. For Hunters, this causes issues during Steady cast; spamming Arcane Shot or a Steady macro during a Steady cast sometimes trigger a GCD. This is hard to reproduce, but happens relatively often. For mages, it can be reproduced 100/100 with Conjure Water (as shown here: https://github.com/Atlantiss/NetherwingBugtracker/issues/251), but also happens with Icy Veins spam. For Paladins, its causing issues with Illumination spamming.

Here are two examples of the bug in action, both from a Hunter PoV:
https://www.twitch.tv/meckieh/clip/BitterReliablePhonePupper?filter=clips&range=7d&sort=time (Spamming Arcane Shot here before my Steady cast goes off, and GCD is refreshed as if the Arcane Shot goes off, but no GCD is actually spent, causing me to lose a global in this situation)
https://clips.twitch.tv/AmorphousRenownedDuckTwitchRaid (Same situation, randomly GCD locked when my Steady goes off as if I just spent a global which I obviously didnt)

Here are stillpics from the clips showing whats going on: https://imgur.com/a/rEKWfec

**Expected behaviour**: 
Spamming abilities during a cast is not supposed to randomly (in the case of hunters) cause a fake GCD. There is supposed to be some sort check that assures you obviously only go on GCD if u actually spend a GCD. For some reason the other bugreport adressing this issue for mages and paladins has been marked "Fixed", but it most certainly is not.

**Server Revision**: 
3072

**Comment by Evolvee** [comment] 2019-07-20 22:56
https://youtu.be/FXFjvsD7VI4 ?

**Comment by Evolvee** [comment] 2019-07-20 22:58
whats the issue?

**Comment by MeckieH** [comment] 2019-07-20 23:00
> https://youtu.be/FXFjvsD7VI4 ?



> whats the issue?
> i dont get it...
> 
> queued spell doesnt fire or what

Correct. I would assume it is connected to spellqueueing. Server registers the queueing of next ability but it doesnt actually cast it: https://imgur.com/a/rEKWfec, its blatantly obvious to see in these 2 frame by frame pictures of the first clip.

**Comment by Evolvee** [comment] 2019-07-20 23:01
can you record it?

**Comment by MeckieH** [comment] 2019-07-20 23:02
https://www.twitch.tv/meckieh/clip/BitterReliablePhonePupper?filter=clips&range=7d&sort=time

Here is the recording showing it. (From where the pics are from).

Sadly I have not found a way to reproduce it consistently but can find many clips from my raids of this happening. It is only reproducable on a mage casting Conjure Water (and I am assuming its the same issue).

**Comment by SwiftieTBC** [comment] 2019-07-26 13:38
I'm fairly sure this is blizzlike.
In reference to 2.3 
Now some people have interpreted the announced changes as an incentive to buttons-mashing, like Girl Meets WoW (note to self: need to read more on her blog, looks like there's plenty of interesting stuff here). But reading into Slouken's explanations on the intended behaviour, what really happens if you mash 

1. 1. You start your first cast as usual
2. 2. The cast starts on the server, the acknowledgement comes back to the client
3. 3. The acknowledgement is recieved by the client and the client begins its casting
4. You hit the next spell too soon, the global cooldown triggers, preventing you from mashing or doing any other spell action tied to the GCD
5. The server recieves your command, sees that it's too early, sends back a denial
6. The denial is recieved by the client, the GCD is interrupted and you get an error message. You can cast again, triggering the GCD
7. The new spellcast reaches the server, which sees it has not action going, and you're back to step 2.

The key thing here is, during the GCD, the client will no longer accept any casting commands from your side until a) the GCD has run its full course or b) it has recieved a notification from the server that it wasn't actually legit and stops the GCD. Basically, button-mashing, which is possible nowadays, will actually carry a higher penalty than today on spells with cast times longer than 1.5s.

Source https://web.archive.org/web/20071028151030/http://altitis.blogspot.com/2007/10/stopcasting-quartz-and-patch-23.html

The key thing here is, during the GCD, the client will no longer accept any casting commands from your side until a) the GCD has run its full course or b) it has recieved a notification from the server that it wasn't actually legit and stops the GCD. Basically, button-mashing, which is possible nowadays, will actually carry a higher penalty than today on spells with cast times longer than 1.5s

Therefore, don't mash in 2.3 :)

**Comment by eri1997** [comment] 2019-07-27 11:49
Steady shot has a cast time of around 1.2 not 1.5 so it shouldn't be causing fake gcd if i read what you said correctly so the bug still remains.

**Comment by Godmatik** [comment] 2019-08-13 15:02
I noticed the same when conjuring water/food, if you spam it toward the end of the cast it will produce another GCD, dunno if intentional or not.

**Comment by NatsumeLily** [comment] 2020-05-09 08:46
Bump.

**Comment by TheMoneyHater** [comment] 2020-06-30 03:41
When is this being fixed?

**Comment by Wolffenstein** [comment] 2020-06-30 05:31
Fixed in rev 3415.

**Closed by Wolffenstein** 2020-06-30 05:31 UTC
Labels: - Core Mechanic
