### ISSUE TITLE
Warlock Summon Inferno not working properly.

### ISSUE THREAD

**Issue by Meakster** [Atlantiss/NetherwingBugtracker#4679] opened 2019-01-28 19:14 UTC
The ability is suppose to allow the warlock to summon an inferno with the reagent required. The summoned inferno is suppose to stun enemies not the user and allies as well. The summoned inferno, what should be the same level as the warlock whom summoned, will be able to enslave the inferno for its control for 5 minutes. 

The only part of the ability that seems to be working right is casting outdoors. I have tried casting it indoors and in caves and it wont work so that is correct.

**Comment by narayagh** [comment] 2019-01-28 19:33
Possible duplicate of #4493

**Comment by BamboozleNW** [comment] 2020-07-05 23:43
https://github.com/Atlantiss/NetherwingBugtracker/issues/2229

**Closed** 2020-07-06 07:16 UTC
Labels: Duplicate
