### ISSUE TITLE
Lazy peons

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#7202] opened 2020-07-22 18:35 UTC
[DB/Durotar]:
- Awakening Lazy Peons will now properly grant credit to all nearby party members

Tested yesterday. THIS FIX doesn't work, yet implemented in 3425 server rev.

**Comment by AWIDIUS** [comment] 2020-07-22 18:49
Tested even now :)
![image](https://user-images.githubusercontent.com/45521546/88215951-b8572d80-cc5c-11ea-9df8-3b78b4839484.png)
![image](https://user-images.githubusercontent.com/45521546/88216000-c907a380-cc5c-11ea-98d9-4a3a6c1ddb61.png)

**Comment by AWIDIUS** [comment] 2020-07-22 18:50
@Wolffenstein

**Comment by Tereneckla** [comment] 2020-07-22 20:13
Duplicate of #7091

**Closed by Tereneckla** 2020-07-22 20:13 UTC
