### ISSUE TITLE
Custom channels

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#6217] opened 2019-08-15 19:41 UTC
After joining a custom channel (such as world), you will not be able to type in it. No error message or anything if you try, it just won't produce the text in the channel. A relog solves the problem. No addons used, and cache cleared, so it does not appear to be client side, and multiple people I know have similar issues.

Rev 3106

**Comment by danbopes** [comment] 2019-08-26 08:23
Dupe of #230

**Closed** 2019-08-30 13:02 UTC
