### ISSUE TITLE
Epic Run speed w/o a Mount - Flying w/o a Mount

### ISSUE THREAD

**Issue by 1Asperity1** [Atlantiss/NetherwingBugtracker#7939] opened 2021-03-04 02:38 UTC
[//]: # https://www.youtube.com/watch?v=pBK2c4EH36w

**Description**: Requirements - Be a Paladin and be mounted. 
Once you are mounted, you can either fight a priest from the other faction or duel someone. Have the priest Mind Control you while you are mounted. Then have that person make you run or fly and as you are moving, use your bubble to break the mind control. 

That's it. You are now moving at speeds you shouldn't be able to run at while not mounted. If you were flying, now you can fly without a mount.

**Expected behaviour**: Bubble should break mind control but not allow the increased speed/flight to remain.

**Server Revision**: 
3607

**Comment by Tereneckla** [comment] 2021-03-04 07:44
Duplicate of #7908

**Closed as completed by Tereneckla** 2021-03-04 07:44 UTC
Labels: Duplicate
