### ISSUE TITLE
Food/Water consumed while moving

### ISSUE THREAD

**Issue by Shulginx** [Atlantiss/NetherwingBugtracker#307] opened 2018-09-24 01:08 UTC
**Description**: 
Food/Water consumed while moving
**Current behaviour**
Food and Drink is consumed on use while moving. (e.g. Refreshing Spring Water/Tough Jerky) and immediately dispelled by movement
**Expected behaviour**: 
Should be prevented and a "Can't Use While Moving" error should be displayed
**Server Revision**: 

This could be retail-like and I could be wrong

**Comment by wtRCH** [comment] 2018-09-24 01:40
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/17

**Closed by wtRCH** 2018-09-24 01:40 UTC
