### ISSUE TITLE
Windcaller Claw does not give credit for quest in UNDERBOG

### ISSUE THREAD

**Issue by therealCrysis** [Atlantiss/NetherwingBugtracker#7245] opened 2020-07-30 13:33 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
QUEST: Lost in Action (9738) Sends you to Underbog to find 4 NPCs. One of them is
Windcaller Claw (17894).
**Current behaviour**:
NPC 17894 does not give credit for whole party for finding him to make quest completed. There is no rule how many members of party will take credit for this. For some of them works just clicking on this NPC, but not everytime.
**Expected behaviour**: 
Windcaller Claw gives credit to every member of party getting close to him on proper distance.
**Server Revision**:

**Comment by The14me** [comment] 2020-07-30 15:25
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/2216 
and ye, its still bugged.

**Closed** 2020-07-30 15:38 UTC
Labels: Duplicate
