### ISSUE TITLE
[Hunter] [Pets] [Talent] Focused fire pet bonus 

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6890] opened 2020-04-17 10:20 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Sometimes you lose the 2% extra dmg you get from the talent Focus Fire for having a pet up.  I'm not sure what is causing this. Only way you notice is if you remember your dmg values or check by hovering dmg on stats and see the x102% modifier missing.

**Current behaviour**: No 2% extra dmg while having pet up

**Expected behaviour**: If pet up-> hunter gets 2% dmg 

**Server Revision**: Latest

**Comment by eri1997** [comment] 2020-04-19 18:21
To reproduce this : if pet dies on a M'uru pull ( dies by mobs not despawn cuz the player died) and you release->go to the raid again-> click teleport -> and ress the pet on m'uru room you won't get the 2% bonus so the problem probably happens when pets die and player dies after them

**Comment by veekk** [comment] 2020-04-27 14:31
can approve this [video](https://www.twitch.tv/skazzzzus/clip/FineGrotesqueMageOSfrog?filter=clips&range=7d&sort=time)

**Comment by Zarant** [comment] 2020-07-15 05:52
When a pet dies and gets revived, the hunter won't get benefit from any effects that requires the pet being alive like focused fire and spirit bond. You have to revive, then dismiss and summon your pet again to get the buff back.

**Comment by Tereneckla** [comment] 2020-07-15 06:47
Duplicate of #3404

**Comment by eri1997** [comment] 2020-07-15 11:25
@Tereneckla all the bugs except Focused Fire talent listed on that bug report are bugs that directly affect the pet and require pet resummon to work/update pet's stats. Focused Fire affects the hunter's dmg stat not the pets . The talent doesn't recognize that you have the pet up sometimes when you ress it  during wipes. Think the problem is likely different for this bug report compared to the other pet related bugs report about talents that wont update pet stats at all when you put points in the talent until you resummon so I'd keep this bug report up but up to you .

**Comment by Wolffenstein** [comment] 2020-10-22 14:21
Fixed in rev 3544.

**Closed by Wolffenstein** 2020-10-22 14:21 UTC
Labels: Class: Hunter, Pets, Talent
