### ISSUE TITLE
fishing nodes in terrokar bugged, only spawn brackish

### ISSUE THREAD

**Issue by oladia** [Atlantiss/NetherwingBugtracker#5280] opened 2019-03-03 07:38 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by oladia** [comment] 2019-03-03 07:39
fishing nodes in terrokar bugged, only spawn brackish

**Comment by danbopes** [comment] 2019-05-21 00:40
Dupe of #4533

**Comment by raethkcj** [comment] 2019-06-10 22:19
Found a School of Darter today, screenshot with server info here: https://i.imgur.com/pAnzCCg.png

#4533 is still bugged and is NOT a dupe

**Comment by danbopes** [comment] 2019-06-10 22:24
Why is it not a duplicate?

**Comment by raethkcj** [comment] 2019-06-10 22:28
This issue is about which types of schools spawn in Terokkar, my screenshot shows a non-brackish pool spawned there. 

The other issue is about fishing in open water (non-pools). They are separate issues. Fishing in pool does not result in empty catches, but fishing in open water does.

**Comment by Manaci** [comment] 2020-01-03 23:21
Fixed in rev 3138

**Closed by Manaci** 2020-01-03 23:21 UTC
