### ISSUE TITLE
[Druid][Spell] Swiftmend

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7792] opened 2020-12-14 03:19 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
https://github.com/Atlantiss/NetherwingBugtracker/issues/7599#issue-710292691

**Description**: Swiftmend instant heal

**Current behaviour**: Due to latency difference (/issue) there is a possibility for a player to cast a Swiftmend that heals for `"1"`, because the friendly target doesn't have the Rejuvenation / Regrowth effect on it.

**Expected behaviour**: It should not be possible at any cost for Swiftmend to heal the friendly target if he doesn't have either Rejuvenation or Regrowth buff applied.

![image](https://user-images.githubusercontent.com/11255782/95288227-18c33780-0868-11eb-8bb7-d5013d9c8f97.png)

**Server Revision**: 3536

**Comment by Godmatik** [comment] 2024-08-04 05:11
Can't reproduce and have not heard of this ever happening on past year in Netherwing.

Hopefully fixed with all the spell/aura reworks that were done. Will re-open if I hear otherwise though.

**Closed by Godmatik** 2024-08-04 05:11 UTC
Labels: Class: Druid, - Arena
