### ISSUE TITLE
[Core][Dungeon] Stratholme dungeon - Living Side - boss bugs

### ISSUE THREAD

**Issue by MisaHack** [Atlantiss/NetherwingBugtracker#7027] opened 2020-06-11 21:58 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
1, 2) Two boss in Straholme dungeons need fix - "Cannon Master Willey" and "Balnazzar".

3) For some reason after each fight in Stratholme dungeon characters appear to be in combat even if they are not, and they do not have negative effect on them. Consequence of this is that characters can not eat food or drink mana. Only solution we found is to log off and log in each time fight is over. Some players noticed that this happen when Spellcasters heal or buff party members during the fight.

**Current behaviour**:
1) "Cannon Master Willey" - badly scripted, encounter with him is bugged, enemies that boss spawns and that should be killed with cannons just spawn randomly all over the room and they stay in place without doing anything. Also cannons do nothing, can not be used.

2) "Balnazzar" - this boss is currently almost the size of the whole Room when he transforms to the Demon! Size of the Giant!!!! He is very hard to kill now, because he can not be targeted with weapons in close combat or ranged! So very poorly done.

3) Characters appear in fight after finished fight, when they need to rest, even when no enemy is around and no negative effects on characters. Consequence - can not eat and drink mana.

**Expected behaviour**: 
1) "Cannon Master Willey" - scarlet crusaders should come and start firing players with arrows from behind, some of players can shoot them with cannon balls by loading ammo from the floor.

2) "Balnazzar" - this boss should not be Giant size (1/3 of the room). And players can target him properly to fight him.

3) Characters can eat food and drink mana inside dungeon after fight is over if there are no enemies and no negative effects on them.

**Server Revision**: 
3377

**Comment by Hacheteroni** [comment] 2020-07-05 10:19
I can confirm these are working as stated above, Balnazzar can also be CC'ed with death coil which is not intended either. You can see videos here of how the fights should be working. Balnazzar is through the ceiling at the moment causing LOS issues. Cannon master's cannon's don't actually fire on mobs and mobs dont attack players unless attacked or standing right on top of them, also spawn in the middle, not as shown in video. I cannot re-create the combat bug so possibly not connected to these bugs.

https://youtu.be/3yAOdhlXotw?t=927 - To see cannon being used on mobs and spawn position and the way mobs shoot at players.
https://youtu.be/3yAOdhlXotw?t=1187 - To see correct Balnazzar sizing.
https://youtu.be/3yAOdhlXotw?t=1264 - Correct Mob types after Balnazzar



My recordings:-
https://www.youtube.com/watch?v=kApxA9R1mvY
https://www.youtube.com/watch?v=r-sxYZwy3yM


From my recording you can see the following:- 
Balnazaar way too big, he can be affected by deathcoil and you can see the the LOS issues you face when he is that big. Once Balnazzar is killed the incorrect mobs spawn after the fight and also far too few of them, every corridor inside strat live should have the above video's skeletons in them. 
The Riflemen on cannon master fight spawn in the middle and not at the end of the corridor and the cannons are not triggering the blast.
You can manually trigger the blast by walking your char over the trigger point of where the blast is intended to be, this is also not intended. 
The riflemen spawn, are stationary and dont move and only a few of them shoot at you, some dont shoot at all.

**Comment by tcberk12** [comment] 2020-10-15 07:06
Bump on this. Additionally, Timmy does not spawn at all once the all the Scarlet mobs outside the Bastion are killed.

Would really nice to just get the Balnazzar bug fixed though. You can't get any LoS on him at all unless you kite him outside the bastion, and even then it's hard to kill because if you get slept, it will never break unless you can bubble/ice block it etc!

**Comment by Wolffenstein** [comment] 2023-05-27 00:08
Fixed in rev 3783.

**Closed by Wolffenstein** 2023-05-27 00:08 UTC
Labels: Dungeon
