### ISSUE TITLE
[Talent] Sword Specialization

### ISSUE THREAD

**Issue by ahlens** [Atlantiss/NetherwingBugtracker#2421] opened 2018-11-07 12:53 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Hi guys,
I wanted to see if [Sword Specialization](https://tbc-twinhead.twinstar.cz/?spell=13964) talent works properly so I did little research. I created two different characters - Warrior and a Rogue. I built Warrior into tank mode so it can withstand more dmg and I equipped Rogue with 2 low lvl swords. Below you will find results presented in Reccount. I haven't found that issue in bugtacker so maybe it's worth looking at it.

**Current behaviour**:
![sword specialization](https://user-images.githubusercontent.com/23612673/48132395-acaeb200-e293-11e8-8f6b-dc2523ae26af.jpg)

**Expected behaviour**: 
I believe it should be **around** 5% while presented result points at 1.8% proc rate and when I was doing this experiment, I didn't notice any talent proc from Sinister Strike (special ability) either.

**Server Revision**: 
2256

**Comment by ahlens** [comment] 2018-11-07 14:17
I'd like to test [Mace Spec](https://tbc-twinhead.twinstar.cz/?spell=13803) as well but recount doesn't count it when there is a proc. Do you have any idea what software I should use to measure it?

**Comment by bloodwindz** [comment] 2018-11-07 14:48
1  yes 
2 yes as well

**Comment by ScottieDOESknow** [comment] 2018-11-07 19:54
> I'd like to test [Mace Spec](https://tbc-twinhead.twinstar.cz/?spell=13803) as well but recount doesn't count it when there is a proc. Do you have any idea what software I should use to measure it?

I can confirm mace spec works as intended on rogue. Leveled 35-66 with 2x mace.

**Comment by ahlens** [comment] 2018-11-07 20:14
> I can confirm mace spec works as intended on rogue. Leveled 35-66 with 2x mace.

Have you done any kind of calculation or it's just a feeling? It has 6% chance to proc. I'd like to see exact values to confirm that.

**Comment by Easyfraggy** [comment] 2018-11-07 21:12
https://github.com/Atlantiss/NetherwingBugtracker/issues/1365

**Comment by ScottieDOESknow** [comment] 2018-11-08 04:40
Just to clarify sword spec (for rogues)

1. Sword Spec proc off only swords.
1. OH sword spec proc triggers an instant extra MH attack.
3. Special attacks triggers an instant extra MH attack.
4. Sword spec proc is an normal mainhand attack and will cancel attack-in-motion and resets your MH attack timer.
5. Sword spec will NOT proc off enchant/weapon/poison procs.

http://roguecrap.blogspot.com/2006/05/more-on-sword-spec-modeling.html

**Comment by ScottieDOESknow** [comment] 2018-11-08 05:43
> Have you done any kind of calculation or it's just a feeling? 

My feeling: There is no discrepancy BECAUSE of my experience with mace spec. Playing the game as intended with mace spec on Netherwing did not differ from my original TBC experience whatsoever.

Your feeling: There might be a discrepancy BECAUSE sword spec could possibly not be working as intended. These are two separate talents and should not be conflated or compared. Separate ticket IMO.

> It has 6% chance to proc. 

Anyone who uses mace spec (on rogue) should be using 2x mace which is 6% for EACH weapon; that translates to an overall proc chance greater than 6%. Again, this does not feel off, from what I tested leveling 35-66 on Netherwing, compared to what I remember in original TBC. If I felt otherwise, a ticket would have been opened 4-5 weeks ago when a discrepancy would have been very obvious.

> I'd like to see exact values to confirm that.

Values? You said yourself that it's hard to calculate considering there is no comabt log entry. Feel free to prove that it's not working as intended. I'm all eyes for interesting data.

>It's also worth checking if crit damage is increased as well.

I'm sure you already know; crit is the easiest to calculate. Again, if you believe it's not working as intended, simply provide evidence from in game and external evidence that can validate your claim.

**Comment by ahlens** [comment] 2018-11-08 10:45
Scottie,

1. I didn't mean to offend you or whoever read my comment. I feel like you missunderstood my intentions.
2. TBC was like 11 years ago, I'm not sure how to compare that feeling to current development stage. I believe you have much wider experience than I do. I'm just a simple man who likes doing such researches, therefore I'm curious about testing such features.
3. My intention is not to prove at all cost that there is something wrong with that talent, I just wanted to test it. It seems like you've already considered that I state it's working improperly.

I will try to do some calculation in free time, just because I'm curious.

**Comment by ScottieDOESknow** [comment] 2018-11-08 11:49
No offense taken, this is simply a discussion. I'm sure you now understand the differences between our feelings and experiences re: maces. Elaboration was required after my first comment was insufficient.
>I can confirm mace spec works as intended on rogue. Leveled 35-66 with 2x mace. 

I did notice recount shows immune/resist from mace spec
https://gyazo.com/f5062ce3636ff4286121691c790155f6

Still, mace spec deserves a separate ticket if you think there IS an issue, otherwise we're conflating this thread with four separate spells from two classes.

**Comment by Easyfraggy** [comment] 2018-11-11 14:03
![image](https://user-images.githubusercontent.com/36134067/48313916-e4cf3100-e5c2-11e8-9d74-5a196ca01970.png)

**Comment by bloodwindz** [comment] 2018-11-22 08:35
for warrior i test it  on 22 november and the combat log shows very few extra attack procs near 1% i estimate it and probably dont proc from ALL melee attacks (sunder as well or execute etc)

**Comment by Neophrone** [comment] 2018-12-13 23:17
As I commented here:https://github.com/Atlantiss/NetherwingBugtracker/issues/3212 everything is fine.
Easy already posted proves, additional proves from me:
![8](https://user-images.githubusercontent.com/43533040/49971819-77534f00-ff38-11e8-9cf0-6581f84f42a0.jpg)
Some info, this talent say that u'r attacks have 5% chance to make an extra attack, mathematically it's mean that 100 of u'r melee weapon swings/melee abilities (if u're wielding swords ofc) should do in average 5 extra attacks. it doesn't mean that sword spec should deal 5% of u'r overall damage (reference to Ahlens researches of this issue).
So using my recount data 270/5101 = 0.0529 (5.29%).
Where 270 - ammount of sword specialization procs.
5101 - ammount of melee swings.
So the proc chance is 5.29%, I'm pretty sure if I'll do 1 million swings proc chance will be exactly 5%.
Everything works fine for this talent, I didn't test it with different abilities (except Sinister Strike, it works with it btw), but everything else works as it should work. Proves u can find in my comment to this issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/3212.
Also procs shouldn't reset swing timer, it was a bug, that was fixed by Blizzard in 2.1 patch. 
This info u can find here: https://www.engadget.com/2007/05/16/rogue-sword-spec-fixed-for-2-1/.
And it's easy to check on our server, another screenshot will help me with it:
![9](https://user-images.githubusercontent.com/43533040/49972984-ff872380-ff3b-11e8-9538-45f3a46d1c7e.jpg)
MH attack speed - 2.7.
OH attack speed - 1.4.
We got OH hit, that triggered extra attack (with damage MH ofc). Hit, that triggered extra attack and extra attack happened at the same time. 
So if extra attack reseting MH timer, than next MH swing should happen in 2.7 seconds, but OH hit that triggered extra attack reseted at the same time with this extra attack, so next OH hit should happen in 1.4 seconds.
2.7 seconds vs 1.4 seconds - OH hit should happen earlier, but look at the screenshot the next swing after extra attack is a MH swing.
Conclusion: extra attack doesn't reseting MH swing timer. And that is right.

**Comment by Tereneckla** [comment] 2020-01-04 14:42
https://github.com/Atlantiss/NetherwingBugtracker/issues/2421#issue-378275275
5.2% of the hit attacks proc sword spec (assuming they had the same percentage of hits as the sword spec hits. On Sinister Strike I assumed 12% misses (27% is dual wield miss, 9% is style miss. So 30% becomes 12%)

https://github.com/Atlantiss/NetherwingBugtracker/issues/2421#issuecomment-437672677 has exactly 5% of the hit attacks proc sword spec (assuming they had the same percentage of hits as the sword spec hits)

https://github.com/Atlantiss/NetherwingBugtracker/issues/2421#issuecomment-447156233
is a bit above with 5.3%

Seems fine to me.

**Closed by Tereneckla** 2020-01-04 14:42 UTC
Labels: Class: Rogue, Class: Warrior, Status: Need Research, Talent
