### ISSUE TITLE
[Core][Stealth][Rogue][Druid] Stealth and detection is broken

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#7114] opened 2020-07-04 17:18 UTC
**Description**: At level 70 there should be no possible way for a grey level NPC to see/notice you in stealth but it's happening regardless of level difference. Even with 5/5 Master of Deception I am being noticed in stealth by low level Defias in Elwynn Forest.

**Current behaviour**: Stealth and detection detection is broken

https://gyazo.com/45738f31e888a411ba1c60bf2c996117

https://gyazo.com/89f331563bad943074ec2131e8db1c11

**Expected behaviour**: Even without talents or gear that increase stealth or stealth detection, it should be based on level difference between the rogue/druid and NPC or player that could detect them in stealth.

**Server Revision**: 3436

**Comment by Wolffenstein** [comment] 2020-07-04 17:28
Ehh not the detection, just the alert of proximity - you won't aggro the mob until you actually walk into it.

**Comment by Wolffenstein** [comment] 2020-07-04 17:35
Fixed in rev 3437.

**Comment by ScottieDOESknow** [comment] 2020-07-04 20:38
https://gyazo.com/0767d7c4da6f4cf09c5f4ad5f365cb3e

**Comment by ScottieDOESknow** [comment] 2020-07-04 20:39
Not attacking out of stealth due to level difference, but attacking steathed target with same distance

1
https://gyazo.com/9902687b336930a2ee170185a769beba

2
https://gyazo.com/b7ac0dd141e6d99e5554b34186dbb50d

**Comment by Wolffenstein** [comment] 2020-07-05 23:19
It's sort of working as intended for optimization on continents - I explained it to Drain.

**Comment by ScottieDOESknow** [comment] 2020-07-06 12:50
There should be no possible way for an NPC to see a stealth target with that many levels difference, regardless of talents or gear that increase stealth. We're talking about a **level 55 NPC vs a level 70 player**. With 5/5 MoD that another 3 levels. 18 levels total.

Please, look at this again. I am not even in the hit box.
https://gyazo.com/0767d7c4da6f4cf09c5f4ad5f365cb3e

I've done some dueling on PTR since stealth changes, and in a PvP situation vs same level player, stealth seems to function the same as it was before. However, the issue I brought up has major implications in a PvE environment where sap, pick pocket and simply sneaking past enemies is impossible to do even with considering the **glaring** level discrepancies between NPC and player.

It concerns me when you say _"It's sort of working"_ because this sounds like there is doubt or uncertainty as to how it should function in general.  I understand there have been many changes to stealth in the past month+ so I am just trying to understand what changed, and why, and where this information came from. It was, I would say **nearly** blizzlike before, but now you can't even stealth past low level (grey) mobs without them hitting you out of stealth while having **10+ levels** difference. It's absurd.

Either stealth OR detection is being incorrectly calculated based on level differences, or a custom modifier was added for detection, and if the latter is the case, then my next question would be why?

**Comment by ScottieDOESknow** [comment] 2020-07-06 13:01
-standing just out of aggro range of this NPC
-not attacking me
-as soon as I use stealth they aggro

look at the combat log

https://gyazo.com/6082da7d21de5bcf2fde54b275b80545

This is basically working the opposite of how it should
Being in stealth should allow you to get even closer to an NPC than out of stealth
That is the fundamental goal of the spell

**Comment by bekonja** [comment] 2020-07-06 23:37
Can confirm, stealth is a joke at current rev3451. Some low-level scrub mobs can see me and aggro on me at the same range as if i was unstealthed. Basically in PvE only thing stealth does rn is reducing your movement speed.

**Comment by Wolffenstein** [comment] 2020-07-07 04:10
Fixed in rev 3452.

**Closed by Wolffenstein** 2020-07-07 04:10 UTC
