### ISSUE TITLE
[Spell][Paladin][Talent] Divine Favor (100% crit chance doesn't crit)

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1615] opened 2018-10-15 19:09 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/43505031/46971867-77141000-d0bd-11e8-95c1-e8678d7e17ac.png)
**Current behaviour**:
![image](https://user-images.githubusercontent.com/43505031/46971969-afb3e980-d0bd-11e8-8e49-3d457640ed6b.png)
![image](https://user-images.githubusercontent.com/43505031/46971988-c1958c80-d0bd-11e8-8fa6-28564fef9a14.png)
There even fades away after the heal and still not crit:
![image](https://user-images.githubusercontent.com/43505031/46972018-d3772f80-d0bd-11e8-9508-f76576a89ff3.png)
![image](https://user-images.githubusercontent.com/43505031/46972077-f6a1df00-d0bd-11e8-908d-a188063b9d0e.png)
![image](https://user-images.githubusercontent.com/43505031/46972095-06b9be80-d0be-11e8-852e-177443bea3ea.png)

Here I crit, THEN Divini Favor fades away.
![image](https://user-images.githubusercontent.com/43505031/46972213-526c6800-d0be-11e8-8fee-1b9f75fd2354.png)

**Expected behaviour**: 
I think my heal should be 100% crit instead of being this unlucky.
**Server Revision**: 
2177

**Comment by Mikik3jr** [comment] 2018-10-15 20:21
Other thing: When I heal after the heal I instantly use Divine Favor it still consumes it (and no crit ofc)

**Comment by Mikik3jr** [comment] 2018-10-15 21:02
Another note: Holy Shock seems to crit with Divine Favor. I crited 3 times, and you guessed right: the spell faded away after the crit, not before.

**Comment by Mikik3jr** [comment] 2018-10-21 20:04
Update: It seems to work outside of dungeons, but when I am Sunken Temple it doesn't seem to work. Maybe this thing is dungeon specific?

**Comment by Mikik3jr** [comment] 2018-10-26 13:39
It looks like it crits when I heal myself, but not every time when I heal the others.

**Comment by ttghnw** [comment] 2018-10-31 15:34
I can confirm this issue today healing ramparts.

**Comment by ttghnw** [comment] 2018-10-31 21:32
Also confirmed "It looks like it crits when I heal myself, but not every time when I heal the others."

**Comment by Wolffenstein** [comment] 2018-11-11 18:58
Fixed in rev 2300.

**Closed by Wolffenstein** 2018-11-11 18:58 UTC
Labels: - Core Mechanic, Class: Paladin, Spell
