### ISSUE TITLE
Bug Report GM: Gate to Baron Rivendare Not Opening on Stratholme Clear

### ISSUE THREAD

**Issue by DJT777** [Atlantiss/NetherwingBugtracker#5127] opened 2019-02-22 18:26 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by ttghnw** [comment] 2019-03-11 01:46
I can confirm this

**Comment by Manaci** [comment] 2019-03-26 14:21
It opens but it takes like 5-10 minutes.

**Comment by ircfelix** [comment] 2019-07-16 19:04
orly? still happening

**Comment by ircfelix** [comment] 2019-07-20 11:56
Please fix. It should open after the adds that spawn on Ramstein's death are dead.

**Comment by ircfelix** [comment] 2019-07-25 20:20
@Evolvee 

if (ramstein = ded) open gate


Also the gate which you need to clear all 3 ziggurats for to open, stays closed if you wipe at the abomination part of stratholme

**Comment by Evolvee** [comment] 2019-07-25 21:54
ramstein is in cpp

**Comment by ircfelix** [comment] 2019-07-26 15:44
cpp?

**Comment by Evolvee** [comment] 2019-07-26 21:18
c++

**Comment by ircfelix** [comment] 2019-07-27 19:26
ah k pp tt rd fo.

U know what that means.

**Comment by ircfelix** [comment] 2019-07-30 17:27
Thank you @Evolvee for commenting on that issue. Now my faith in you fixing this issue in the near future is renewed! Thanks in advance for fixing it, Wrdl.

**Comment by Evolvee** [comment] 2019-07-30 18:39
i commented the reason why i cant fix it

**Comment by ircfelix** [comment] 2019-07-31 07:30
:PepeHands:

**Comment by ircfelix** [comment] 2019-08-02 08:11
Update:
As seen in this video around 7:30 and later https://www.youtube.com/watch?v=6DEEYMGS24w you see how baron rivendare's two doors (outside ziggurat door and rivendare's chamber door should behave):

- Last abomination on abomination square is killed: Rivendare's outside ziggurat door opens
- Ramstein is dead, Rivendare's chamber door is still closed, skeletons outside the ziggurat **do not** automatically aggro the player like they do on NW: Five Skeleton guardians spawn
- Skeleton guardians are dead: Baron Rivendare's Chamber door opens.

**Comment by Rushor** [comment] 2019-09-28 13:55
the whole script must be reworked

**Comment by The14me** [comment] 2020-07-17 05:07
Rev.3483 the door open by himself in 5 min after the kill.Still an issue.

**Comment by Wolffenstein** [comment] 2023-05-27 00:09
Fixed in rev 3783.

**Closed by Wolffenstein** 2023-05-27 00:09 UTC
Labels: Dungeon, Gameobject, Status: Confirmed, - Core Mechanic
