### ISSUE TITLE
[NPC][Shattered Halls] Shattered Hand Darkcasters Rain of Fire auto cancels

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3522] opened 2018-12-18 22:14 UTC
**Description**: Shattered Hand Darkcasters cast rain of fire and instantly cancel

https://www.youtube.com/watch?v=2MxdAPM30cQ&feature=youtu.be

**Current behaviour**:Shattered Hand Darkcasters cast rain of fire and instantly cancel

**Expected behaviour**: Complete the cast

**Server Revision**: 2462

**Comment by Wolffenstein** [comment] 2018-12-19 21:50
Can't reproduce, seems to be working fine for me. Hard to tell what happened there, maybe something interrupted him. I will close the issue for now and if someone else stumbles upon the same issue I will reopen it (although it would still be a core problem, not of this specific npc).

**Closed by Wolffenstein** 2018-12-19 21:50 UTC
