### ISSUE TITLE
[NPC] Crag Stalker

### ISSUE THREAD

**Issue by Aphroditus-Netherwing** [Atlantiss/NetherwingBugtracker#5078] opened 2019-02-19 04:51 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently Crag Stalker's can attack you in stealth if you do not move or have a buff that deals damage when they attack you.

**Current behaviour**: Currently Crag Stalker's can attack you in stealth if you do not move or have a buff that deals damage when they attack you.

**Expected behaviour**: They should auto remove stealth upon hitting you even without damaging them first or moving.

**Server Revision**: 2816

**Comment by Easyfraggy** [comment] 2019-02-19 09:07
I noticed this on several stealthed mobs when leveling. Seems like a global issue.

**Comment by Evolvee** [comment] 2019-02-22 20:24
cant reproduce

**Comment by The14me** [comment] 2020-07-09 05:22
Rev.3460 still an issue.It's hard to reproduce.

**Comment by Wolffenstein** [comment] 2020-07-10 01:00
Fixed in rev 3470.

**Closed by Wolffenstein** 2020-07-10 01:00 UTC
Labels: - Core Mechanic
