### ISSUE TITLE
Autoattacking stops for a whole fight as rogue, can't re-autoattack

### ISSUE THREAD

**Issue by BelsnickelVD** [Atlantiss/NetherwingBugtracker#7257] opened 2020-07-31 20:44 UTC
As the title says: Autoattacking stops as rogue, can't autoattack again until the next fight. Happened only twice in 50 hours.

**Comment by The14me** [comment] 2020-08-01 10:14
If u use Rend that cancel the auto, just a note.

**Comment by Tereneckla** [comment] 2020-08-02 08:17
Gouge is the spell that cancels your autoattacks. But you can start autoattacking normally afterwards again.

**Comment by Madjarid** [comment] 2020-08-03 16:29
It happened again just now. Didn't use gouge. The combat log doesn't help much. I killed one mob, and went to another and my slice and dice faded. That might be a coincidence but, you know, maybe it'll help you

**Comment by Realnairoby** [comment] 2020-08-14 04:20
Happens to warriors as well. Its more like a melee problem. Couldnt reproduce yet.

**Comment by Tereneckla** [comment] 2020-08-14 04:57
As long as you're not using an ability on focus target. Attacks are intended to sometimes break in that case.

**Comment by tilipitappi** [comment] 2020-11-20 12:48
Happened to me 4 times now. Vanish fixes this. Its an autoattack bug. You just can't autoattack. Pretty shitty if you dont notice it immediately.

**Comment by Madjarid** [comment] 2020-11-20 19:34
> Happened to me 4 times now. Vanish fixes this. Its an autoattack bug. You just can't autoattack. Pretty shitty if you dont notice it immediately.

In my experience you can fix it by pressing escape to remove your target as well , and then start autoattacking again. I haven't played melee in a while, I thought they fixed this. Its been over three months 😕

**Comment by Godmatik** [comment] 2024-07-04 22:42
Can't reproduce and have not heard anyone else having this issue in the past year on Netherwing - closing for now.

**Closed by Godmatik** 2024-07-04 22:42 UTC
Labels: Status: Need Research, - Core Mechanic
