### ISSUE TITLE
The Missing Diplomat

### ISSUE THREAD

**Issue by crowlb** [Atlantiss/NetherwingBugtracker#5385] opened 2019-03-14 05:28 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Missing Diplomat quest can't be finished/continued in dustwallow marsh
**Current behaviour**:
After defeating the private in duswallow marsh, Proudmore and Tervosh appear and speak for a moment then disappear.  After returning to the tower in Theramore, Proudmore as a ? above her head, but you cant turn in a quest.  Tervosh has a ! above his head, but you can't take a new quest from him.
**Expected behaviour**: 
You should be able to turn in the completed quest and take the new one.
**Server Revision**: 
2883

**Comment by Dimbleglim** [comment] 2019-03-17 17:20
Odd; I finished that quest line for as far as it exists (the chain ends abrubtly after all and was left unfinished by blizzard) or should exist in TBC. I did notice the grey exlamation mark over Tervosh though but never returned at higher level.

**Comment by crowlb** [comment] 2019-03-17 19:16
its stuck in dustwallow for me. i cant progress. i have seen others having
the same problem in the past on the discord support channel.

**Comment by Skullshady** [comment] 2019-05-25 10:02
Is your quest fixed? I am having the same issue

**Comment by crowlb** [comment] 2019-05-25 22:58
nope. still have a yellow question mark over jaina in theramore.

**Comment by Tereneckla** [comment] 2020-01-08 13:05
Duplicate of #986

**Closed by Tereneckla** 2020-01-08 13:05 UTC
