### ISSUE TITLE
Hunter Frost trap issue

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6417] opened 2019-11-19 23:07 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sometimes "Frost trap" does not apply debuff on players and they are running inside with 100% speed. 
**Current behaviour**:
![image](https://user-images.githubusercontent.com/52432938/69194338-8f145980-0b31-11ea-879a-0dbdf0407f2e.png)

**Expected behaviour**: 
Frost trap should apply debuff on players which reduce movement speed with 60%
**Server Revision**: 
3194

**Comment by 4egito** [comment] 2019-11-27 23:23
![WoWScrnShot_112819_000634](https://user-images.githubusercontent.com/52432938/69765669-7cc39c80-117d-11ea-95d6-b05fec48eab7.jpg)

**Comment by 4egito** [comment] 2019-11-27 23:28
![WoWScrnShot_112819_000634](https://user-images.githubusercontent.com/52432938/69765733-d4fa9e80-117d-11ea-96f4-392f9e2bfe69.jpg)
I'm not sure how this druid bugs the trap but it does it 5-6 times so please take this issue seriously.
I think it happens when he switch the form in the triggering moment. As u see there is slow on the ground but no debuff...  Same shit happens vs rogue when he uses "Cloak of shadows" in triggering moment.

**Comment by 4egito** [comment] 2019-12-16 10:12
![WoWScrnShot_121619_002415](https://user-images.githubusercontent.com/52432938/70898125-b8bf8400-1ffc-11ea-9cb5-31c145fa7372.jpg)
U can see the position on the warrior who is inside the slow trap behind the pillar but not slowed...
can u please make any research of that bug please?! if u cant fix it gimme privileges i will fix it myself.......

**Comment by Wolffenstein** [comment] 2019-12-18 17:48
If you find a way to reproduce it, it will be fixed. I can't fix something that happens "sometimes" because i cannot trigger it in my local environment.

**Comment by Wolffenstein** [comment] 2019-12-18 21:17
Possibly fixed in rev 3214.

**Closed by Wolffenstein** 2019-12-18 21:17 UTC
Labels: - Core Mechanic
