### ISSUE TITLE
[Mage][Talent] Ignite

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1921] opened 2018-10-27 23:30 UTC
**Description**: Fire mage talent

**Current behaviour**: Applied to enemy as soon as any fire spell crits.

**Expected behaviour**: Spells with a travel time (fireball, pyroblast) should only apply ignite on impact.

**Server Revision**: 2214

**Comment by Evolvee** [comment] 2018-10-27 23:38
caused by revision 2204

**Comment by Easyfraggy** [comment] 2018-10-28 09:41
Altho I do think this issue is valid, could we get some retail confirmation e.g a video to show that it should be the case.

**Comment by Wolffenstein** [comment] 2018-10-28 12:44
Fixed in rev 2205.

**Closed by Wolffenstein** 2018-10-28 12:44 UTC
Labels: - Core Mechanic, Class: Mage
