### ISSUE TITLE
[Core] [NPC] Not able to loot Target Dummies after expiration

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#5627] opened 2019-04-11 13:42 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/5567 - old issue related to topic
https://db.excalibur.ws/?item=4366 
https://db.excalibur.ws/?item=4392 
https://db.excalibur.ws/?item=16023 - related items
https://db.excalibur.ws/?npc=2673 
https://db.excalibur.ws/?npc=2674 
https://db.excalibur.ws/?npc=12426 - NPCs that are affected
https://web.archive.org/web/20070814134438/http://www.thottbot.com:80/?i=4276 - archived comments describing proper behavior

**Current behaviour**:

Player who summoned Target Dummy are not eligible to loot its corpse after expiration

**Expected behaviour**: 

Target dummies should be lootable by player who summoned them after death or expiration

**Small sidenote**:

Assign following loot table to NPC https://db.excalibur.ws/?npc=2673 :
https://db.excalibur.ws/?item=4359 75%
https://db.excalibur.ws/?item=2589 60%
https://db.excalibur.ws/?item=2841 50%
https://db.excalibur.ws/?item=4363 30%
https://db.excalibur.ws/?item=7191 15%
https://db.excalibur.ws/?item=2592 5%

These are rough estimates of actual loot table that was present back in vanilla/tbc. I got it from one of the thottbot comments, rounded down to make sure it not breaks economy in any possible way. Adding proper loot table instead of only 1 item will help to playtest this bug faster.

**Server Revision**: 
2936

**Comment by danbopes** [comment] 2019-04-13 05:13
Dupe of #3936

**Closed** 2019-04-13 13:20 UTC
Labels: - Core Mechanic
