### ISSUE TITLE
[Sunwell - Twins] No target change during Confounding Blow

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6797] opened 2020-03-25 20:53 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lady Sacrolash sometimes does not change target when she uses Confounding Blow on the main aggro target. 

**Current behaviour**:
She keeps targeting the original target. Does not autoattack or anything, just stands there until the Confounding Blow-debuff is gone and then resumes attacking.
[Happens ~10 seconds into this clip](https://clips.twitch.tv/LivelyMiniatureTeaDatSheffy)

**Expected behaviour**: 
Should change to second target in the aggro list.

**Server Revision**: 
3315

**Comment by Suzaru** [comment] 2020-03-26 03:39
Happened at <in Harmony>'s kill today too.

**Comment by Godmatik** [comment] 2024-07-22 05:28
This was an issue last server on Karazhan, however on Netherwing I have not seen it happen once in the several times I have done Twins, and have not heard of anyone experiencing it either. Also not able to reproduce it on PTR

Possibly fixed with one of the new spell/aura branches?

Hope so... will close for now and reopen if I hear reports of it.

**Closed by Godmatik** 2024-07-22 05:28 UTC
Labels: Raid
