### ISSUE TITLE
Something wrong with Hezrul bloodmark 

### ISSUE THREAD

**Issue by TheOnlyHolako** [Atlantiss/NetherwingBugtracker#4008] opened 2019-01-10 04:43 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The night of 10/01 , there was 3 hezruls stacked on each others , with few mobs around stacked too , they killed me , when i came back , i wasn't able to see the hezrul but when i went to his zone , the mobs showed up from nowhere and killed me , i contacted a GM , but since then Hezrul didn't show up , it's been 15 min i'm waiting for him .I think there is something wrong in here . Ty .

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
Edit : I checked today , he seems normal , but a friend of mine told me there has been some issues with him .

**Comment by Drayo** [comment] 2020-07-11 03:50
I killed him twice and he respawned normally for me. No double or triple respawns.

**Comment by The14me** [comment] 2020-07-13 11:48
Rev.3482 good old bug is back.

**Comment by Godmatik** [comment] 2024-07-04 23:27
Can't reproduce, they are patrolling just fine for me, and no complaints about it on Netherwing when it launched last year or Karazhan a couple of weeks ago.

Closing.

**Closed by Godmatik** 2024-07-04 23:27 UTC
Labels: Movement, NPC
