### ISSUE TITLE
Shadowfiend

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8375] opened 2023-04-23 16:27 UTC
Shadowfiend doesnt attack the target sometimes, it just follows it and moves back and forth rapidly, resulting in zero mana gained from the ability.
Happened in arena today, and a few times before in battlegrounds.
Revision: 3758

**Comment by Godmatik** [comment] 2023-04-24 04:02
Confirmed, although it seems to happen pretty infrequently and I am unable to reproduce the conditions for it.

**Comment by ghost** [comment] 2023-05-17 00:32
Maybe 1/10 times. It looks like the pet is constantly switching between attack and follow (target circle is flashing).
edit: i think it's caused by aggressive stance

**Comment by Wolffenstein** [comment] 2023-06-06 17:23
Idk how to reproduce, maybe fixed in rev 3792.

**Closed as completed by Wolffenstein** 2023-06-06 17:23 UTC

**Comment by ghost** [comment] 2023-06-15 11:08
from Discord:

> [11:18] tzeentch: Had 1 guy in blind were hitting the other guy, i pressed macro (just cast fiend, petattack, really simple) and my target changed to the blinded guy and fiend wouldn't leave my side his entire duration
&nbsp;
[11:18] Dionizodoros (100% real GM): (controlling it with crtl + 1/2 seems to not work btw)
&nbsp;
[11:19] tzeentch: I tried clicking the petattack button lol, didn't do shit
&nbsp;
[12:32] Werwood (Not Hyeauloairae): I'm pretty sure the fiend bug is related to the custom racials and shit
&nbsp;
[12:32] Werwood (Not Hyeauloairae): because every time I see a confused priest and their fiend just hanging around, the fiend is friendly to me, I can't attack it
