### ISSUE TITLE
[Class][Spell] No cast animation when pressing autoattack at the end of the cast

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#3886] opened 2019-01-06 13:19 UTC
Current behaviour: When casting lightning bolt, if you hit the melee attack button by the end of its casting time, the animation of the lightning bolt disappears and it looks like the cast was cancelled. The mob does however take the damage and aggro even if you dont see a lightning bolt hitting the target and your character appears not to be casting anymore. 

Expected behaviour: You should be able to press the melee attack button while casting the bolt, but the bolt animation should finish casting before the character goes into melee attack position.

**Comment by Zarant** [comment] 2020-07-21 01:08
It seems like a client side issue

**Comment by Godmatik** [comment] 2024-08-17 22:46
Not a client side issue, it is a bug
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/194
Closing this one

**Closed by Godmatik** 2024-08-17 22:46 UTC
Labels: Spell, Status: Need Research, - Core Mechanic
