### ISSUE TITLE
[Spell] Rapid Killing#35098/35099 lasts it's full duration instead of just the first shot

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#1674] opened 2018-10-17 17:57 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
Rapid Killing lasts it's full 20 second duration regardless of what abilities you use.
https://youtu.be/qxV-CZDqYAY 
**Expected behaviour**: 
Rapid Killing should expire upon the first Aimed Shot, Arcane Shot, or Auto Shot hitting the mob.
**Server Revision**:  2186

**Comment by mhdemn** [comment] 2018-11-07 02:08
server rev 2256
Been keeping an eye on this since I found about the bug; it's [fixed](https://youtu.be/eZnDXtMA-3Q) now. I've been tracking it whole day, no matter the aspect you're in, or whatever the situation is, it gets consumed by auto shot, aimed shot or arcane shot as it should. Guess you forgot to close the issue @Easyfraggy ?

**Comment by mhdemn** [comment] 2018-11-07 13:29
Okay, dunno how to put this, but I talked too soon. See, first thing I do against every mob is cast Aimed or Arcane so I didn't notice, but it seems when you've got a few auto shots in (that are not consuming Rapid Killing) then arcane shot won't consume rapid killing.

You can see all possible situations here, starting with Arc Shot or Aimed Shot (consumes Rapid Killing unlike until 2256) and the residual bug where the first autos ensure rapid killing doesn't go away.

So:
1. Auto Shot doesn't consume Rapid Killing. It should.
1.1 Auto Shot seems to prevent further Shots that should be consuming RK from consuming it.

Very sorry I spoke too fast. Please readd it to to-do list.

**Comment by aspectslul** [comment] 2018-12-27 07:39
Auto Shot doesn't consume Rapid Killing. It should.  confirmed

**Comment by Wolffenstein** [comment] 2018-12-31 02:12
Fixed in rev 2545.

**Comment by Manaci** [comment] 2020-01-03 22:03
Fixed

**Closed by Manaci** 2020-01-03 22:03 UTC
Labels: - Core Mechanic, Class: Hunter, Spell
