### ISSUE TITLE
Hunter's Arcane Shot currently being affected by +/- spell damage.

### ISSUE THREAD

**Issue by DMN7** [Atlantiss/NetherwingBugtracker#8581] opened 2023-07-26 04:30 UTC
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)

**Description**: 
https://www.wowhead.com/tbc/item=31677/fel-mana-potion#comments
**Current behaviour**:
Arcane Shot is currently being affected by spell damage.
**Expected behaviour**: 
Arcane Shot should scale with RAP not spell damage.
**Server Revision**:

**Comment by Godmatik** [comment] 2023-07-26 23:48
Confirmed - negative spell power affects are reducing my arcane shot damage.

It should only be scaling with RAP

**Comment by Wolffenstein** [comment] 2023-07-27 01:37
Are you sure that should be the case in 2.4.3 as well? The comments are from 2.0.8 and lots of coeffs changed since then

**Comment by Godmatik** [comment] 2023-07-27 02:25
https://www.reddit.com/r/classicwowtbc/comments/nikww5/spell_power_hunter_still_a_a_thing/

A reddit thread from classic (which used 2.4.3 values) seems to confirm that spell power scaling to arcane shot was removed starting in TBC (first comment)

**Comment by Peglaa** [comment] 2023-07-31 08:24
https://www.mmo-champion.com/threads/609469-Hunter-spell-damage

here's some real proof from late tbc

**Comment by Wolffenstein** [comment] 2023-08-21 17:22
Fixed in rev 3855.

**Closed as completed by Wolffenstein** 2023-08-21 17:22 UTC
