### ISSUE TITLE
Gnomeregan teleporter in Booty Bay

### ISSUE THREAD

**Issue by Alenka1234** [Atlantiss/NetherwingBugtracker#4021] opened 2019-01-10 16:27 UTC
**Description**: 
The teleport in Booty Bay, which is used mainly by Horde players to teleport to Gnomeregan does not work -- making the instance almost impossible to run by Horde members (or at least requiring from them to run to it which is extremely time consuming)
**Current behaviour**:
The teleport does not work even if you have Goblin Transponder [http://db.hellfire-tbc.com/?item=9173] 
**Expected behaviour**: 
The teleport should teleport people who have done the quest Gnomer-gooooone! [http://db.hellfire-tbc.com/?quest=2843] and have the item Goblin Transponder  [http://db.hellfire-tbc.com/?item=9173] 
**Server Revision**: 
Current

**Comment by Evolvee** [comment] 2019-01-10 22:18
probably caused by the current core changes the realm is going through, was working before

**Comment by Wolffenstein** [comment] 2019-01-17 18:22
Fixed in rev 2647.

**Closed by Wolffenstein** 2019-01-17 18:22 UTC
Labels: Dungeon, NPC
