### ISSUE TITLE
Titles Wheel disappeared, sometimes titles do too.

### ISSUE THREAD

**Issue by SpicyJerk** [Atlantiss/NetherwingBugtracker#6022] opened 2019-06-29 07:56 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hello, well the title said pretty much all of it... I have some Titles problems.
![WoWScrnShot_062919_085958](https://user-images.githubusercontent.com/52343506/60381358-0b5bb280-9a54-11e9-93c8-9545144ae593.jpg)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by SpicyJerk** [comment] 2019-06-30 20:17
Hello ???

**Comment by danbopes** [comment] 2019-09-03 00:07
Dupe of #5806

**Closed by danbopes** 2019-09-03 00:07 UTC
