### ISSUE TITLE
[NPC][Postmaster Malown, Stratholme] Doesn't spawn after 3 mailboxes are opened.

### ISSUE THREAD

**Issue by HadiSalehWeb** [Atlantiss/NetherwingBugtracker#6644] opened 2020-02-21 12:12 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The boss is supposed to spawn after 3 mailboxes are opened, he doesn't. Not even after opening all of them.

**Current behaviour**: Postmaster Malown doesn't spawn after opening three mailboxes.

**Expected behaviour**: Postmaster Malown spawns after opening three mailboxes.

**Server Revision**: 3259

**Comment by Tereneckla** [comment] 2020-02-21 14:09
Duplicate of #5667

**Closed by Tereneckla** 2020-02-21 14:09 UTC
