### ISSUE TITLE
Thunderbluff Lifts

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#54] opened 2018-09-22 21:27 UTC
> When I was jumping on to the elevator too early I got teleported all the way up and then fell down onto the elevator and took damage. Also I tried running back on forth on the edge of the elevators "doorway" when it was about to start going upwards and that seemed to trigger it too, got teleported like 30 yards up and then got stuck in mid air for few secs until I fell down.

Reported by Froztie

Needs additional testing, seems intermittent according to player.

**Comment by Daddydeeds** [comment] 2018-09-22 22:36
Mulgore lift on north side of Thunder Bluff (the lifts to the mid-level bluff).  When exiting lift onto path at top, teleported back to ground at base of lift.  Was able to repeat the bug.

Had no problem with lift on southwest side of Thunder Bluff (the lifts on the path from Bloodhoof Village).

**Comment by Wolffenstein** [comment] 2018-09-22 22:42
Could you provide a video that shows this bug?

**Comment by wtRCH** [comment] 2018-09-22 22:49
It might be due to high ping, because I tried to reproduce it for 10 minutes and did not get it to work once.

My ping was 33ms and there was a player who also tried it and it worked for him (260ms)

**Comment by Easyfraggy** [comment] 2018-09-22 23:30
Can you try recreate now? We have done an update on this issue and seems to work now.

**Comment by Daddydeeds** [comment] 2018-09-22 23:46
Will head over to TB and try the elevators now.

**Comment by Daddydeeds** [comment] 2018-09-22 23:55
Looks like a good fix  : )   Used all four lifts at TB.  Up and down on each lift; stepping off and back on at both upper and lower levels.  No problems.  Ping was between 225-230.

**Comment by aresbrutus** [comment] 2018-09-23 01:41
Seems to be working now so closing it.

**Closed by aresbrutus** 2018-09-23 01:41 UTC
Labels: - Core Mechanic, Other, Status: Need Research
