### ISSUE TITLE
Hunter talent: Entrapment doesn't function atall.

### ISSUE THREAD

**Issue by Ethugx** [Atlantiss/NetherwingBugtracker#3813] opened 2019-01-04 00:02 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hunter talent: Entrapment doesn't function atall.
**Current behaviour**:
no work
**Expected behaviour**: 
work
**Server Revision**: 
please

**Comment by nullfoxh** [comment] 2019-01-04 00:19
Duplicate.
https://github.com/Atlantiss/NetherwingBugtracker/issues/3181

**Comment by The14me** [comment] 2019-01-11 06:01
Duplicate of #3181

**Closed by The14me** 2019-01-11 06:01 UTC
Labels: Duplicate
