### ISSUE TITLE
[Quest] [NPC] Private Thorsen

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5965] opened 2019-06-22 07:27 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When seeing the ! you go and talk to Private Thorsen, and when you do there is no quest to pick up. Even though he has a ! above his head. Also when you are meant to deliver some goods to him, you can't he doesn't acknowledge you have a quest completed.

**Current behaviour**: When seeing the ! you go and talk to Private Thorsen, and when you do there is no quest to pick up. Even though he has a ! above his head. Also when you are meant to deliver some goods to him, you can't he doesn't acknowledge you have a quest completed.

**Expected behaviour**:  Giving you a quest, and handing in completed quests. 

**Server Revision**:  3031

**Comment by danbopes** [comment] 2019-06-22 07:50
Dupe of #5915 which is a dupe of so many others.

**Closed** 2019-06-22 10:14 UTC
