### ISSUE TITLE
[Quest][Shadowmoon Valley] The Deadliest Trap Ever Laid

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#7827] opened 2020-12-22 12:26 UTC
**Description**: 
[The Dealiest Trap Ever Laid](https://www.wowhead.com/quest=11097/the-deadliest-trap-ever-laid) it's daily q for Neterwing reputation.

**Current behaviour**:
[Commander Hobb](https://www.wowhead.com/npc=23434/commander-hobb) he just blocked or even hasn't finished yet. He just stands on his position and doesn't have q mark above his head. On this image below we can see that Hobb didn't move so even't has been blocked.
![image](https://user-images.githubusercontent.com/4455568/102887636-8dfddc00-4457-11eb-88a4-05d0f6b3df6f.png)

I haven't met this bug here yet. It could happen due to two minor bugs there.

[Dragonmaw Skybreaker](https://www.wowhead.com/npc=23440/dragonmaw-skybreaker) at Scryer:
 - some of them spawn on [drakes](https://www.wowhead.com/npc=21648/mature-netherwing-drake) above and aggro to them. Maybe one just evaded and blocked event.
 - some of them when they land don't aggro immediately. Maybe despawned after few sec and blocked the event.
 
**I don't know nothing about Aldor side.**

**Expected behaviour**: 
 - Hobb should go back to his place and we can grab q again
 - Dragonmaws shouldn't aggro to this drakes, which should fly around
 - They should aggro immediately to someone
 [Video at wowhead](https://www.youtube.com/watch?v=M_ygYydXyuk&feature=emb_logo&ab_channel=Blackburn)

**Server Revision**: 
3575

**Comment by Godmatik** [comment] 2024-08-18 23:31
Rev 4018 - unable to reproduce, and never heard of this issue occurring in the past year on Netherwing.

Will re-open if I hear of it on next server.

**Comment by Godmatik** [comment] 2024-09-09 12:13
Reopening - he got stuck on Kara server, so still an issue

**Comment by Godmatik** [comment] 2024-10-13 13:27
Potentially fixed with movement rework

**Closed as completed by Godmatik** 2024-10-13 13:27 UTC
Labels: NPC, Quest, Status: Confirmed
