### ISSUE TITLE
Paladin Buffs with Seals not stacking right

### ISSUE THREAD

**Issue by Firahlus** [Atlantiss/NetherwingBugtracker#624] opened 2018-09-26 02:59 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Seal of Crusader and Blessing of Might not stacking
**Current behaviour**:
Seal of Crusader Rank 1 applied I cannot apply Blessing of Might  Error message: "A more powerful spell is already active".  However with Blessing of Might applied I can apply Seal of Crusader.  Also if blessing of might is already applied I can also just apply it again regardless of Seal of Crusader is applied
**Expected behaviour**: 
Can apply Seal of Crusader of Blessing of Might at any time.
**Server Revision**:

**Comment by wtRCH** [comment] 2018-09-26 03:00
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/56

**Comment by wtRCH** [comment] 2018-09-26 03:00
Refered https://github.com/Atlantiss/NetherwingBugtracker/issues/56

**Closed by wtRCH** 2018-09-26 03:00 UTC
