### ISSUE TITLE
[Hunter][Pet] Stealth Detection

### ISSUE THREAD

**Issue by gwxse8w** [Atlantiss/NetherwingBugtracker#3410] opened 2018-12-13 17:48 UTC
**Description**: 
Looks like Hunter's pet has no stealth detection on its own. It won't sense stealthed players (I was testing in a duel) nearby.
Pets should have their own stealth detection, probably even greater than the average player.

Start a duel with a stealther (I did with a druid).
Put pet on Aggressive and command it to stay.
Get away from the pet (30yards) and make the stealther approach your pet.
Such stealther can sit in stealth on top of your pet without being detected/attacked.

**Current behaviour**:
Pet have no stealth detection on its own.

**Expected behaviour**: 
Pet should detect stealthed players (mobs too?) nearby and if on aggressive it should attack/unstealth them.

**Comment by Wolffenstein** [comment] 2018-12-13 19:18
Need proof

**Comment by Tenoutoften** [comment] 2018-12-15 07:34
These comments are from Cataclysm talking about how it was in vanilla and later on
https://us.battle.net/forums/en/wow/topic/2416206609
>The skill Track Hidden increases all hunters and their pets stealth detection.
So when the pets are set to aggresive, they will attack the first enemy that gets close to them.
That is even the hunter himself hasn't spotted you and you happened to be in the vicinity.

>Certain pets (bats, and dogs) used to be able to detect stealth in vanilla.
None can now.

**Comment by Zarant** [comment] 2020-07-03 03:10
Pets should only be able to attack units that you can see. 
Research was done a while ago here: https://github.com/ccshiro/cc-buglist/issues/1155

**Comment by Wolffenstein** [comment] 2020-07-03 03:24
Is that still happening? Ways to reproduce?

**Comment by Tereneckla** [comment] 2020-07-03 06:19
What Zarant linked is a seperate topic and working properly.
But pets currently do spastic movement if there is a stealthed unit nearby that you cannot see.
https://www.youtube.com/watch?v=oBxTklDmqXM
(I just activated Firebolt autocast because I noticed it wasn't active, pets still just start to attack a unit when you are able to see it)

**Comment by Wolffenstein** [comment] 2020-07-03 18:59
I don't think pets should have a separate detection - it doesn't make sense since it could lead to situations where you see an enemy but your pet doesn't (or vice versa).

**Comment by Tereneckla** [comment] 2020-07-04 11:53
Yes, no real proof for them to have their own detection.
But they shouldn't spastically try to attack a creature they/you cannot see.

**Comment by The14me** [comment] 2020-07-11 03:33
Related https://github.com/Atlantiss/NetherwingBugtracker/issues/3466

**Comment by Wolffenstein** [comment] 2020-07-11 04:53
Attacking should be fixed in rev 3476. The rest requires research we currently do not possess.

**Closed by Wolffenstein** 2020-07-11 04:53 UTC
Labels: Class: Hunter, Status: Need Research
