### ISSUE TITLE
fall damage from flying mount

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#7541] opened 2020-09-13 16:56 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://streamable.com/ppbtrh 
im not sure what triggered it but it seemed to happen when i fly down fast then dismount.
happened once more then i relogged and it stopped for now.
**Current behaviour**:

**Expected behaviour**: 
not die from 15 yards
**Server Revision**: 
3528

**Comment by Godmatik** [comment] 2024-07-07 14:17
Unable to reproduce and have not heard of this happening in past year on Netherwing.

Closing for now.

**Closed by Godmatik** 2024-07-07 14:17 UTC
Labels: Status: Need Research, - Core Mechanic
