### ISSUE TITLE
The Angry Scytheclaws - Sunscale Feather is almost impossible to drop!

### ISSUE THREAD

**Issue by Nightrou** [Atlantiss/NetherwingBugtracker#5831] opened 2019-06-05 22:28 UTC
https://tbc-twinhead.twinstar.cz/?npc=3256
[Quest][The Barrends] The Angry Scytheclaws - The dop chance is stupidly low!
[NPC] Sunscale Scytheclaw
[Npc][Drop] Sunscale Feather

**Description**: I have grinded Sunscale Scytheclaw for 1 hour and half without getting a single Sunscale Feather!

**Current behaviour**: It does not drop!

**Expected behaviour**: According to the database it's drop chance is 15% i killed around 40 without getting a single one.

**Comment by danbopes** [comment] 2019-06-05 22:29
Dupe of #3866

**Closed** 2019-06-06 21:55 UTC
Labels: Duplicate
