### ISSUE TITLE
Fel Cannon Forge Camp Mageddon

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#2118] opened 2018-11-02 04:05 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Kill some Gan'arg servants at a Fel Canon and run away. The Fel Cannon will not drop aggro, so you can go as far as you wish as long as you wish, but will remain aggro'd.

**Current behaviour**:
Fel Cannons that aggro you will never de-aggro.

**Expected behaviour**: 
Once you get a certain distance away from the Fel Cannon, it will lose aggro (and you will be able to mount, go stealth, etc.).

**Server Revision**: 
2244

**Comment by The14me** [comment] 2018-11-02 04:29
duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/2114

**Closed by The14me** 2018-11-02 04:29 UTC
Labels: Duplicate
