### ISSUE TITLE
[Raid][Boss] Nightbane's Fear can push players out of bounds

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6355] opened 2019-10-19 15:56 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://i.imgur.com/HmiK0lO.png
https://i.imgur.com/6WJ6spU.png
<<<< lock on the slope 

**Current behaviour**:
kek

**Expected behaviour**: 
not kek

**Server Revision**: 
3157

**Comment by Evolvee** [comment] 2019-10-20 09:11
https://github.com/Atlantiss/NetherwingBugtracker/issues/5999
https://github.com/Atlantiss/NetherwingBugtracker/issues/5833
https://github.com/Atlantiss/NetherwingBugtracker/issues/5230

**Comment by Tereneckla** [comment] 2020-01-03 22:38
keeping this one

**Comment by The14me** [comment] 2020-07-07 04:13
rev 3441. still cant reproduce.
Can be closed.

**Comment by Wolffenstein** [comment] 2020-07-07 05:05
Hopefully fixed in rev 3453.

**Closed by Wolffenstein** 2020-07-07 05:05 UTC
Labels: - Core Mechanic
