### ISSUE TITLE
Blizzard slow debuff

### ISSUE THREAD

**Issue by Bugsterport** [Atlantiss/NetherwingBugtracker#8291] opened 2023-04-04 08:26 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description:**
Mage Blizzard buff and damage sometimes doesnt apply. Always noticed after Frostnova with Cone of Cold Debuff
It seems more like the spell on itself is bugged

**Current behaviour:**
Blizzard does no damage, nor does it apply its slowing effect on any tick of its cast
After spell cast it wont keep casting for the full duration. it automatically stops before the first tick applys. Cant 100% reproduce the issue.
I noticed that the spell sometimes is not working at all. You start casting and it cancels before the first tick. Only a relog can fix that, but good luck with that when you are in combat :/

**Expected behaviour:**
On any tick of its cast it should apply damage and the debuff slow effect

**Comment by Godmatik** [comment] 2024-07-04 22:36
Can't reproduce - perhaps got fixed with the channeled spells fix several months ago.

**Closed as completed by Godmatik** 2024-07-04 22:36 UTC
