### ISSUE TITLE
Daily Quest: Blood for Blood PTR 2.4

### ISSUE THREAD

**Issue by KeksSC** [Atlantiss/NetherwingBugtracker#6651] opened 2020-02-23 21:52 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest: https://tbcdb.com/?quest=11515
After weakening an "Felblood Initiate" ( https://tbcdb.com/?npc=24918 ) with 
"Fel Siphon" ( https://tbcdb.com/?item=34257) and killing the spawning "Emaciated Felblood" ( https://tbcdb.com/?npc=24955 ), the quest progress did not change. 

**Current behaviour**:
Killing an "Emaciated Felblood" does not add to the quest progress

**Expected behaviour**: 
Killing an "Emaciated Felblood" should add to the quest progress

**Server Revision**: 
PTR 3255

**Comment by Tereneckla** [comment] 2020-02-23 22:44
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/6516#issuecomment-589990329

**Closed by Tereneckla** 2020-02-23 22:44 UTC
