### ISSUE TITLE
Ziggurat in EPL, LoS problem

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1226] opened 2018-10-05 00:09 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There was some kind of invisible wall in a certain Ziggurat, making the mob run all the way around to get to you.
![screenshot_531](https://user-images.githubusercontent.com/40346279/46494393-1f39f700-c7e9-11e8-8c2a-354f57524105.png)
This is the .gps from the place where it happened
**Current behaviour**:
I can't actually upload the gif for some reason, but whisper Elyne in discord and I'll send you it
**Expected behaviour**: 
There should not be an invisible wall there.
**Server Revision**:

**Comment by Godmatik** [comment] 2024-08-20 00:12
Unable to reproduce - tested at those exact coords and around the entire inside of the ziggurat, mobs moved around with no issue.

Possibly fixed with last year's pathing updates.

**Closed by Godmatik** 2024-08-20 00:12 UTC
Labels: Gameobject, NPC, Status: Confirmed
