### ISSUE TITLE
[Spell] [Priest] Mindcontrol breaking

### ISSUE THREAD

**Issue by xalin246** [Atlantiss/NetherwingBugtracker#6929] opened 2020-05-03 11:35 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: While leveling my priest i used rank 1 and 2 of mindcontrol. I tried to attack another mob with it but after like 5 seconds max it will break the mc. This happens everytime. Well now i dont know if thats something which is supposed to be like that or not, altough it makes mindcontrol pretty useless to me. I tested it on mobs on my level range and even mobs 20 level beneath my, which didnt change anything.

Thanks in advance

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment] 2020-05-03 13:33
Duplicate of #5089

**Closed by Tereneckla** 2020-05-03 13:33 UTC
