### ISSUE TITLE
([Spell][Paladin] Spiritual Attunement)

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3807] opened 2019-01-03 18:26 UTC
**Description**: Spiritual Attunement is not giving mana when the heal being used on the paladin bring the paladin from x% to 100% full health. It works as intended as long as the paladin is not brough up to maximum health. Example: Paladin is at 50% health, heal crits him and brings him to 100% health, paladin does not gain mana.

**Current behaviour**: Works fine unless the heal is bringing paladin to maximum health.

**Expected behaviour**: The paladin would gain mana equal to the amount of health healed despite if the heal heals them to full.

**Server Revision**:

**Comment by staplerx300** [comment] 2019-01-24 10:11
still bugged btw, makes dungeons horrible

**Comment by Nonamesleftffs** [comment] 2019-01-24 10:47
https://youtu.be/YSQuG-IqUJ4

Made a video to show just how bad the issue is - It's returning around 3% of healing received rather than 10%. This is effectively making Protection Paladins not viable.

**Comment by totaemoeggerli** [comment] 2019-01-29 15:11
please fix this issue as fast as possible

**Comment by Nonamesleftffs** [comment] 2019-01-29 21:19
Still not fixed. I am posting about it on discord virtually every day and devs just take the piss..

**Comment by Wolffenstein** [comment] 2019-02-01 02:58
Fixed in rev 2741.

**Closed by Wolffenstein** 2019-02-01 02:58 UTC
Labels: Class: Paladin, Spell

**Comment by Arnamik12** [comment] 2019-02-04 13:10
This is broken again like before the fix :(
