### ISSUE TITLE
[Quest][Mana-Tombs] escort npc in 'Someone Else's Hard Work Pays Off' gets stuck

### ISSUE THREAD

**Issue by eepoo** [Atlantiss/NetherwingBugtracker#6622] opened 2020-02-08 10:31 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The escort seems to work fine until the part where the two Nexus Terrors spawn. The escort npc seemed to engage the first Terror but then gets stuck in place. NPC evades everything, like if you try to cast a buff on him. The quest in question is https://www.wowhead.com/quest=10218/someone-elses-hard-work-pays-off
My party cleared all the thrash from the dungeon before starting the escort. Not sure if that makes any difference.
**Current behaviour**:
NPC gets stuck after two Nexus Terrors spawn.
**Expected behaviour**: 
NPC doesn't get stuck, keeps fighting and continues his path to the entrance of the instance to complete the escort.
**Server Revision**: 
Not sure, happened on 8th Feb, 2020.

**Comment by Evolvee** [comment] 2020-03-31 18:34
Hmm, I cant reproduce this.

**Comment by Wolffenstein** [comment] 2020-05-03 17:30
Fixed in rev 3365.

**Closed by Wolffenstein** 2020-05-03 17:30 UTC
Labels: Status: Confirmed
