### ISSUE TITLE
Shutting Down Manaforge Coruu  cant do this quest

### ISSUE THREAD

**Issue by yihu0259** [Atlantiss/NetherwingBugtracker#5638] opened 2019-04-14 01:14 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Shutting Down Manaforge Coruu] cant do this quest, the crystal cant be used
**Current behaviour**:
[Shutting Down Manaforge Coruu] cant do this quest, the crystal cant be used
**Expected behaviour**: 

**Server Revision**: 
2939

**Comment by danbopes** [comment] 2019-04-14 01:37
Dupe of #2278

**Closed** 2019-04-14 17:54 UTC
