### ISSUE TITLE
Skull rock voidwalkers do not drop aggro

### ISSUE THREAD

**Issue by Perturabo** [Atlantiss/NetherwingBugtracker#286] opened 2018-09-23 21:57 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Durotar] Skull Rock)
[//]: # ([NPC] Voidwalker Minion)

**Description**: 

Voidwalker minions inside skull rock follow you for an infinite amount.

**Current behaviour**:

Voidwalker minions inside skull rock follow you for an infinite amount.

**Expected behaviour**: 

Having a range at which they drop aggro, like all mobs.

**Server Revision**: 

Latest

**Comment by Godmatik** [comment] 2018-09-23 22:03
Duplicate of #169

**Closed** 2018-09-23 23:35 UTC
Labels: NPC
