### ISSUE TITLE
[Hunter][Talent] Serpent's Swiftness Pet's melee attack speed

### ISSUE THREAD

**Issue by zonk2** [Atlantiss/NetherwingBugtracker#4329] opened 2019-01-18 19:05 UTC
**Description**:
Hello, i don't know if it is an actual bug or just a tooltip error (but atleast it seems like a bug).

The talent 'Serpent's Swiftness' grants your pet 20% increased attack speed. But if you spec it, the tooltip of your pet's attack speed doesn't change. Other buffs like spec'd 'Frenzy' or 'Cobra Reflexes' do change the attack speed to the correct value. Furthermore it doesn't feel like your pet is attacking faster if you skill Serpent's Swiftness.

**Current behaviour**:
The talent 'Serpent's Swiftness' doesn't increase the attack speed of your pet. Only your own attack speed.
**Expected behaviour**: 
The talent should increase your pet attack speed by 20%

**Server Revision**: Latest

**Comment by Zarant** [comment] 2020-07-15 06:07
I suspect this issues and issues #6890 and #3404 have the same root cause.

**Comment by Tereneckla** [comment] 2020-07-15 06:47
Duplicate of #3404

**Closed by Tereneckla** 2020-07-15 06:47 UTC
Labels: Class: Hunter, Pets, Talent
