### ISSUE TITLE
[Quest][Azshara] Kim'jael Indeed!

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#4800] opened 2019-02-03 10:10 UTC
https://vanilla-twinhead.twinstar.cz/?quest=3601

**Current behaviour**:

When you try to loot some boxes that are empty they don't respawn. Only 3-4 boxes of a total of ~10 have loot in them and respawn. 

**Expected behaviour**: 

Even if a box is empty they should disappear and respawn eventually. 

**Server Revision**:

**Comment by danbopes** [comment] 2019-04-24 20:42
Dupe of #4719

**Closed** 2019-04-25 13:30 UTC
