### ISSUE TITLE
[NPC] Grishna Harbinger [Spell] Shriveling Gaze

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2758] opened 2018-11-18 07:33 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/spell=37589/shriveling-gaze#comments
<img src="https://i.imgur.com/p3Utjhj.png">
**Current behaviour**:
Reduces strength by 2. Does not reduce character size.
**Expected behaviour**: 
Should reduce character size and strength to a set amount/percentage, then progressively fade every second (20 to 0 stacks).
**Server Revision**:

**Comment by Evolvee** [comment] 2020-02-01 10:02
it reduces the size, the problem is just that the spell is not casted fully stacked so its close to not visible

**Comment by Evolvee** [comment] 2020-02-01 10:05
@Wolffenstein ez fix

**Comment by Wolffenstein** [comment] 2020-05-06 19:42
Fixed in rev 3368.

**Closed by Wolffenstein** 2020-05-06 19:42 UTC
Labels: - Core Mechanic, NPC, Spell, Status: Confirmed
