### ISSUE TITLE
[CORE] Spell ranks upon Activating Dual Spec

### ISSUE THREAD

**Issue by gun4axb** [Atlantiss/NetherwingBugtracker#8281] opened 2023-04-03 01:32 UTC
**Description**: 
Slight agitation when switching specializations for ability deranks.

**Current behaviour**:
Sets all abilities on bars to max rank.

**Suggestion**: 
I'd prefer to keep the set ability's rank as was before switching specializations.

**Server Revision**: 
3728

**Comment by Godmatik** [comment] 2023-04-03 02:44
Confirmed, this is likely due to the fact that when you learn a skill from trainer, it automatically places the newest rank spell on your bar ... TECHNICALLY not blizzlike actually but is very convenient regardless ... although causes issues for dual spec particularly for healers.

**Comment by Wolffenstein** [comment] 2023-04-03 12:51
Fixed in rev 3729.

**Closed as completed by Wolffenstein** 2023-04-03 12:51 UTC
