### ISSUE TITLE
BRD - Arena spectators not turning neutral

### ISSUE THREAD

**Issue by arthur-merlin** [Atlantiss/NetherwingBugtracker#8477] opened 2023-06-09 20:06 UTC
**Description**: Arena Spectators in BRD 

**Current behaviour**: Arena spectators npc=8916 do not turn neutral after completing the arena event.

**Expected behaviour**: They should turn neutral after completing the arena event.

**Server Revision**:

**Comment by Godmatik** [comment] 2023-06-09 23:13
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/1470

But yeah, BRD is on the list as far as I know of dungeons that need to be fixed, lots of issues with it. Stratholme and Scholomance were recently fully re-scripted, hopefully this dungeon is soon.

**Closed as completed** 2024-07-01 22:26 UTC
