### ISSUE TITLE
[Quest][Item] Kil'sorrow Banner

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6825] opened 2020-04-04 10:01 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: "Can't do that yet" message

**Current behaviour**: If you pull a lot of ogres and kill them in one place, you can't use more than one banner because you are too close to already placed banner.

**Expected behaviour**: Should be able to place more than one banner if there is a stack of Warmaul Ogre bodies in one place.

Quest:
[Returning the Favor]

**Server Revision**: 3320

**Comment by The14me** [comment] 2020-04-04 11:02
Quest ID 9931
Banner ID 25555
Proof
https://wow.zamimg.com/uploads/screenshots/normal/306824-kilsorrow-banner.jpg
@tsuone  u know how to make good bugreport...don't slack ^_^

**Comment by raethkcj** [comment] 2020-04-06 21:50
Duplicate of issue since beta #3317

**Closed** 2020-04-06 22:44 UTC
