### ISSUE TITLE
[Spell](Netherspite) Beam Portal

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3631] opened 2018-12-23 23:01 UTC
**Description**: 
Topic is related to the portal on the right side as you enter Netherspite's boss room and its visual clarity.

**Current behaviour**:
The beam coming out of the right side will sometimes be invisible.

**Expected behaviour**: 
The beam should be visible like the others.

**Server Revision**: 
2485

**Comment by AxeCell** [comment] 2018-12-23 23:43
Timestamp of the northern beam being invisible: https://www.twitch.tv/videos/353241369?t=07h47m50s

**Comment by Wolffenstein** [comment] 2018-12-24 01:01
I honestly cannot reproduce it by I pushed a small change in rev 2493 that may or may not help. Closing for now.

**Closed by Wolffenstein** 2018-12-24 01:01 UTC
