### ISSUE TITLE
[Spell][Paladin] Judgement doesn't hold you in combat

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1894] opened 2018-10-26 13:44 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You use paladin seals to judge on the enemy.
**Current behaviour**:
When someone pulls a mob and I as a person not in combat judges the mob that is focusing on someone else it puts me in combat. If I don't do anything for like 2-3s I leave combat.
**Expected behaviour**: 
I don't think I should leave combat after judging the enemy.
**Server Revision**: 
2214

**Comment by Tereneckla** [comment] 2020-01-08 14:51
Duplicate of #1224

**Closed by Tereneckla** 2020-01-08 14:51 UTC
Labels: - Core Mechanic
