### ISSUE TITLE
[Core][Spell][PvE] Entangling Roots expiration removes eating & drinking effect.

### ISSUE THREAD

**Issue by Kvel2D** [Atlantiss/NetherwingBugtracker#843] opened 2018-09-28 22:50 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Entangling Roots used by Bristleback Thornweaver dispells eating and drinking buffs when it expires.
![2018-09-28 15_44_47-world of warcraft](https://user-images.githubusercontent.com/13269470/46236923-27e88400-c336-11e8-8999-4690343a8b50.png)
![2018-09-28 15_44_50-world of warcraft](https://user-images.githubusercontent.com/13269470/46236927-2c14a180-c336-11e8-8fe7-67329ad035ff.png)

**Current behaviour**:
Entangling Roots dispells eating and drinking buffs on expiration.

**Expected behaviour**: 
Entangling Roots shouldn't affect eating and drinking buffs.

**Server Revision**: 
2078

**Comment by wowthings** [comment] 2018-09-28 22:52
But they do damage... right?

**Comment by Kvel2D** [comment] 2018-09-28 22:53
Frost Nove used by Bristleback Water Seekers does this as well. Might be a problem with offensive debufs in general.

**Comment by Easyfraggy** [comment] 2018-09-28 22:58
Shouldnt entangling roots interrupt eating/drinking every time it ticks?

Frost nova I guess should only be on initial hit.

**Comment by The14me** [comment] 2018-09-29 09:46
Work the same way like the DoT's.Dmg=interrupt.No matter single spell or not.

**Comment by Kvel2D** [comment] 2018-09-29 16:13
The problem is not with the damage portion of those debuffs. The food and drinking buffs are canceled when the debuff _expires_. There is no damage to the player on expiration of the debuff and it obviously doesn't make sense that just the expiration should cancel eating.

**Comment by Evolvee** [comment] 2018-10-01 15:40
periodic damage never interrupted eating

CC effects fading away as well

this is a critical pvp bug

**Comment by Brasso** [comment] 2018-12-15 20:41
Cannot reproduce in pvp with entangling roots. Either it's fixed or it's spell specific. https://i.imgur.com/JvUoWJv.gifv

**Comment by Tenoutoften** [comment] 2018-12-16 10:13
This is still happening, since it doesn't happen in PvP it might be strictly a PvE thing.
[NW Behavior vid](https://www.youtube.com/watch?v=QriHhTSzuug&feature=youtu.be)

**Comment by Godmatik** [comment] 2024-07-06 03:56
Was fixed last year

Closing.

**Closed by Godmatik** 2024-07-06 03:56 UTC
Labels: Spell, - Core Mechanic
