### ISSUE TITLE
Grandmaster Vorpil teleport ability

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7343] opened 2020-08-09 00:08 UTC
The teleport ability of this boss does not function (in normal or heroic), he uses it but nothing happens to most of the party (except perhaps the tank), you don't get teleported to where he is at.

**Comment by Tereneckla** [comment] 2020-08-09 17:16
Duplicate of #6547

**Closed by Tereneckla** 2020-08-09 17:16 UTC
