### ISSUE TITLE
Budd's Map

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8868] opened 2024-01-19 22:49 UTC
**Current behaviour**:
Quest item still despawns after sometime, issue is not resolved.

https://github.com/Atlantiss/NetherwingBugtracker/issues/8858

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/ff6ec846-a313-4dfa-b1cc-cac80107292a)

**Server Revision**: 
3956

**Comment by Wolffenstein** [comment] 2024-01-21 00:22
idk then cant reproduce

**Comment by Godmatik** [comment] 2024-01-21 04:12
Seems like it happens toward end of a run after everyone is done with ZA they go back for map and its not there. Maybe it is related to the prisoner being freed and/or his nearby chest being looted, or the bear boss being defeated, or all bosses being defeated? Just throwing out ideas, will try to mess around on PTR sometime to reproduce

**Comment by Wolffenstein** [comment] 2024-01-21 17:43
Maybe will be fixed in rev 3957. If not, reopen.

**Closed as completed by Wolffenstein** 2024-01-21 17:43 UTC
