### ISSUE TITLE
[Spell][Mage] Dampen Magic - reducing mobs spell damage to 0

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3235] opened 2018-12-04 15:17 UTC
**Current behaviour**:
When under the effect of Dampen Magic all damage which deals less than 180 spell damage is reduced to 0 as seen on screenshot (it isn't even logged). It can be seen in Lash of Pain f.e

![screenshot_3](https://user-images.githubusercontent.com/43505196/49451725-1d3be680-f7e0-11e8-814a-f600acb6adc6.png)

**Expected behaviour**: 
When under Dampen Magic effect no matter if spell deals 2 dmg 100 dmg etc when less than 180, it should always deal at least "1" damage.

**Server Revision**: 
2382

**Comment by Tenoutoften** [comment] 2018-12-04 15:35
https://www.wowhead.com/npc=10928/succubus-minion
https://db.excalibur.ws/?spell=32202
https://www.wowhead.com/spell=32202/lash-of-pain#used-by-npc

**Comment by Firroth** [comment] 2018-12-04 19:47
Okay, tested it once more after, encountering similar issue with other mob. Since I just picked up mage for fast dpsing down mobs for quests etc. for outlands, since I skipped p2 and p3 of tests, and know practically nothing about mages, so I leave it to you guys.

Issue lies with "Dampen Magic" I had it cast on myself during this quest, that's why no damage or anything even tho mob casted spell on me. When I removed it, it dealt 61 dmg - though I think it's a bit too low for outlands hp standards of players xD, maybe wrong spell id?

Anyway back to topic, dampen magic seems to nullify entire spell damage up to 180, so should it look like that in this case for spells which deal less than 180 dmg and not even log it in combat log except spell being used? I found it out when I went to Tombs of Cabal and here Arcane missiles did the same, 0 damage with dampen on, and with it off it dealt 160-170. Look:

![2018-12-04_20-30-00](https://user-images.githubusercontent.com/43505196/49468613-a580b280-f805-11e8-92f5-43d7bde93ee7.gif)

So what do you think? does it work like intended? or there should be even "1" dmg reported.

**Comment by Tenoutoften** [comment] 2018-12-04 20:45
It's most likely not wrong spell ID, but possibly wrong scaling. Lash of Pain was reported a few times before scaling of spells was looking at more closely so it could have been double nerfed if it is too low.

The lowest damage it should be reduced to is 1. I made two reports on Blessing of Sanctuary and in one of them I went on a mob that had his damage reduced to 0(Even though 1 should be the lowest value) this resulted in the mob missing all of his attacks: https://github.com/Atlantiss/NetherwingBugtracker/issues/3072

**Comment by Firroth** [comment] 2018-12-04 20:50
Yup, will do thanks for input.

**Comment by Tenoutoften** [comment] 2018-12-04 20:58
[[Spell]Lash of pain(rank 6)#11780](https://db.excalibur.ws/?spell=11780) does 99 dmg.
This is from the warlock [[Item]Grimoire of Lash of Pain (Rank 6)](https://db.excalibur.ws/?item=16374), requires level 60. So I'd expect the [[NPC]Succubus Minion#10928](https://db.excalibur.ws/?npc=10928) to deal roughly that damage.

**Comment by ircfelix** [comment] 2018-12-04 22:23
Proof for 1 dmg:

https://www.youtube.com/watch?v=pcl7REPFimg
(vanilla source though)

**Comment by Wolffenstein** [comment] 2018-12-05 03:11
Fixed in rev 2393.

**Comment by ircfelix** [comment] 2018-12-05 22:10
As of Patch 1.12, this spell will no longer reduce a spell's damage below 50% of the total damage it would have dealt. If Dampen Magic reduced a spell's hit from 100 damage to 10 damage, that spell will now do 50 damage.

http://wowwiki.wikia.com/wiki/Dampen_Magic?oldid=1431792

**Comment by devo6969** [comment] 2020-07-08 05:21
Seems to be working as intended Cabal did 173-171 magic damage and as I put on Dampen Magic, (Rank 6) would reduce to 120 flat.

**Closed** 2020-07-08 19:28 UTC
Labels: Class: Mage, Spell, Status: Need Research
