### ISSUE TITLE
[Quest] Fel Embers not completable on Heroic

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7098] opened 2020-07-02 11:55 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/86355678-57df5c80-bc6b-11ea-8f29-dab9acf66b94.png)
https://www.wowhead.com/quest=9494/fel-embers

**Current behaviour**: Only completable in Normal Mode

**Expected behaviour**: Also completable in Heroic Mode

**Server Revision**: 3422

**Comment by BamboozleNW** [comment] 2020-07-02 22:18
Proof?

**Comment by BamboozleNW** [comment] 2020-07-02 22:29
Looking into this though yet to find any solid information it should, though my hunch is if it drops in heroic you should be able to complete the quest as well in heroic if working as intended.

**Comment by Wolffenstein** [comment] 2020-07-02 22:30
Fixed in rev 3424.

**Closed by Wolffenstein** 2020-07-02 22:30 UTC
