### ISSUE TITLE
[spell][warlock] felguard's intercept (pet sometimes not charging)

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6933] opened 2020-05-06 12:14 UTC
**Description**: 
from **time to time** once you cast intercept (felguard's) - pet is not charging - just stunning enemy and dealing intercept's damage.

I'm not 100% sure but it looks like this happens when you are using intercept on exact 8 yards or exact 25 yards range (between pet and enemy) - or it might be just random.

tested with intercept lvl 1: https://tbcdb.com/?spell=30154

**Server Revision**: 
3365

![WoWScrnShot_050620_140659](https://user-images.githubusercontent.com/43931626/81175368-b954b900-8fa3-11ea-84ed-254eea86e8f6.jpg)

**Comment by Tereneckla** [comment] 2020-05-07 18:17
Duplicate of #1895

**Closed by Tereneckla** 2020-05-07 18:17 UTC
