### ISSUE TITLE
cannot loot player corpse in battleground

### ISSUE THREAD

**Issue by Pecka69** [Atlantiss/NetherwingBugtracker#5702] opened 2019-04-27 15:03 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
sometimes i cannot loot player's corpses in battleground, so they can just run back and ressurect there
**Current behaviour**:
some ccorpses are unlootable
**Expected behaviour**: 
all corpses should be lootable to deny corpse run
**Server Revision**:

**Comment by Godmatik** [comment] 2024-07-03 03:10
Not able to reproduce, was able to loot every player.

Closing.

**Closed by Godmatik** 2024-07-03 03:10 UTC
Labels: PvP: Battleground & Arenas
