### ISSUE TITLE
[Spell][Priest] Inner Focus cooldown does not reset when used

### ISSUE THREAD

**Issue by andort1** [Atlantiss/NetherwingBugtracker#4945] opened 2019-02-10 15:53 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment] 2019-02-10 15:58
?

**Comment by killablink** [comment] 2019-02-10 16:35
I think it's the same problem as Combustion. You use combustion but sometimes you don't see the spell go on cooldown. It's actually on cooldown but it seems like it's ready.

**Comment by Mikik3jr** [comment] 2019-02-10 17:31
Sometimes it happens that the priest uses Inner Focus (an activable spell) and when they use it it does not show it is on cooldown. It shows that you can use it, but it says spell is not ready yet. After the cooldown ofc it is usable again, but you don't see it visually that the CD is over.

Similar on Divine Favor for paladins.

**Comment by towneh** [comment] 2019-02-11 14:11
The inner focus spell incurs the cool down after being used, but the icon itself does not update (nor are you able to track with timers) to show that a cool-down is in effect,

**Comment by Desst** [comment] 2019-02-13 10:00
can confirm

**Comment by Qrokqt** [comment] 2019-02-16 23:36
It seems to happen when a spell is queued at the same time, if you inner focus then wait a sec and then cast a spell it goes on cd like normal. But when you inner focus and cast another spell at the same time it wont show as going on cd.

**Comment by Godmatik** [comment] 2024-08-01 14:22
Rev 4016 - Unable to reproduce, tried to queue it at end of cast several times now, and it still goes on CD properly.

Also have not heard of anyone running across this in the past year on Netherwing.

Hopefully fixed at some point - closing for now.

**Closed by Godmatik** 2024-08-01 14:22 UTC
Labels: Class: Priest, Spell, - Core Mechanic
