### ISSUE TITLE
Hunter pet bugged upon abandonment

### ISSUE THREAD

**Issue by Squiggh** [Atlantiss/NetherwingBugtracker#7208] opened 2020-07-23 00:03 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Cant tame a new pet when your current one runs away due to happiness level

**Current behaviour**: Cant tame a new pet when your current one runs away due to happiness level

**Expected behaviour**: Able to tame a new pet when runs away due to being unhappy.

**Server Revision**:

**Comment by Zarant** [comment] 2020-07-24 04:33
Duplicate of #5792

**Closed by Zarant** 2020-07-24 04:33 UTC
Labels: Duplicate
