### ISSUE TITLE
[Quest][The Barrens]Counterattack!

### ISSUE THREAD

**Issue by Dajmills** [Atlantiss/NetherwingBugtracker#284] opened 2018-09-23 21:51 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Kolkar Invaders do not leesh / reset.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment] 2018-09-23 21:56
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/254

**Closed by wtRCH** 2018-09-23 21:56 UTC
