### ISSUE TITLE
[Quest] Children's week

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#278] opened 2018-09-23 21:30 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Instant completion for the quests when you take them
**Current behaviour**:
You can turn in the quest without completing it and you get the exp and everything in SW where you pick up the quests
**Expected behaviour**: 
You should visit the places and then blow the whistle to summon the child to complete the quest
**Server Revision**: 
![wowscrnshot_092318_232820](https://user-images.githubusercontent.com/12075744/45933218-b05ad380-bf88-11e8-94b7-7e50489f311a.jpg)

**Comment by wtRCH** [comment] 2018-09-25 01:30
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/146

**Closed by wtRCH** 2018-09-25 01:30 UTC
Labels: Quest, World Events
