### ISSUE TITLE
If Centaur net fades after battle, it'll take cannabilize with it

### ISSUE THREAD

**Issue by Riphook** [Atlantiss/NetherwingBugtracker#7913] opened 2021-02-14 07:03 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Mob][Magram Wrangler)
[//]: # ([Spell][Hunter?] Net)

**Description**: 

**Current behaviour**
If I kill a Magram Wrangler while it has its net cast on me and I choose to cannabilize it, when the net fades it will take the cannabilize affect with it.
**Expected behaviour**: 
I expect cannabilize to be unaffected and be cast for its full length.

<a href="https://imgur.com/a/DfPeM9e"><img src="https://i.imgur.com/uanDKzY.gif" title="Cannibilize"/></a>

**Server Revision**:

**Comment by Tereneckla** [comment] 2021-03-07 12:50
Duplicate of #6298

**Closed as completed by Tereneckla** 2021-03-07 12:50 UTC
Labels: Duplicate
