### ISSUE TITLE
[Spell][Priest] Prayer of Mending double cast animation + initial cast animation on each bounce

### ISSUE THREAD

**Issue by Asparagoose** [Atlantiss/NetherwingBugtracker#3774] opened 2019-01-01 18:48 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently, Prayer of Mending has 2 issues, animation only that don't seem to affect the skill's function. Firstly, it is triggering the cast animation of the beam going from the Priest to the target twice (only when casting on others), and secondly, it is shooting beams from the Priest to each new target when it bounces from player to player upon healing damage.

Video of incorrect bounce animation: https://www.youtube.com/watch?v=MrLf5-ZIwd4
This also shows the double animation on initial cast, and if you pay attention to the buff timer it is not being refreshed by the second animation as far as I can tell, so it's strictly an animation issue that doesn't appear to be affecting gameplay.

Video of double casting animation: https://www.youtube.com/watch?v=z1WXdrAEgVU&feature=youtu.be

**Current behaviour**: Double cast animation when targeting others, initial cast animation instead of bounce from healed target to new target.

**Expected behaviour**: Only one cast animation when targeting other players as it appears to be when targeting self as displayed in one of the videos, and the beam should bounce from the healed target to the new target, and not from the Priest except on the initial cast.

Here's a Hydra clip showing normal Prayer of Mending interaction: https://youtu.be/KAG9b3-bhMw?t=192
You can see him use PoM, and his friendly spell bars at the bottom showing it jumping from target to target, and no Priest animation is triggered, aswell as no double cast at the beginning.

**Server Revision**: 2550

**Comment by Oldwal** [comment] 2019-01-03 20:02
I just noticed this as well. I tried it on a party member and his combat log actually said that he both gained PoM AND refreshed PoM. This could be a BIG bug if actually 2 PoM goes out.

**Comment by Asparagoose** [comment] 2019-01-03 20:59
I tried to check if it indeed refreshes, and it might still, but for me the duration of the buff didn't seem to refresh and we even tried with 5-6 mobs attacking my target and the heal only went off once each cycle, even though I tried to fit it just before a wave of auto attacks. Unsure still personally, but leaning towards animation only at this time.

**Comment by Desst** [comment] 2019-01-24 07:44
Can confirm this. The projectile keeps firing from the caster itself instead of bouncing. 
Still not sure about the healing effect if it's working as intended or not.

Can we please get a fix on this issue?

**Comment by Wolffenstein** [comment] 2019-02-01 14:09
Fixed in rev 2746.

**Closed by Wolffenstein** 2019-02-01 14:09 UTC
Labels: Class: Priest, Spell
