### ISSUE TITLE
[Profession][Alch] no receipe discovering while creating pots/elixiers

### ISSUE THREAD

**Issue by Alroc90** [Atlantiss/NetherwingBugtracker#6448] opened 2019-12-02 13:25 UTC
**Description**: 
by creating Pots/elixiers and so on you should be albe to discover new receipes.
**Current behaviour**:
created 300 pots/elixiers and didnt discover any receipe
**Expected behaviour**: 
discover a receipe, like a flask
**Server Revision**:

**Comment by Healweed** [comment] 2019-12-02 14:40
Let me ask you this:
 Did you create potions/Elixirs by using Outland mats?

The condition to discover Flasks/Transmute: X to Y/Super Rejuvenation Potion is to craft any **Potion/Elixir by using outland mats.** 
Adding to that, discovering a flask is not exactly easy, as it's already a very low chance(as intended) to discover.

**Comment by Alroc90** [comment] 2019-12-02 14:42
yes sir, only outland mats and some late vanilla like dreamfoil, golden sansam for some elixiers
even tho the chance is low, i think at 300 trys 1 should have been procced, or am i wrong?

**Comment by Healweed** [comment] 2019-12-02 20:04
Golden Sansam and Dreamfoil are vanilla herbs. The condition to discover is by using __**Only**__ outland herbs from Felweed(lowest herb value) to Ancient Lichen/Mana Thistle(Highest herb value).

**Comment by Evolvee** [comment] 2019-12-02 21:09
so can i close this?

**Comment by Alroc90** [comment] 2019-12-02 21:13
guess so. had 1 proc after ~350 trys with only outland herbs now.

**Closed** 2019-12-02 21:28 UTC
Labels: Status: Need Research

**Comment by Alroc90** [comment] 2019-12-05 15:49
yo sorry guys but i did another 350 just now, elixiers procs - rate looks normal but not a single receipe again. u sure that works fine?
