### ISSUE TITLE
[Item][Spell][Priest] Eye of Magtheridon not activating properly

### ISSUE THREAD

**Issue by Queck32** [Atlantiss/NetherwingBugtracker#7853] opened 2020-12-31 08:54 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Eye of Magtheridon does not activate if secondary spell effect such as Shadow Weaving is resisted.

**Current behaviour**:
Eye of Maghteridon (https://www.wowhead.com/item=28789/eye-of-magtheridon#comments) currently does not procc based on "secondary spell effects" such as Shadow Weaving (https://tbc-twinhead.twinstar.cz/?spell=15334). (There are others in the same category that may also not work such as Winters Chill (https://tbc-twinhead.twinstar.cz/?spell=28595) and Shadow Embrace (https://tbc-twinhead.twinstar.cz/?spell=32394)) (I am unable to test those).

![image](https://user-images.githubusercontent.com/75730998/103402526-8de39780-4b4d-11eb-85f3-55f6a020d1ff.png)

It only procs based on primary spell effects, dunno how else to call it such as single target spells (Vampiric Touch / Mind Flay / Mind Blast etc..).
![image](https://user-images.githubusercontent.com/75730998/103401988-802d1280-4b4b-11eb-869b-12b9fda930f3.png)

**Expected behaviour**: 
Eye of Magtheridon should be activated by any resist other than partial resist (spell is partly resisted but damage does go through). Meaning Eye of Magtheridon should be activated by the resist of shadow weaving and other "secondary spell effects"

It is very hard to find a video of this (due to needing the combat log open correctly) but several comments on the wowhead (https://www.wowhead.com/item=28789/eye-of-magtheridon#comments) from TBC patches suggest that this trinket does procc based on Shadow Weaving and similiar effects.
![image](https://user-images.githubusercontent.com/75730998/103402211-7526b200-4b4c-11eb-81c6-834f3609baa2.png)

Further I went through all of the tbc patches (https://wow.gamepedia.com/Patch_2.4.3) and havent found a single mention of Eye of Magtheridon changes, that would make me think that this trinket was designed this way and the comment from 2.1.0 should be relevant for all patches in tbc.

**Server Revision**: 
3578

**Comment by Tereneckla** [comment] 2020-12-31 10:08
Duplicate of #7831

**Closed as completed by Tereneckla** 2020-12-31 10:08 UTC
Labels: Duplicate
