### ISSUE TITLE
[Raid][SWP][Black Temple] Disorient tanking

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6958] opened 2020-05-13 21:04 UTC
**Description**:  on encounters like Eredar Twins and Gurtogg Bloodboil, after disorient (e.g. confounding blow) boss must switch target to 2nd tank, but on both those bosses they're stay hitting 1st disoriented tank

**Current behaviour**: disorient crush crush crush death

**Expected behaviour**: disorient switch happiness rainbow

**Server Revision**: 3371

**Comment by Tereneckla** [comment] 2020-05-13 21:08
Gurtogg Bloodboil does not have a disorient.

**Comment by Tereneckla** [comment] 2020-05-13 22:23
Duplicate of #6797

**Closed by Tereneckla** 2020-05-13 22:23 UTC

**Comment by veekk** [comment] 2020-05-14 00:48
@Tereneckla it's different issue and another boss were mentioned, so that's not really duplicate as u marked it
