### ISSUE TITLE
SSC elevator causes fall damage to characters jumping on it while it moves down

### ISSUE THREAD

**Issue by Red86** [Atlantiss/NetherwingBugtracker#8547] opened 2023-07-13 19:30 UTC
While riding down the elevator at the entrance of SSC, jumping while it's moving down will cause your character to take heavy fall damage.
This seem to be caused by the server snapshotting the height of your character the moment you press space and then comparing to the height of your character when it lands. Since you're jumping on an object that is moving down, the server will think that you have fallen and apply fall damage when you did not.

Expected behaviour:

Jumping on an object that is moving down, should not cause fall damage.

**Comment by Godmatik** [comment] 2023-07-14 14:48
Confirmed, global issue for all elevators but most prominent with this one because of how fast it descends + how long it takes

**Comment by Godmatik** [comment] 2023-07-21 02:46
Mostly fixed after the change you put in, 

If you spam jump on the SSC elevator there is still a small chance you can die though (or at least take some damage)

**Comment by Wolffenstein** [comment] 2023-07-26 11:33
Fixed with the transport system ACore3 port (PR #121)

**Closed as completed by Wolffenstein** 2023-07-26 11:33 UTC
