### ISSUE TITLE
(147) at login

### ISSUE THREAD

**Issue by Westifilms** [Atlantiss/NetherwingBugtracker#4203] opened 2019-01-15 03:21 UTC
Morning
i log in and before i get to character selection i get (147)
it then makes me login again and the cycle continues.
Effectivly i cant get past it to play.
Please help
Im on a mac.
Cheers
Shock

**Comment by fjaros** [comment] 2019-01-15 07:46
Issue happens because game server's SMSG_AUTH_RESPONSE doesn't return any data payload when authenticating with the auth server as a Mac client. Only returns packet length + opcode.

**Comment by Desst** [comment] 2019-01-15 07:55
Confirmed. This should be Hotfixed

**Comment by BAndysc** [comment] 2019-01-16 00:01
Fixed in rev 2639

**Closed** 2019-01-16 21:56 UTC
