### ISSUE TITLE
[Spell] [NPC] [Blade's Edge] Bloodmaul Buzz - Bloodmaul Ogres (any)

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2333] opened 2018-11-05 14:02 UTC
**Description**: Bloodmaul Ogres cast Bloodmaul Buzz which increases max HP by 20%

**Current behaviour**: NPC will heal to full from this buff after it expires.

**Expected behaviour**: buff should only add 20% max HP (like last stand)

**Server Revision**: 2255

**Comment by The14me** [comment] 2018-11-05 16:23
https://github.com/Atlantiss/AtlantissTBCBT/issues/909

**Comment by Mewmewww** [comment] 2018-11-07 17:20
high priority please, its almost impossible for a warrior to kill these before they get to heal unless we can get crits.

**Comment by ScottieDOESknow** [comment] 2018-11-15 11:47
same issue

https://github.com/Atlantiss/NetherwingBugtracker/issues/2211

**Comment by chinupf** [comment] 2019-04-01 13:37
Issue is still present, mobs regain full health after buff expires.

**Comment by Tereneckla** [comment] 2020-01-17 10:02
Duplicate of #2211

**Closed by Tereneckla** 2020-01-17 10:02 UTC
Labels: - Core Mechanic, Spell
