### ISSUE TITLE
[Item] Darkmoon Card: Crusade ABUSE 

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#8724] opened 2023-10-04 22:44 UTC
https://www.wowhead.com/tbc/item=31856/darkmoon-card-crusade

**Description**: 
As description of item says - player should get buff stacks only when **landing a harmful spell on an opponent**.
**Current behaviour**:
At this momemt warlocks (probably mages by using Blizzard and other classes too) are able to stack up this buff infinitely simply by using Rain of fire (https://www.wowhead.com/tbc/spell=5740/rain-of-fire) or Hellfire (https://www.wowhead.com/tbc/spell=1949/hellfire#see-also-ability) without dealing damage to an opponent. So warlocks are able to stack up 10 stacks of this trinket's buff before the boss pull simply by spaming rank 1 Rain of fire on the floor (zero damage to any opponent).
**Expected behaviour**: 
Player should get buff stacks only when **landing a harmful spell on an opponent**.
**Server Revision**: 
3879

**Comment by Godmatik** [comment] 2023-10-05 00:33
https://github.com/Atlantiss/NetherwingBugtracker/issues/7947

Was said to be fixed here, but I can confirm it's still proccing off of any spell cast unintentionally.

However - it appears that in classic - Hellfire should still be able to give you stacks of the trinket. Because you are damaging 
yourself.

![Hellfire](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/4f8559b9-4def-49ba-937f-312c091bf881)

**Comment by Neophrone** [comment] 2023-10-05 01:21
"landing a harmful spell on an opponent" description of an item clearly explain how it should work. Only harmful spell on an opponent. Damaging yourself isn't equal to damaging an opponent. This item was designed to get 10 stacks during the fight and probably losing stacks. The way it's working right now - equal to flat +80 Spell damage.

**Comment by Godmatik** [comment] 2023-10-05 03:02
Yeah I got it - just saying how the functionality currently worked over on classic - might've been a bug there as well

Regardless - rain of fire should not be providing stacks as it currently does. Also heard a priest's mass dispel was instantly giving 10 stacks as long as he cast it on the raid.

**Comment by Godmatik** [comment] 2024-08-29 21:00
Fixed in upcoming spell proc revamp branch.

Hellfire is now the only AoE spell that can proc it without needing a target, this is intended/blizzlike

**Closed as completed by Godmatik** 2024-08-29 21:00 UTC
Labels: Exploit/Abuse - Priority, Status: Confirmed, Item, - Priority
