### ISSUE TITLE
Ghost mushroom takes several hours to respawn.

### ISSUE THREAD

**Issue by Balmory** [Atlantiss/NetherwingBugtracker#9158] opened 2024-08-17 17:14 UTC
[//]: # (Ehttps://www.wowhead.com/tbc/item=8845/ghost-mushroom#comments.)

**Describe**:  Ghost mushrooms in Hinterlands, Zangarmarsh, Ungoro, Maraudon and places do not respawn until you farm almost all the herbs in the zone which will take around 1 hour or more. That also happens with other herbs. Sometimes you farm the entire zone and they do not respawn.

**Current behaviour**: They been respawning every 6 hours, sometimes more or until somebody farms the entire zone.

**Expected behaviour**:  They shouldnt be bounded to other herbs spawn, they should be respawning every 15-20 minutes.

**Server Revision**:  4020

**Comment by Godmatik** [comment] 2024-08-19 21:37
Vanilla herbs need a full rescripting/revamp, especially in vanilla zones, this is part of that

**Comment by Balmory** [comment] 2024-08-20 16:19
Sadly, those herbs are highly needed for TBC phase 4 and 5 due to the high ammount of demon bosses.

**Comment by Godmatik** [comment] 2024-10-06 23:54
Spoke with Wolf and he is aware and it's a system to be revamped at some point soon.

Closing this because it's duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/7667

**Closed as completed by Godmatik** 2024-10-06 23:54 UTC
Labels: Professions, Status: Confirmed, - Priority
