### ISSUE TITLE
Hellfire Ramparts: Chest loot bug.

### ISSUE THREAD

**Issue by Nixazzar** [Atlantiss/NetherwingBugtracker#2889] opened 2018-11-21 00:16 UTC
**Description**: 
During the fight with Nazan, i and one more player died during the fight, chest was looted by tank, and they got items to roll for, however dead party members didn't recive rolling on items, once i was ressurected i was able to loot chest and pick up all items that other people rolled for.

Also, chest stay in the dungeon after looting but it is invisible, but you still can find it with mouse cursor and loot it again. This one is minor visual bug.

**Current behaviour**:
Items from chest can be "ninja'd" by ressurected dead players. Maybe even buy others also, that part wasnt tested. Dead players should also be able to roll for item.
**Expected behaviour**: 
Boss is dead, chest is spawned, someone from party loots it, everyone gets to roll for an item and item cannot be taken from chest before rolling for items is finished.
**Server Revision**:

**Comment by mhdemn** [comment] 2018-11-21 22:18
2339

Did Ramps a few hours ago, chest was missing BoJ for every party member.

-Couldn't get to experience the bug OP describes as we all managed to survive.

**Comment by Zebhor** [comment] 2018-11-22 12:05
I can confirm it. Warrior Levian didn't see loot rolls, because he was dead. 
BoJ drops later patch 2.3+ so Nazan won't drop badges.

video proof: https://www.youtube.com/watch?v=VzgSVJWAFJ4
They confirm it on our teamspeak but its non english so mute sound :) I used greed option on one of blue items and won it becuase 2 of them passed it so i didnt wait for others roll.

**Comment by mhdemn** [comment] 2018-11-22 12:43
So last boss in HC Ramparts is the only boss amongst all HC bosses in the xpac that doesn't reward a BoJ? Not from chest, not from any of the bodies? hm

**Comment by Easyfraggy** [comment] 2018-11-22 16:39
Blizzard and logic doesnt go hand in hand

**Comment by Quaked** [comment] 2019-01-13 21:51
Char is bugged without loot.

**Comment by Jseay1313** [comment] 2019-01-14 07:19
still happens

**Comment by Mcgnomestomp** [comment] 2019-01-27 17:35
Bug still happens. 3/5 weren't able to loot since they died during the encounter. Warrior wasn't able to roll for Hellreaver.

**Comment by Zuntrix** [comment] 2019-02-04 20:06
Did ramparts yesterday. Everyone who died during encounter couldn't get boss loot or quest items, so the guy who stayed alive got all items drops and quest items.

**Comment by williamtheturtle** [comment] 2019-06-01 08:50
Dying on the Last fight HC or Normal the loot will not be able to be rolled on. Only players that survive the encounter will be able to roll on loot from the chest. Can this please be fixed? Bugged as of 6/1/2019

**Comment by randomuser69** [comment] 2019-06-18 00:44
Just happened to my group too:

![WoWScrnShot_061719_203608](https://user-images.githubusercontent.com/51173000/59645545-6a5e2500-9140-11e9-98c6-32313ec9bf05.jpg)
![WoWScrnShot_061719_203621](https://user-images.githubusercontent.com/51173000/59645546-6a5e2500-9140-11e9-856c-0f53cd4877f6.jpg)

**Comment by leeviathan** [comment] 2019-09-07 13:22
Happened to me just now. I died in fight, didn't see rolls for loot. I was resurrected and tried looting the chest and it was empty and disappeared after opening.

**Comment by Manaci** [comment] 2020-01-03 22:38
Fixed with loot rework

**Closed by Manaci** 2020-01-03 22:38 UTC
Labels: - Core Mechanic, Loot
