### ISSUE TITLE
[NPC] [spell] Ivar the Foul// Foul Odor passive aura

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#1284] opened 2018-10-06 07:46 UTC
**Description**: This guy seem to have some OP DPS aura. Strange it was, on my seccond attempt he didnt use that aura anymore

**Current behaviour**: his aura was ticking 7x per seccond
![ivar the foul](https://user-images.githubusercontent.com/17127512/46568881-9e940b80-c94c-11e8-9e0e-4b2ec91823ac.jpg)

**Server Revision**:  2130

**Comment by Evolvee** [comment] 2018-10-06 10:01
@Wolffenstein same as the zombie in EP, problem is passive aura ticking too fast than its supposed to

**Comment by Evolvee** [comment] 2018-10-12 14:53
should already be fixed @Wolffenstein ?

**Comment by Evgenyx123** [comment] 2018-10-19 19:03
![ivar the fool](https://user-images.githubusercontent.com/44301820/47238378-4811dd00-d3e2-11e8-85f2-7768d41d619e.jpg)
The aura did 40 attacks per second to me.

**Comment by The14me** [comment] 2018-12-07 07:11
Look fine to me,Please Pm if still bugged to re-open.

**Comment by The14me** [comment] 2020-02-22 05:40
The first time when I try to reproduce it--->bugged. After that, I can't reproduce it anymore.

**Comment by Wolffenstein** [comment] 2020-05-06 19:44
Fixed in rev 3368.

**Closed by Wolffenstein** 2020-05-06 19:44 UTC
Labels: - Core Mechanic, NPC, Spell
