### ISSUE TITLE
[Spell][Paladin] Blessing of Might and Seal of Crusader interaction

### ISSUE THREAD

**Issue by ffchaosmaster** [Atlantiss/NetherwingBugtracker#159] opened 2018-09-23 11:33 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Can't cast Blessing of Might when Seal of the Crusader is active.
**Current behaviour**:
Message "A more powerful spell is already active" when trying to cast it, when I don't have any other buffs than Seal of the Crusader (which can be used on top of Blessing of Might).
Screenshot:
![wowscrnshot_092318_133041](https://user-images.githubusercontent.com/5289978/45927547-2df4f400-bf35-11e8-8f4a-1dcb6be30935.jpg)

**Expected behaviour**: 
Should be able to cast Blessing of Might even if the Seal of the Crusader buff is active
**Server Revision**:

**Comment by wtRCH** [comment] 2018-09-23 13:00
Already known issue.
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/56

**Closed by wtRCH** 2018-09-23 13:00 UTC
Labels: Class: Paladin, Spell
