### ISSUE TITLE
[Spell][Hunter][Auto Shot] Shoot anyway, even when interrupted

### ISSUE THREAD

**Issue by Argonn** [Atlantiss/NetherwingBugtracker#1525] opened 2018-10-12 11:46 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When i was kiting a Feral Tender, i noticed me dealing damage even when he was to close, of when i moved.
Looking at the log (13:42:04) I shot the tree even when it got interrupted.

![image](https://user-images.githubusercontent.com/2676201/46867402-1ff40e00-ce25-11e8-8126-9af0165844cc.png)

**Current behaviour**:
Your auto shot still hits, even when interrupted

**Expected behaviour**: 
You should not hit your enemy when auto shot gets interrupted

**Server Revision**: 
2165 (patch 203)

**Comment by Ahmpy** [comment] 2018-10-12 14:02
This is probably not caused by a bug, but by your connection to the server. Client side you may have 'interrupted' the auto shot but the server had already completed the shot and hence why this occurs.

**Comment by wtRCH** [comment] 2018-10-12 17:17
Closing due to @Ahmpy comment but I am leaving it with "Status: Need Research"

**Closed by wtRCH** 2018-10-12 17:17 UTC
Labels: Status: Need Research, invalid
