### ISSUE TITLE
[Core][Looting] Missed a Badge of Justice from a boss

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5169] opened 2019-02-24 12:10 UTC
**Description**: Killed the last boss of Heroic Slave pens, I forgot to loot my badge and ported out. Went back in to loot the item but the boss was greyed out and considered like not my own loot.

**Current behaviour**: Killed the last boss of Heroic Slave pens, I forgot to loot my badge and ported out. Went back in to loot the item but the boss was greyed out and considered like not my own loot.

**Expected behaviour**: Should be able to loot the items when coming back

**Server Revision**: 2646

**Comment by Easyfraggy** [comment] 2019-02-24 12:11
![image](https://user-images.githubusercontent.com/36134067/53299009-a12cca00-3835-11e9-90d2-48c0c8c75c34.png)

**Comment by tsu-1** [comment] 2021-04-25 13:32
I think there should be a system implemented where you get items like Badge of Justice delivered to you in a mail, if you forget to loot them from the boss corpse.

**Comment by Godmatik** [comment] 2024-07-14 18:25
Unable to reproduce - able to re-enter the dungeon and loot the missed badge just fine after disbanding group - perhaps fixed with the revamped instance ID system.

**Closed by Godmatik** 2024-07-14 18:25 UTC
Labels: Loot, Dungeon, - Outdated: Need retest/research
