### ISSUE TITLE
Relogging While On Flight

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2317] opened 2018-11-05 08:26 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
[Twitch Clip](https://clips.twitch.tv/ObliviousProudEggplantYouDontSay)

**Current behaviour**:
Relogging while on a flight will cause the gryphon/wyvern to fly directly to closest waypoint of the taxi service, flying through all terrain, water, etc with no collision.

**Expected behaviour**: 
Relogging while on a flight path should be seamless, continuing on the correct track as if the player did not log off.

**Server Revision**: 
2255

**Comment by mhdemn** [comment] 2018-11-05 19:34
Aight since this happened to me while not being in a flight and posting it was considered a duplicate of this version of the bug Ill type it here to make sure it doesn't get missed.
It also happens when you dc while not in a flight. This happened to me while questing, having landed 20 minutes ago.

**Comment by KevinTyrrell** [comment] 2018-11-05 19:49
> since this happened to me while not being in a flight

How?

**Comment by mhdemn** [comment] 2018-11-05 19:58
that's what Im trying to understand, kinda hard since my post got closed without given a single read.
Im playing on wifi lately cause of reasons and I have frequent short periods of packet loss, say 5-6 seconds. WoW can handle that and bring me back without kicking me out from the world. But today my connection is acting up and these packet loss periods have been longer, long enough for WoW to consider me offline and kick me. After one of these dcs it's when I started this random flight from the ogre camp in southwestern Terokkar until where I started my last flight, which was Swamprat Post (Zangarmarsh) - Stonebreaker Hold (Terokkar).

Don't wanna be a bitch, just wanted to make mention of this bug happening also when not dcing in the middle of a flight in case that's relevant information.

**Comment by Easyfraggy** [comment] 2018-11-05 20:06
You said in your post that you were flying.

**Comment by mhdemn** [comment] 2018-11-05 20:08
Sorry if I expressed myself poorly, not a native speaker. I meant it had been 20 minutes since I last landed, my last flight took place that long ago when this dc and consequent bug happened. I'm assuming it's related cause the bug's effect is the same, but I was on land and questing when I lost connection, not in the middle of a flight.

**Comment by Easyfraggy** [comment] 2018-11-16 22:09
So is this still happening? I'm unable to recreate it.

**Comment by mhdemn** [comment] 2018-11-16 22:19
Haven't happened to me again. But I didn't get dced while on flight more than once since that one happened to me, so I can't really tell for sure

**Comment by Easyfraggy** [comment] 2018-11-18 12:02
Can't reproduce after 50 relogs on FP - please reopen if it happens again.

**Closed by Easyfraggy** 2018-11-18 12:02 UTC
Labels: - Core Mechanic
