### ISSUE TITLE
Quest, Searing Gorge, Rise, Obsidion!

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1027] opened 2018-10-01 15:59 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mob Obsidion (8400), after you start the event for the quest, reacts to the player on stealth, as if it has seen you. But he should still be laying on the ground, not moving at all.
**Current behaviour**:
Reacts to player proximity, "looking" at the player's direction (does not attack, tho)
**Expected behaviour**: 
Should lay on the ground, until the RP event finishes and the dwarf starts attacking you.
**Server Revision**: 2105

**Comment by Evolvee** [comment] 2018-10-01 16:01
@Wolffenstein the issue is probably that hostile NPCs with immune to PC flag still react to rogues in stealth (the soft-stealth detection)

**Comment by Wolffenstein** [comment] 2018-10-01 16:32
Fixed in rev 2106.

**Closed by Wolffenstein** 2018-10-01 16:32 UTC
Labels: - Core Mechanic, Status: Confirmed
