### ISSUE TITLE
[NPC] Netherspite 2nd phase

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3632] opened 2018-12-23 23:11 UTC
**Description**: 
Topic is related to the behaviour of Netherspite in the 2nd phase during the boss fight.

**Current behaviour**:
Netherspite will not face the direction of his Netherbreath target.
The Netherbreath attack is always 10 seconds delayed.
Sometimes Netherspite doesn't even use his Netherbreath attack.

**Expected behaviour**: 
Netherspite should visually face the target he's using Netherbreath on.
Unsure if he's supposed to delay Netherbreath for this long.
Netherspite should always use his Netherbreath attack if people are within his range.

**Server Revision**: 
2485

**Comment by AxeCell** [comment] 2018-12-23 23:40
Timestamp of us deliberately attempting to outrange his cast range: https://www.twitch.tv/videos/353241369?t=07h36m01s
Timestamp of his banish phase afterwards: https://www.twitch.tv/videos/353241369?t=07h37m31s

**Comment by Wolffenstein** [comment] 2018-12-24 00:56
The first Netherbreath timer is not a bug.

**Comment by Wolffenstein** [comment] 2018-12-24 01:00
Fixed in rev 2493.

**Closed by Wolffenstein** 2018-12-24 01:00 UTC
