### ISSUE TITLE
Mail Icon not Disappearing

### ISSUE THREAD

**Issue by morielar** [Atlantiss/NetherwingBugtracker#6133] opened 2019-07-19 19:03 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Similar to most recent issue, mail icon appearing as if there is mail even though inbox is empty. tried deleting cache. Tried cancelling an auction and icon briefly went away when i opened mail, then came back. otherwise mail is interacting normally

**Current behaviour**: Mail icon not disappearing when mail is empty

**Expected behaviour**: Mail icon should disappear once mail is emptied

**Server Revision**:

**Comment by danbopes** [comment] 2019-07-19 19:16
Dupe of #6113. Should be reopened.

**Comment by Kaidalen** [comment] 2019-07-20 08:10
BUMP THIS I posted this as well awhile revs ago but they just close the bug report

**Comment by Kaidalen** [comment] 2019-07-20 08:10
Only way it goes away is if you RELOG. ITS BROKEN FELLAS and annoying to see

**Comment by Wolffenstein** [comment] 2019-07-22 05:20
Rev 3080

**Closed by Wolffenstein** 2019-07-22 05:20 UTC
