### ISSUE TITLE
Dark Keeper Nameplate not working properly in Black Rock Depths

### ISSUE THREAD

**Issue by bonampa312** [Atlantiss/NetherwingBugtracker#7978] opened 2021-04-21 03:58 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While running Black Rock Depths there's a picture in the wall, named Dark Keeper Portrait, when opening it it reveals the Dark Keeper Nameplate, when clicking the nameplate a description window should appear with the name of the Dark Keeper dwarf that is in the instance atm

**Current behaviour**:
No description window is being displayed when selecting the Dark Keeper Nameplate

**Expected behaviour**: 
A description window like the one below should be displayed when the Dark Keeper Nameplate is selected
![image](https://user-images.githubusercontent.com/9395720/115494759-e25d7080-a22b-11eb-9232-ea21f5d41930.png)

**Server Revision**: 
Content Patch: 2.3.0 - Revision: 3626

**Comment by Godmatik** [comment] 2024-07-02 01:01
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/1471

BRD needs a full re-write, it is on Wolf's to-do list.

**Closed as completed by Godmatik** 2024-07-02 01:01 UTC
Labels: Dungeon, Gameobject
