### ISSUE TITLE
Warlock`s pet forgets his stat scaling after relog/resummon

### ISSUE THREAD

**Issue by Atrecom** [Atlantiss/NetherwingBugtracker#8246] opened 2023-03-29 17:14 UTC
**Description**:  When you have summoned demon pet, you relog, and pet forgets about scaling from spell damage/stats

**Current behaviour**:  
On the FIRST screenshot it is a normal imp (163 power)
On the SECOND screenshot there is an imp after you re-summon him (160 power)
On the THIRD screenshot there is an imp after character logged in

Both situations are fixed with re-equipping any gear with spell damage/stats, from wich pet scales

**Expected behaviour**: 
Every time you pet has stats from FIRST screenshot

**Server Revision**:  2.0.3 ver. 3714

FIRST:
![image](https://user-images.githubusercontent.com/44858756/228614384-d5ccec61-9687-48cc-ab1f-a5dc4633f160.png)

SECOND:
![image](https://user-images.githubusercontent.com/44858756/228614451-3f278bbf-ff95-455a-a2af-ca71e6a18e37.png)

THIRD: 
![image](https://user-images.githubusercontent.com/44858756/228615074-3562afce-2a29-4c71-98b7-29f3c384c241.png)

**Comment by Atrecom** [comment] 2023-04-01 21:53
every dismount makes pet lower again. bruh

**Comment by Wolffenstein** [comment] 2023-04-03 13:06
I can't reproduce this, does your imp have any buffs on him or something?

**Comment by Atrecom** [comment] 2023-04-03 14:17
Being a demomology warlock, with Demonic Knowledge talent.
https://www.wowhead.com/tbc/spell=35693/demonic-knowledge

May be it`s a reason.

**Comment by Godmatik** [comment] 2024-10-07 01:45
Probably fixed in one of the recent reworks.

I have Demonic Knowledge talent (+ every other pertinent demo talents). Mounting, relogging, resummong, etc - the warlock pet always has the same stats.

**Closed as completed by Godmatik** 2024-10-07 01:45 UTC
Labels: Class: Warlock, Talent, - Priority
