### ISSUE TITLE
[Rogue][Spell][Vanish]

### ISSUE THREAD

**Issue by AndrewNB41191** [Atlantiss/NetherwingBugtracker#4453] opened 2019-01-22 05:27 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Vanished at the exact same moment of death due to a DOT. Couldnt stealth upon respawn. Had to wait till vanish was back off CD to be able to use stealth again.

**Current behaviour**: Couldnt stealth upon respawn. Had to wait till vanish was back off CD to be able to use stealth again.

**Expected behaviour**: Stealth Behaves normally on respawn

**Server Revision**: 2676

**Comment by AndrewNB41191** [comment] 2019-02-05 19:21
![wowscrnshot_020519_122034](https://user-images.githubusercontent.com/44848584/52298576-7b03c080-2940-11e9-8219-a3f9f466a71a.jpg)

**Comment by Godmatik** [comment] 2024-07-04 00:57
Unable to reproduce - vanished at exact moment DOT kills me and I can still stealth.

Might've only been an issue when spell delay was a thing, which it no longer is.

Closing.

**Closed as completed by Godmatik** 2024-07-04 00:57 UTC
Labels: Class: Rogue, Spell
