### ISSUE TITLE
[Quest][Durotar] Taming the Beast

### ISSUE THREAD

**Issue by huntdfl** [Atlantiss/NetherwingBugtracker#375] opened 2018-09-24 13:49 UTC
1. After successfully taming any of the quest pets (happened on all 3-stages of the chain), the pet will not move and you will stuck in an infinite combat state which can only be fixed by restart the WoW client (https://gfycat.com/gifs/detail/SleepyHandsomeArgentineruddyduck). 

2. While doing Part 2 of Taming the beast, the taming rod consumed 1 charge for no reason while other 2 charges failed to tame the crawler. I then had to drop the quest/re-accept to complete that part of the chain. 

3. The 1-charge consume happened again on the next portion of the quest (use taming rod on armored scorpion) but unlike part 2, it successfully tamed the scorpion on the final charge.

**Comment by alicitaqt** [comment] 2018-09-25 15:30
I can confirm this is an issue

**Comment by Cigeso** [comment] 2018-09-26 10:09
happened to me as well

**Comment by pelekon** [comment] 2018-12-13 15:10
fixed in rev 2432 (couldn't reproduce point 3, if it still happen after update then make new issue and link me it on discord)

**Closed by pelekon** 2018-12-13 15:10 UTC
Labels: Class: Hunter, Item, Quest
