### ISSUE TITLE
Pet buffs disappearing on player death.

### ISSUE THREAD

**Issue by ShaneDoyle** [Atlantiss/NetherwingBugtracker#6258] opened 2019-09-03 17:45 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When a player dies, their pet will lose all active buffs. This feels like a bug since dismissing a pet manually will not result in the pet losing buffs. This is especially annoying in situations where the player may die frequently, such as dungeons or battlegrounds. Pets should only lose their buffs in certain situations (entering arenas, death etc.).

**Current behaviour**: When a player dies, their pet will lose all buffs.

**Expected behaviour**: The pet should not lose buffs because the player died.

**Server Revision**: 3116

**Comment by The14me** [comment] 2020-07-08 18:10
Rev.3460 still an issue.

**Comment by Zarant** [comment] 2020-07-11 14:32
Duplicate of #5070

**Closed** 2020-07-11 14:36 UTC
Labels: Status: Confirmed
