### ISSUE TITLE
[Quest][Silithus] Field Duty - NPC not giving dialog option to initiate event

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1276] opened 2018-10-06 02:33 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you accept [Field Duty](https://www.wowhead.com/quest=8507/field-duty) it provides [this usable item ](https://www.wowhead.com/item=21143/unsigned-field-duty-papers), when you use it and try to talk to [Janela Stouthammer](https://www.wowhead.com/npc=15443/janela-stouthammer) she should give a dialog option to start an event that spawns [Captain Blackanvil](https://www.wowhead.com/npc=15440/captain-blackanvil) and after a while a big wasp boss. If Blackanvil survives the encounter he then signs the previous item. 

**Current behaviour**:
Janela Stouthammer doesn't offer a dialog if you prepared the item. 
![vlcsnap-2018-10-06-04h11m00s488](https://user-images.githubusercontent.com/43504905/46566520-5232d680-c920-11e8-854e-aa6136e009f5.png)

**Expected behaviour**: 
Expected dialog option. More info at [the wiki](http://wowwiki.wikia.com/wiki/Quest:Field_Duty#Notes)
**Server Revision**: 
2130

**Comment by Evolvee** [comment] 2018-10-07 14:11
the same event is missing on horde side i guess

**Comment by Evolvee** [comment] 2018-10-07 17:07
alliance side scripted

todo: horde side

**Comment by Evolvee** [comment] 2018-10-08 19:30
both events scripted in rev hehexd

**Comment by Drayo** [comment] 2019-01-23 14:01
The horde event did not work for me, I tried twice.

I got the quest, used the Item and then talked to the Orc Guy, an Elite Mob spawned and all the mobs + me killed him. I even did some decent damage on it.

After that when I talk to him again I only get the same dialog to start the event again, be he should sign my paper, no?

Also, when you click the dialog after doing the event a new one will not start, it takes a good while until it works again.

**Comment by Evolvee** [comment] 2019-01-23 15:04
works fine for me

**Comment by Evolvee** [comment] 2019-01-23 15:09
![image](https://user-images.githubusercontent.com/1942409/51615877-33853980-1f29-11e9-879c-c8de40862a09.png)
![image](https://user-images.githubusercontent.com/1942409/51615883-35e79380-1f29-11e9-9fb8-3d5d738b8f85.png)
![image](https://user-images.githubusercontent.com/1942409/51615895-3d0ea180-1f29-11e9-9097-1662dd6561a9.png)


I just did it on live realm...

must be your addon issue

**Comment by VHaugan** [comment] 2020-07-30 13:32
I am having the same problem as Drayo.

After defeating the elite mob Krug will not sign the papers, I only get the dialog to start the event again.

I am however getting a grey ! above Krug's head, which makes me think this quest is actually supposed to require level 60? I am currently level 59 and was able to pick up the quest just fine.

**Comment by Justfor49** [comment] 2020-08-13 02:49
Same issue is happening for Alliance. The big bug comes out, event plays to kill it, but followup quest NPC shows a silver exclamation mark. Field duty quest is marked as level 56 according to my addon - according to wowhead on classic its lvl 60 quest: https://classic.wowhead.com/quest=8731/field-duty

I assume the issue is that either the follow up quest is wrongly marked as min lvl 60 to acquire or the initial field duty quest should be only acceptable at lvl 60.

**Comment by Godmatik** [comment] 2020-09-19 04:00
Still occurs, as said above, I am below level 60. 

Likely the quest should not have been offered to me.

**Comment by Wolffenstein** [comment] 2023-12-07 15:00
Fixed in rev 3931.

**Closed by Wolffenstein** 2023-12-07 15:00 UTC
Labels: Quest, RP Events, Status: Confirmed
