### ISSUE TITLE
[quest][BEM]Showdown - Broken Again

### ISSUE THREAD

**Issue by jasondilltx** [Atlantiss/NetherwingBugtracker#6345] opened 2019-10-15 13:00 UTC
[Showdown] : https://tbc-twinhead.twinstar.cz/?quest=10742

**Description**: not functioning.  no action upon using the battle horn quest item

**Current behaviour**: no response to using quest item

**Expected behaviour**: goc and rexxar both appear and fight

**Server Revision**:

**Comment by Evolvee** [comment] 2019-10-25 20:51
this is caused by a core issue that we are experiencing now, will be fixed asap

**Closed by Evolvee** 2019-10-25 20:51 UTC
Labels: Status: Confirmed
