### ISSUE TITLE
([Quest] You Robot) NPC Slow Response

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#7476] opened 2020-08-31 01:15 UTC
Upon killing Negatron for quest https://www.wowhead.com/quest=10248/you-robot you are supposed to finish and hand in the quest to Doctor Vomisa, Ph.T. There is a very awkward amount of time after killing Negatron until you can speak to this NPC, about 1-2 minutes of just sitting there. This should probably be changed. Not necessarily a bug, more like an enhancement request, it is strange having to sit there to wait for the question mark to appear.

**Comment by Tereneckla** [comment] 2020-08-31 09:50
Duplicate of #7150

**Closed by Tereneckla** 2020-08-31 09:50 UTC
