### ISSUE TITLE
[NPC][Spell] Coilfang Champion's Cleave Hits 360° in Slave Pens

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#2815] opened 2018-11-19 15:47 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Coilfang Champion](https://db.excalibur.ws/?npc=19885)'s [Cleave](https://db.excalibur.ws/?spell=15284) hit me from behind, several times throughout the dungeon but this is my only recorded incident.

[![Backwards Cleave](http://img.youtube.com/vi/Ldolu9tbfQo/0.jpg)](https://www.youtube.com/watch?v=Ldolu9tbfQo&t=65 "Backwards Cleave")

**Server Revision**: 
2338

**Comment by Easyfraggy** [comment] 2018-11-20 12:18
Cleaves are chain-cleaves in early tbc - not a bug. You are too close to the tank.


360 cleave is a myth - there is no such thing.

**Comment by Jacksn5** [comment] 2018-11-26 13:29
> 
> 
> Cleaves are chain-cleaves in early tbc - not a bug. You are too close to the tank.

Granted, but what about those:

[![Cleave 1](http://img.youtube.com/vi/hPnCnYwW_Ok/0.jpg)](https://www.youtube.com/watch?v=hPnCnYwW_Ok "Cleave 1")

[![Cleave 2](http://img.youtube.com/vi/pM-3mkV82tw/0.jpg)](https://www.youtube.com/watch?v=pM-3mkV82tw "Cleave 2")

I couldn't possibly stand further from the tank while him and I are still in attack range of the NPC.

**Comment by Easyfraggy** [comment] 2018-11-26 19:53
I'm not sure you should be able to avoid these cleaves - need research - Their chain range might be too big.

**Comment by Jacksn5** [comment] 2018-11-28 17:33
I don't quite understand what happened here:
[![Weird Cleave](http://img.youtube.com/vi/HSek--doS2k/0.jpg)](https://www.youtube.com/watch?v=HSek--doS2k "Weird Cleave")
I don't think [Bonechewer Ravener](https://db.excalibur.ws/?npc=17264) is supposed to cleave, yet the animation was there but is labelled as regular melee attack, still 6312 seems too high for both cleave damage or a regular melee attack on (mostly) plate.

**Comment by Easyfraggy** [comment] 2018-11-28 21:49
The cleave animation is from the warrior using cleave on the 2 mobs. You got agro from one of the mobs - not sure how unless the ravener stunned the tank at that moment also? Video is very low quality - can't see the text.

**Comment by Manaci** [comment] 2020-01-03 22:30
Pre-nerf and fixed now

**Closed by Manaci** 2020-01-03 22:30 UTC
Labels: Dungeon, Spell
