### ISSUE TITLE
[NPC] Multiple bugged Venomtail Scorpid npc=3127 in Durotar - "Invalid target"

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#220] opened 2018-09-23 16:17 UTC
**Description**:
[Venomtail Scorpid](https://db.excalibur.ws/?npc=3127)
[![Bugged Venomtail Scorpid 1](http://img.youtube.com/vi/k0EehtK02GA/0.jpg)](https://www.youtube.com/watch?v=k0EehtK02GA "Bugged Venomtail Scorpid 1")

[![Bugged Venomtail Scorpid 2](http://img.youtube.com/vi/ArD6C6d3kxs/0.jpg)](https://www.youtube.com/watch?v=ArD6C6d3kxs&t=15 "Bugged Venomtail Scorpid 2")

Also notice there are no evade swings on the scorpid that's not bugged.

**Server Revision**: 
[2029]

**Comment by Easyfraggy** [comment] 2018-09-24 08:49
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/190

**Closed by Easyfraggy** 2018-09-24 08:49 UTC
Labels: NPC
