### ISSUE TITLE
[Spell][Warrior] Sweeping strikes

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4253] opened 2019-01-16 06:24 UTC
**Current behaviour**: The killing blow you land (can be autoattack/ability) is not affected by sweeping strikes.

**Expected behaviour**:  All of the attacks you make are affected by sweeping strikes.

**Server Revision**: 2635

**Comment by liek0r** [comment] 2019-01-16 11:07
Interesting. I haven't noticed that. But at least execute killing blows are not affected by sweeping strikes. 

See https://github.com/Atlantiss/NetherwingBugtracker/issues/894

**Comment by teddys** [comment] 2019-01-16 18:15
Just noticed that it happens only sometimes ... right now slam killing blow was correctly affected by sweeping strikes. Maybe it has something to do with spell batching?

**Comment by femdead** [comment] 2019-01-17 17:13
also occurs on any attack made in the last ~second of sweeping strikes duration

**Comment by Godmatik** [comment] 2024-08-08 18:54
Duplicate of #8521 
Gonna close this one out

**Closed by Godmatik** 2024-08-08 18:54 UTC
Labels: Class: Warrior, Spell, Hotfix Issue - Priority
