### ISSUE TITLE
Combat bug in EPL Lake

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1179] opened 2018-10-04 04:57 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While swimming in this lake, I get constantly taken into and out of combat. It breaks stealth too. It started right after I entered the lake, and it's not any mob aggroing on me eihter.
Edit: bug kept on happening even after I left the lake, and didnt stop even with vanish.
**Current behaviour**:
![screenshot_528](https://user-images.githubusercontent.com/40346279/46453598-be72d600-c778-11e8-9e37-c2f788eda2c8.png)
**Expected behaviour**: 
This should not happen.
**Server Revision**:

**Comment by The14me** [comment] 2018-10-04 05:03
Issue with InhabitType 3 .If the mob is on the water everything is ok,but when he's on the land...that happen.

**Comment by Tereneckla** [comment] 2020-01-08 00:59
Still happening (even when everything is dead.)
But only in the water.

**Comment by Tereneckla** [comment] 2020-01-22 10:02
Duplicate of #1376

**Closed by Tereneckla** 2020-01-22 10:02 UTC
Labels: NPC, Status: Confirmed
