### ISSUE TITLE
[Warrior] [Spell] Sweeping Strikes does not proc/copy damage from killing blows.

### ISSUE THREAD

**Issue by Easymonka** [Atlantiss/NetherwingBugtracker#8521] opened 2023-06-29 21:36 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you land a killing blow on a target with sweeping strikes active it does not consume a charge and does not copy the damage from the killing blow to another target.

**Expected behaviour**: 
When you land a killing blow on a target the damage is copied and a charge is consumed just like any other attack.

**Server Revision**: 
3819

**Comment by tsu-1** [comment] 2023-07-16 11:45
https://github.com/Atlantiss/NetherwingBugtracker/issues/4253 https://github.com/Atlantiss/NetherwingBugtracker/issues/894

**Comment by Wolffenstein** [comment] 2023-07-20 13:04
https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/35a2182a-c78a-46ce-b559-1b2f9873ce70

?

**Comment by tsu-1** [comment] 2023-07-25 23:02
also occurs on any attack made in the last ~second of sweeping strikes duration

_Originally posted by @femdead in https://github.com/Atlantiss/NetherwingBugtracker/issues/4253#issuecomment-455252674_

**Comment by tsu-1** [comment] 2023-07-25 23:02
@Wolffenstein 

              also occurs on any attack made in the last ~second of sweeping strikes duration

_Originally posted by @femdead in https://github.com/Atlantiss/NetherwingBugtracker/issues/4253#issuecomment-455252674_

**Comment by Godmatik** [comment] 2024-08-08 19:53
https://cdn.discordapp.com/attachments/1260258864356397106/1271192815334068244/08082024456.gif?ex=66b67210&is=66b52090&hm=6199bdabdcdb0348cba4fc61a75f30707aaccd96730ad27a09002a628ea761a4&

https://cdn.discordapp.com/attachments/1260258864356397106/1271192924012413043/08082024123.gif?ex=66b6722a&is=66b520aa&hm=e7fbf1c183829f79d6a2ccfbe9bf86fc8de2e88e9a92e07152172815f47aec79&

Unable to reproduce (ty n.n. for testing)

If there is a consistent way to reproduce, please share it, but it seems to be working as intended.

Closing for now.

**Closed as completed by Godmatik** 2024-08-08 19:53 UTC
Labels: Class: Warrior, Status: Need Research, Talent, - Core Mechanic
