### ISSUE TITLE
[Professions][Herbalism]

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6228] opened 2019-08-19 18:09 UTC
**Description**: Ungatherable Mageroyal (Herb) Node
Location: Wailing Caverns cave area (inside) prior to the instance portal
Faction: Both

There's an ungatherable Mageroyal (herb) node in the Wailing Caverns cave area inside that leads to the instance.
Might want to do a quick pass over all herbalism nodes because people have complained about their inconsistency for months; not enough nodes to go around at all compared to mining.

**Current behaviour**:  Specified node in pre-instance-portal area of Wailing Caverns is ungatherable.

**Expected behaviour**:  All spawned gatherable nodes should be able to be gathered if the person doing the gathering has enough gathering skill.

**Server Revision**: 3106

**Addendum**:  Myself and other players have reported significant herb node spawning/location issues across all of Azeroth and Outland; very inconsistent and severely hinders progression in Alchemy especially for lower level players.  May be worthwhile to do a look at mining and herb spawning overall in both Azeroth and Outland to ensure that nodes are spawning as often as is blizzlike.

**Comment by danbopes** [comment] 2019-08-22 04:02
Dupe of #5687

**Closed** 2019-08-22 23:56 UTC
