### ISSUE TITLE
[SWP] [Grand Warlock Alythess] Meelee hitting Warlock

### ISSUE THREAD

**Issue by Sagoona** [Atlantiss/NetherwingBugtracker#6861] opened 2020-04-13 16:26 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
She meelee hits and one-shots the tanking Warlock.
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/6798 and https://github.com/Atlantiss/NetherwingBugtracker/issues/5783
**Current behaviour**:
Randomly meelee hits the tanking warlock right after a cast of [Blaze](https://www.wowhead.com/spell=45235/blaze) and killing him (No Swing timer reset after completed cast?)
[legacylogs](https://legacyplayers.com/Raids/Viewer/?data=GFHGGYZRHFDHKUCGJZHWGZ2TKVDXIVKWJJHXMZ2SO5LTCQSIOJLWQVDKIJDWKUTPIZVS6TBSPBXDIUCWOR5GO53FHFHFU6STHBDTATTIGNDEYVCOM5JVAMSLOUVXC3STPI2W6USTN5EXGTSBMZHHKVKPNZZWM4DTGNYGG4THPBLSWL2BGBQXIUCXN5QXSRTMMV2FSQLUIVWFGTTLOQZUSMLCMFXUWUKOLFMC6ZRRPFCVUZDCJVAWOZTFNRVUGTDKKB2HETJSOZLGMSKJORJES42ENFTTM6SVOVZHKNTXNAZGM6COMRKVCVKWIRSDAS3ELBAUSMKWIU2E6MSCJFCC6ZZ5HU)
[VoD Timestamp 01:05:20](https://www.twitch.tv/videos/590227226) 
**Expected behaviour**: 
[Alythess](https://www.wowhead.com/npc=25166/grand-warlock-alythess#abilities) should chain cast and never move nor meelee attack since 50k yards range on every spell [Nihilum kill VoD](https://www.youtube.com/watch?v=QwwspsnR6Ro)
**Server Revision**: 
Cant fetch it anymore - kill happened on 12th of april 20:35 ST

**Comment by Tankdiehutte** [comment] 2020-04-13 18:58
Thats a normal Issue with all castermobs. They sometimes hit in between 2 casts if sb is in Hitrange, because casting a spell doesnt reset the hittimer of Mobs.

**Comment by SamVerburg** [comment] 2020-04-13 21:23
Auto attack timer should always reset after casting

**Comment by Sagoona** [comment] 2020-04-13 21:56
Yes swingtimer resets after finishing a cast. Just tested it on a random caster mob - i can upload a clip if u want.

**Comment by Wolffenstein** [comment] 2020-06-07 17:17
Fixed in rev 3377.

**Closed by Wolffenstein** 2020-06-07 17:17 UTC

**Comment by NatsumeLily** [comment] 2020-06-07 20:11
This is most likely not a bug. It's how the mobs react to warlock talent "[Nether Protection]".

For example "Grand Astromancer Capernian" in the Kael'thas fight will move in to melee the warlock tanking her if they have that talent and become immune. That is blizz-like and worked like that on retail.

**Comment by SamVerburg** [comment] 2020-06-08 02:51
> This is most likely not a bug. It's how the mobs react to warlock talent "[Nether Protection]".
> 
> For example "Grand Astromancer Capernian" in the Kael'thas fight will move in to melee the warlock tanking her if they have that talent and become immune. That is blizz-like.

Obviously the warlock warlock tank does not have nether protection

**Comment by NatsumeLily** [comment] 2020-06-08 04:07
> 
> 
> > This is most likely not a bug. It's how the mobs react to warlock talent "[Nether Protection]".
> > For example "Grand Astromancer Capernian" in the Kael'thas fight will move in to melee the warlock tanking her if they have that talent and become immune. That is blizz-like.
> 
> Obviously the warlock warlock tank does not have nether protection

True. But the change log says: 

> Selected bosses (e.g. Grand Warlock Alythess) will no longer move to attack melee when their target becomes briefly immune to their spells

Makes it sound like it "fixes" things like my example which aren't bugs.
